### ISSUE TITLE
sequence返回0_0_00000001

### ISSUE THREAD

**Issue by yanlingsishao** [hanchuanchuan/goInception#100]
{'order_id': '2', 'stage': 'CHECKED', 'error_level': '0', 'stage_status': 'Audit Completed', 'error_message': 'None', 'sql': 'insert into user (id,name,pass_word) values(15,2,1)', 'affected_rows': '1', 'sequence': '0_0_00000001', 'backup_dbname': 'None', 'execute_time': '0', 'sqlsha1': 'None'}
![image](https://user-images.githubusercontent.com/28887713/67932534-0e7fce80-fbff-11e9-9c0f-a03bd76820d7.png)
sequence 是不是应该有值啊，我这咋返回0_0_00000001
![image](https://user-images.githubusercontent.com/28887713/67932611-2ce5ca00-fbff-11e9-9419-2f4d2c0b7b57.png)

**Comment by hanchuanchuan** [comment]
审核阶段不处理 `sequence` 的，记录的是执行时间和 `thread_id`以及执行序号，在执行阶段就有了。
