### ISSUE TITLE
数字变成了科学计数法

### ISSUE THREAD

**Issue by swords1999** [hanchuanchuan/goInception#106]
版本1.1.2
binlog日志里面记录是：@9=80101002310，@11=1507182249.000000这样的格式，备份的内容变成了2.0130101e+07，8.010100231e+10。

**Comment by hanchuanchuan** [comment]
字段是什么类型

**Comment by swords1999** [comment]
字段是decimal(11,0) NOT NULL DEFAULT '0'

**Comment by swords1999** [comment]
> 字段是什么类型

decimal(11,0) NOT NULL DEFAULT '0'

**Comment by swords1999** [comment]
MySQL5.7版本。

**Comment by hanchuanchuan** [comment]
该问题已经修复，请更新到新版本  [Release v1.1.3](https://github.com/hanchuanchuan/goInception/releases/tag/v1.1.3)

**Comment by swords1999** [comment]
> 该问题已经修复，请更新到新版本 [Release v1.1.3](https://github.com/hanchuanchuan/goInception/releases/tag/v1.1.3)

真的效率，谢谢。

**Comment by swords1999** [comment]
验证1.1.3版本解决了此问题。
