### ISSUE TITLE
enable_set_charset参数无效

### ISSUE THREAD

**Issue by swords1999** [hanchuanchuan/goInception#117]
**环境**
 - 数据库: [mysql57]
 - 版本: [1.1.3]

**参数**
enable_set_charset设置无效，写在配置文件中enable_column_charset = true，启动不生效。
inception set enable_column_charset = true;生效，但是创建表依然提示不能指定字符集。

**Comment by hanchuanchuan** [comment]
需要设置允许的字符集 `support_charset`

**Comment by swords1999** [comment]
默认值support_charset = "utf8,utf8mb4"

**Comment by swords1999** [comment]
CREATE TABLE `test_li`  (
  `LOC_a` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ICL_b` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
  `ICL_INFO` varchar(315) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ',
  `TS` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '时间戳'
  PRIMARY KEY (`LOC_MSG`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8

**Comment by swords1999** [comment]
waring：Not allowed set charset for table 'fpsiclmsg'.
Not allowed set collation for table 'fpsiclmsg'.

**Comment by hanchuanchuan** [comment]
为了配置灵活, 表级和列级字符集设置的开关是分开的.
如果想指定表级的字符集和排序规则, 需要指定 
`enable_set_charset` 和 `enable_set_collation`, 有可能还需要 `support_collation`.

下面是摘选的字符集参数说明: 

参数  |  默认值  |  可选范围 | 说明
------------ | ------------- | ------------ | ------------
enable_column_charset   |  false    |   true,false     |  是否允许指定列的字符集
enable_set_charset   |  false    |   true,false     |     是否允许指定表和数据库的字符集
enable_set_collation   |  false    |   true,false     |     是否允许指定表和数据库的排序规则
enable_set_engine    |  true    |   true,false     |     是否允许指定存储引擎,默认为`true`
support_charset | utf8,utf8mb4              | string | 支持的字符集,多个时以逗号分隔
support_collation   | ''             | string | 支持的排序规则,多个时以逗号分隔
support_engine  | innodb   |   string  | 支持的存储引擎类型.默认为`innodb`,此处可以设置多个,以逗号分隔,或者修改默认的存在引擎类型

**Comment by swords1999** [comment]
都配置上就正常了。
