### ISSUE TITLE
请问是否可以实现类型兼容性检测？

### ISSUE THREAD

**Issue by phaibin** [hanchuanchuan/goInception#121]
**描述您想要的功能：**

目前的检测选项`check_column_type_change`，可以针对类型完全不同做出警告，比如`int -> varchar`或者`smallint -> int`。但是有两个问题：

1. 检测不出`varchar(20) -> varchar(10)`这种转换，这种转换其实是有问题的
1. 对于`smallint -> int`其实是安全的转换，可以忽略

不知道能否优化这个选项的检测，增加类型兼容性的判断。谢谢！

**描述您考虑过的解决/替代方案：**

**Comment by hanchuanchuan** [comment]
该问题已优化，请选择[V1.1.5-3](https://github.com/hanchuanchuan/goInception/releases/tag/v1.1.5) 及之后版本

**Comment by phaibin** [comment]
感谢！效率好高。感觉加的这个特性还是很nb的，建议写到文档里面，是个亮点

**Comment by hanchuanchuan** [comment]
感谢建议～

**Comment by hanchuanchuan** [comment]
不好意思哈，其实拖蛮久了，最近有点忙

**Comment by phaibin** [comment]
哈哈，对于一个人维护的开源项目，已经很棒了 👍
