### ISSUE TITLE
能否支持set foreign_key_checks选项

### ISSUE THREAD

**Issue by syman** [hanchuanchuan/goInception#122]
如题，能否开启支持 忽略外键检查选项支持

**Comment by hanchuanchuan** [comment]
请查看 [使用文档的审核选项](https://hanchuanchuan.github.io/goInception/options/)
参数 `enable_foreign_key`

**Comment by syman** [comment]
enable_foreign_key 设置为False，那DDL执行是不是会不检查外键约束表是否存在？

**Comment by hanchuanchuan** [comment]
请自行验证效果.

**Comment by czxin788** [comment]
enable_foreign_key = 0
发现不管用，dml语句仍然报错：
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails

goinception版本是Release Version: v1.3.0-97-gcfb88db-dirty
