### ISSUE TITLE
对mysql空间数据类型的支持

### ISSUE THREAD

**Issue by liuxinwang** [hanchuanchuan/goInception#124]
**描述您想要的功能：**
支持GEOMETRY，POINT，POLYGON等空间类型字段的校验

**描述您考虑过的解决/替代方案：**
增加一个开关选项，是否开启对空间类型字段的校验支持

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
当前空间类型是支持的，是想要有开关控制来关闭吗

**Comment by liuxinwang** [comment]
> 当前空间类型是支持的，是想要有开关控制来关闭吗
我是从archery平台 v1.7.1版本 执行SQL上线脚本的时候对point类型校验时提示语法错误;
如以下建表语句：
create table t1(
id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
c1 point default NULL COMMENT 'c1',
PRIMARY KEY (`id`)
)COMMENT 't1'

审核信息：
ine 3 column 9 near " default NULL COMMENT 'c1',
PRIMARY KEY (`id`)
)COMMENT 't1'" (total length 174)

**Comment by hanchuanchuan** [comment]
空间类型的支持版本是在三个月前，可以手动获取最新的goinception Docker镜像。

**Comment by liuxinwang** [comment]
以获取最新镜像，可以了，多谢。
