### ISSUE TITLE
建议调用选项增加连接字符集选项

### ISSUE THREAD

**Issue by xxlrr** [hanchuanchuan/goInception#129]
**描述您想要的功能：**
我正在使用的goInception（Release Version: v1.0.4-1-g7ed107b）在连接mysql时使用的连接字符集是不可配的，但是由于我们生产环境复杂某些SQL使用默认的连接字符集（UTF8）会导致数据乱码，希望作者能够在调用选项中增加连接字符集选项，谢谢。

**描述您考虑过的解决/替代方案：**
目前暂无替代方案

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
参数`default_charset`可以设置连接数据库的默认字符集，仅能全局设置，默认值 `utf8mb4`。
如果要调用时独立设置，可以启用多个审核服务，配置不同字符集参数。
