### ISSUE TITLE
请问带变量的DML语句是否能够支持？

### ISSUE THREAD

**Issue by zwunix** [hanchuanchuan/goInception#131]
带变量的DML语句如下：
SET @idNO = 0;
  
INSERT INTO
  relation (
    `id`,
    `serv`
  )
SELECT
  @idNO: = @idNO + 1,
  d.serv
FROM
  cont.item_detail d
  INNER JOIN cont.consume_detail c on d.id = c.fk_item_detail_id
  INNER JOIN cont.buy_detail b on c.fk_hjy_detail_id = b.id
WHERE 
  c.audit_flag = 2;

通过审核报错信息如下：
SET @idNO = 0	0	error	Not supported statement type.

INSERT INTO
  relation (	0	error	You have an error in your SQL syntax, near ' = @idNO + 1,
d.serv
FROM
cont.item_detail d
INNER JOIN cont.cont_consume_detail c on d.id = c.fk_item_detail_id
INNER JOIN cont.cont_buy_deta' at line 8

这种类似的DML是否能够支持？

**Comment by hanchuanchuan** [comment]
```sql
-- 冒号后面不要有空格，会有语法错误
@idno: = @idno + 1,
```

不支持设置变量的，不过可以在SELECT中实现类似效果。例如：
```sql
insert into t2(id,c1)
select id,(@rownum:=@rownum+1) as rownum
from t1,(select @rownum:=0) R
order by id desc;
```

**Comment by zwunix** [comment]
好
