### ISSUE TITLE
使用示例能否更详细？

### ISSUE THREAD

**Issue by youbeiwuhuan** [hanchuanchuan/goInception#138]
**描述您想要的功能：**使用示例中能否将返回结果的几列各是什么意思有哪些值代表什么意义说明一下（或是标明在哪里查到）；我这个初次使用者很难定位问题？我运行了几次都返回“”“Must end with commit.”但不知道错在哪里

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
先参考一下这个吧，[结果集列说明](https://github.com/hanchuanchuan/inception-document/blob/master/docs/results.md) 
这是老版本inception的文档，新文档会尽快更新一下，到时在首页的文档链接上查看即可。

另外，你的这个报错指的是语句结尾不正确，正确格式参考[使用示例](https://hanchuanchuan.github.io/goInception/demo.html) 中的SQL。

**Comment by hanchuanchuan** [comment]
最新文档参考 [结果集说明](https://hanchuanchuan.github.io/goInception/result.html)

**Comment by youbeiwuhuan** [comment]
谢谢！
