### ISSUE TITLE
goInception不支持commit

### ISSUE THREAD

**Issue by heistt** [hanchuanchuan/goInception#146]
应用版本:
goinceotion-1.1.4

goinception不支持commit语句，显示为error
![image](https://user-images.githubusercontent.com/18729728/71609309-5355c080-2bc2-11ea-8f36-ae2c3ad0817c.png)

切换为inception后，则变为warning
![image](https://user-images.githubusercontent.com/18729728/71609314-581a7480-2bc2-11ea-83f9-0769d48702ad.png)

**Comment by hanchuanchuan** [comment]
都不支持的，这个语法不允许。
goinception最新版本已支持事务功能，具体看release和文档。

**Comment by heistt** [comment]
> 都不支持的，这个语法不允许。
> goinception最新版本已支持事务功能，具体看release和文档。

你好，刚才测试了一下，如果mysql实例autocommit=0，是否启动trans选项，DML执行后都不会提交

**Comment by hanchuanchuan** [comment]
感谢反馈，在实例关闭`autocommit`时，确实不会提交，该问题稍后修复。
经测试在启用`trans`时，会进行提交。（未提交的可能是版本较低，尚未包含事务功能）

**Comment by hanchuanchuan** [comment]
问题已修复，可点击下载。 [v1.1.5-39 下载](https://github.com/hanchuanchuan/goInception/releases/download/v1.1.5/goInception-linux-amd64-v1.1.5-39-g60b5647.tar.gz)

**Comment by heistt** [comment]
> 问题已修复，可点击下载。 [v1.1.5-39 下载](https://github.com/hanchuanchuan/goInception/releases/download/v1.1.5/goInception-linux-amd64-v1.1.5-39-g60b5647.tar.gz)

效率很高，非常感谢！

**Comment by zwunix** [comment]
为什么下载了v1.1.6-13，还是不支持commit：
       commit | 0 | error | Not supported statement type.

**Comment by hanchuanchuan** [comment]
都不支持，这个语法不允许。
事务功能是另一回事，详细使用看文档。
