### ISSUE TITLE
DDL和DML共存审核时报错

### ISSUE THREAD

**Issue by RedCosme** [hanchuanchuan/goInception#147]
**描述**
DDL和DML共同执行
先table_a 添加字段column for_language ;
然后向table_b中插入数据，插入数据来源是从table_a里面select出来的数据包含刚才添加的字段for_language
报错说unknown column "table_a.for_language"  in "field list"

**重现**
alter table_a add column for_language default NULL;
insert into table_b (for_language, aa, bb, cc ) select table_a.for_language, table_a.aa, table_bb from table_a;

**环境**
 - 数据库: [mysql]
 - 版本: [5.7.21]
 goinception版本1.0.5

**Comment by hanchuanchuan** [comment]
确实是审核的一个小问题。
`insert`操作只判断了是否有新表，所以这个在做`explain`时，数据库实际尚未存在该字段。

**Comment by RedCosme** [comment]
嗯好的，谢谢
