### ISSUE TITLE
在mysql组复制+proxysql架构上，执行create语句失败

### ISSUE THREAD

**Issue by peng19832** [hanchuanchuan/goInception#148]
**描述**
如题：在mysql组复制架构上，执行create语句失败。
简单的create table语句，审核检测通过后，执行报错：
    **实例read_only=1，禁止执行变更语句!**
CREATE TABLE `test_lee`(
  `id` int(0) UNSIGNED NOT NULL COMMENT '主键',
  `name` varchar(20) NOT NULL DEFAULT 'xsswsdsdfsdf' COMMENT '名字',
  PRIMARY KEY (`id`)
) COMMENT = '测试';

**重现**
审核通过后，上线执行语句。

**环境**
 - 数据库: [mysql]
 - 版本: [例如 8.0]
 - 架构: mgr + proxysql

**参数**
read_only

**Comment by hanchuanchuan** [comment]
使用的是archary吗

**Comment by peng19832** [comment]
> 使用的是archary吗

是的

**Comment by hanchuanchuan** [comment]
在QQ群有人反馈过，是archery判断的问题，可以等作者修复。
如果要自行修复的话，根据错误提示查找相关代码，判断read_only时把ON/OFF和1/0均处理了即可。

**Comment by peng19832** [comment]
> 在QQ群有人反馈过，是archery判断的问题，可以等作者修复。
> 如果要自行修复的话，根据错误提示查找相关代码，判断read_only时把ON/OFF和1/0均处理了即可。

喔，好的，我去archery那边问问
