### ISSUE TITLE
添加唯一索引报错

### ISSUE THREAD

**Issue by liuqian1990** [hanchuanchuan/goInception#151]
2020/01/08 11:25:31.074 osc.go:768: [error] origin sql: alter table tb_archery add unique index uniq_test_ghost_3 (test_ghost_3)
2020/01/08 11:25:31.074 osc.go:769: [error] parsed after: ADD UNIQUE `uniq_test_ghost_3`(`test_ghost_3`)

**Comment by liuqian1990** [comment]
发现 `uniq_test_ghost_3`(`test_ghost_3`)这个没有空隔，成了一个字串

**Comment by hanchuanchuan** [comment]
暂时修改成 `ADD UNIQUE uniq_test_ghost_3(test_ghost_3)` 格式即可，解析ALTER子句时添加了长度校验，以避免解析错误。
稍后会修复。

**Comment by liuqian1990** [comment]
还是一样报错

**Comment by hanchuanchuan** [comment]
![image](https://user-images.githubusercontent.com/18544383/71953842-613cbe80-321e-11ea-935a-aaf397dbdd2f.png)

**Comment by hanchuanchuan** [comment]
问题已修复，点击 [Releases](https://github.com/hanchuanchuan/goInception/releases/tag/v1.1.6) 选择 v1.1.6-13 版本下载
或者使用 `docker pull hanchuanchuan/goinception:latest` 获取最新docker版
