### ISSUE TITLE
类型不变加大显示长度

### ISSUE THREAD

**Issue by liuqian1990** [hanchuanchuan/goInception#158]
type 原类型tinyint(1)

ALTER TABLE a CHANGE type type TINYINT(4) NOT NULL DEFAULT '1' 

这种情况是走gh-ost还是直接过

**Comment by hanchuanchuan** [comment]
除rename操作外,只要满足表大小设置, 均会走设置的ddl工具

**Comment by liuqian1990** [comment]
但像这种都是直接修改元数据的

**Comment by hanchuanchuan** [comment]
可以做一下详细的测试,看是否会锁表(以及对应的mysql版本)
