### ISSUE TITLE
MySQL5.7语法不支持

### ISSUE THREAD

**Issue by swords1999** [hanchuanchuan/goInception#159]
CREATE TABLE `app_test` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DataChange` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `DataChange_w` varchar(32) DEFAULT '' COMMENT '最后修改人邮箱前缀',
  `DataChange_r` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`Id`) USING BTREE
)
报错：

Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
--
原因是5.6仅支持一个TIMESTAMP字段，5.7可以支持多个。

**Comment by hanchuanchuan** [comment]
查看timestamp相关参数，有参数控制的。
另外，`DataChange_r` 去掉 `DEFAULT CURRENT_TIMESTAMP` 应该可以审核通过的。
