### ISSUE TITLE
[新功能方案讨论] 实现会话级变量设置

### ISSUE THREAD

**Issue by hanchuanchuan** [hanchuanchuan/goInception#166]
**描述您想要的功能：**

添加会话级变量设置，实现更灵活的审核规则配置。

用法：
```sql
/*--user=xxx;--password=xxx;--host=127.0.0.1;--port=3306;--check=1;*/
inception_magic_start;
use test;

-- 支持用法
inception set ghost_on = 0,osc_on = 1; /* 支持 */
inception set session ghost_on = 0,osc_on = 1; /* 支持, 和上面完全一致 */

-- 错误示例
inception set global ghost_on = 0,osc_on = 1; /* ERROR: 全局变量仅支持单独设置 */
inception set ghost_on = '123'; /* ERROR: Variable 'ghost_on' can't be set to the value of '123' */
inception set level er_table_must_have_comment = 2; /* ERROR: 暂不支持会话级的自定义审核级别 */

create table t1(id int primary key,c1 bigint(10));
 
inception_magic_commit;
```

**重要说明：**
inception会话变量正确设置时，该行SQL不再返回！以免后续误发送到mysql端。
（会记录相应日志，以便追溯查看）

示例一：
```sql
/*--user=xxx;--password=xxx;--host=127.0.0.1;--port=3306;--check=1;*/
inception_magic_start;
use test;

drop table if exists t1,t2;

inception set check_table_comment = 1;

create table t1(id int primary key);

inception set check_table_comment = 0;

create table t2(id int primary key);
 
inception_magic_commit;
```
审核结果(隐藏了部分列)：
注意，`inception set` 的行并不返回！除非set失败报错。

order_id |  stage  | error_level |   stage_status   |         error_message        |                    sql      
-----|------|------|-----------|--------------|----------------------------
1     | CHECKED |      0      | Audit Completed |          None         |             use test_inc
2     | CHECKED |      0      | Audit Completed |          None         |      drop table if exists t1,t2
3     | CHECKED |      1      | Audit Completed | 表 't1' 需要设置注释. | create table t1(id int primary key)values(1,1,1) 
4     | CHECKED |      0      | Audit Completed |          None         | create table t2(id int primary key)

**Comment by hanchuanchuan** [comment]
相关issue #157

**Comment by hhyo** [comment]
除了在inception_magic域范围内设置，在范外可以设置么
