### ISSUE TITLE
修改表的auto_increment值，执行结果成功，实际值并未改变

### ISSUE THREAD

**Issue by 1393467261** [hanchuanchuan/goInception#169]
**描述**
修改表的auto_increment值，执行结果成功，实际值并未改变*重现**
**模拟重现的步骤**
create table test(id int not null auto_increment primary key, name varchar(11));
--此时auto_increment为空，正常
--执行以下语句
alter table test auto_increment = 10;
--此时auto_increment为空，不正常
--在mysql中执行没有上述问题
**环境**
 - 数据库: [mariadb]
 - 版本: [10.0.22]

**Comment by hanchuanchuan** [comment]
在测试环境中打开数据库的 `general_log` 并重试一下。

**Comment by hanchuanchuan** [comment]
问题确定了？

**Comment by 1393467261** [comment]
还没，等有时间复现下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hanchuanchuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 晚上9:36
收件人:&nbsp;"hanchuanchuan/goInception"<goInception@noreply.github.com&gt;;
抄送:&nbsp;"动物世界"<1393467261@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [hanchuanchuan/goInception] 修改表的auto_increment值，执行结果成功，实际值并未改变 (#169)





 
问题确定了？
