### ISSUE TITLE
pt-online-schema-change添加参数建议

### ISSUE THREAD

**Issue by 1393467261** [hanchuanchuan/goInception#170]
**描述您想要的功能：**
pt-online-schema-change支持检测pxc集群数据同步情况来控制pt进程的配置--max-flow-ctl，如果不加此参数执行pt，可能导致pxc集群负载高，进而导致节点crash。希望作者可以考虑下，加入这个配置项并应用到pt中

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**
https://www.percona.com/doc/percona-toolkit/3.0/pt-online-schema-change.html#cmdoption-pt-online-schema-change-max-flow-ctl

**Comment by hanchuanchuan** [comment]
好的，后续会添加。

**Comment by 1393467261** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hanchuanchuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 晚上9:44
收件人:&nbsp;"hanchuanchuan/goInception"<goInception@noreply.github.com&gt;;
抄送:&nbsp;"动物世界"<1393467261@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hanchuanchuan/goInception] pt-online-schema-change添加参数建议 (#170)





 
好的，后续会添加。

**Comment by hanchuanchuan** [comment]
已添加新参数，#172

[v1.2.1-12-max_flow_ctl](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.1)
