### ISSUE TITLE
添加可以执行创建视图，函数，过程SQL的功能

### ISSUE THREAD

**Issue by dengpixiong** [hanchuanchuan/goInception#171]
**描述您想要的功能：**
添加可以执行创建视图，函数，过程SQL的功能

**描述您考虑过的解决/替代方案：**
目前不支持创建视图，函数，过程，希望可支持，功能更完善。

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
这部分功能除视图有可能支持外，函数和过程很难。
一方面TiDB本身暂不支持，两者大规模数据库管理通常是禁用这些的。
