### ISSUE TITLE
语句在WHERE后无关联字段竟然能审核通过

### ISSUE THREAD

**Issue by zwunix** [hanchuanchuan/goInception#178]
**描述**
语句在WHERE后无关联字段竟然能审核通过

**重现**
例如
update cont_XXX
set con_status = 3
where 
71532599925489664;

**环境**
 - 数据库: [mysql]
 - 版本: [5.6]

造成了大量数据被错误地修改。

**Comment by hanchuanchuan** [comment]
因为标准MySQL语法是允许的，所以审核和执行都通过了。

**Comment by hanchuanchuan** [comment]
后续会尝试添加限制，数据恢复可以通过备份功能里的回滚SQL。

**Comment by hanchuanchuan** [comment]
问题已优化. 注意区分版本
[v1.2.1-21](https://github.com/hanchuanchuan/goInception/releases)
