### ISSUE TITLE
SQL语句太长产生WARNING：Backup: Data too long for column 'sql_statement' at row 1

### ISSUE THREAD

**Issue by zwunix** [hanchuanchuan/goInception#180]
**描述**
开发提交的语句太长，超出了65535，在备份该语句的时候warning。信息如下：
Backup: Data too long for column 'sql_statement' at row 1

**环境**
 - 数据库: [mysql]
 - 版本: [5.6]

**Comment by hanchuanchuan** [comment]
有以下几个方案供选择：

1. 选择一个新的备份实例，备份表结构自动创建时会自动创建为mediumtext类型
2. 手动修改所有备份库的备份表表结构，将`sql_statement`的类型改为mediumtext类型
3. 该警告仅影响该行的回滚，其他无影响，或选择性忽略

以上方案任选其一即可

**Comment by zwunix** [comment]
是的。现在也是这样修改的。

**Comment by hanchuanchuan** [comment]
需要注意版本的问题，版本须高于 `v1.0-rc3`
![image](https://user-images.githubusercontent.com/18544383/77633773-e8324500-6f8a-11ea-8b67-d5d6be8b6e7e.png)
