### ISSUE TITLE
编译报冲突错误

### ISSUE THREAD

**Issue by tiechaowang** [hanchuanchuan/goInception#181]
执行 make parser编译报如下冲突错误
CGO_ENABLED=0 GO111MODULE=on go build  -o bin/goyacc parser/goyacc/main.go
bin/goyacc -o /dev/null parser/parser.y
Parse table entries: 852395 of 2131686, x 16 bits == 1704790 bytes
bin/goyacc -o parser/parser.go parser/parser.y 2>&1 | egrep "(shift|reduce)/reduce" | awk '{print} END {if (NR > 0) {print "Find conflict in parser.y. Please check y.output for more information."; exit 1;}}'
rm -f y.output

**Comment by hanchuanchuan** [comment]
没有输出表示是成功的

**Comment by tiechaowang** [comment]
> 没有输出表示是成功的

明白了，感谢！
