### ISSUE TITLE
ddl dml 切换执行报错

### ISSUE THREAD

**Issue by kcxg** [hanchuanchuan/goInception#182]
**描述**
执行完DDL 执行DML 然后再切换到ddl 会报错

**重现**
模拟重现的步骤
建表 插入语句 再建表时报错. no database selected

**环境**
 - 数据库: [mysql]
 - 版本: [5.7.17]

**参数**
可能与问题相关的设置参数

**Comment by kcxg** [comment]
goincetion 版本 1.2.1

**Comment by hanchuanchuan** [comment]
请给出重现示例。

以下测试正常：
![image](https://user-images.githubusercontent.com/18544383/78091040-73359400-73fe-11ea-968a-b6739532102d.png)

**Comment by kcxg** [comment]
`[
    {
        "id": 1,
        "stage": "CHECKED",
        "errlevel": 0,
        "stagestatus": "Audit Completed",
        "errormessage": "",
        "sql": "use `archer`",
        "affected_rows": 0,
        "sequence": "0_0_00000000",
        "backup_dbname": "",
        "execute_time": "0",
        "sqlsha1": "",
        "backup_time": "0",
        "actual_affected_rows": ""
    },
    {
        "id": 2,
        "stage": "EXECUTED",
        "errlevel": 0,
        "stagestatus": "Execute Successfully\nBackup Successfully",
        "errormessage": "",
        "sql": "DROP TABLE IF EXISTS `t1`",
        "affected_rows": 0,
        "sequence": "1585740974_1921375_00000001",
        "backup_dbname": "10_4_106_151_3306_archer",
        "execute_time": "0.025",
        "sqlsha1": "",
        "backup_time": "0",
        "actual_affected_rows": ""
    },
    {
        "id": 3,
        "stage": "EXECUTED",
        "errlevel": 0,
        "stagestatus": "Execute Successfully\nBackup Successfully",
        "errormessage": "",
        "sql": "CREATE TABLE `t1`  (\n  `id` int(11) NOT NULL,\n  `c1` int(11) DEFAULT NULL,\n  `c2` int(11) DEFAULT NULL,\n  PRIMARY KEY (`id`) USING BTREE\n) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic",
        "affected_rows": 0,
        "sequence": "1585740975_1921375_00000002",
        "backup_dbname": "10_4_106_151_3306_archer",
        "execute_time": "0.570",
        "sqlsha1": "",
        "backup_time": "0",
        "actual_affected_rows": ""
    },
    {
        "id": 4,
        "stage": "EXECUTED",
        "errlevel": 0,
        "stagestatus": "Execute Successfully\nBackup Successfully",
        "errormessage": "",
        "sql": "INSERT INTO `t1` VALUES (1, 1, 1)",
        "affected_rows": 1,
        "sequence": "1585740975_1921375_00000003",
        "backup_dbname": "10_4_106_151_3306_archer",
        "execute_time": "0.013",
        "sqlsha1": "",
        "backup_time": "0.093",
        "actual_affected_rows": ""
    },
    {
        "id": 5,
        "stage": "EXECUTED",
        "errlevel": 1,
        "stagestatus": "Execute Successfully",
        "errormessage": "Backup: Skip backup because there is no table structure information.",
        "sql": "DROP TABLE IF EXISTS `t2`",
        "affected_rows": 0,
        "sequence": "1585740975_1921375_00000004",
        "backup_dbname": "",
        "execute_time": "0.015",
        "sqlsha1": "",
        "backup_time": "0",
        "actual_affected_rows": ""
    },
    {
        "id": 6,
        "stage": "EXECUTED",
        "errlevel": 2,
        "stagestatus": "Execute failed",
        "errormessage": "Execute: No database selected.",
        "sql": "CREATE TABLE `t2`  (\n  `id` int(11) NOT NULL,\n  `c1` int(11) DEFAULT NULL,\n  `c2` int(11) DEFAULT NULL,\n  PRIMARY KEY (`id`) USING BTREE\n) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic",
        "affected_rows": 0,
        "sequence": "1585740975_0_00000005",
        "backup_dbname": "",
        "execute_time": "0.013",
        "sqlsha1": "",
        "backup_time": "0",
        "actual_affected_rows": ""
    }
]`

建表  插入  再建表时会报错

**Comment by kcxg** [comment]
![image](https://user-images.githubusercontent.com/31840413/78134019-05b35300-7452-11ea-8b98-272e893f3894.png)

![image](https://user-images.githubusercontent.com/31840413/78133969-f3d1b000-7451-11ea-981b-9da5d2b67c1e.png)

我先建表  再插入 然后再再建表时报错

**Comment by hanchuanchuan** [comment]
下述步骤经测试是成功的.
```sql
drop table if exists t1,t2;

create table t1(id int primary key,c1 int);

insert into t1 values(1,1),(2,2);

alter table t1 add column c2 int;

insert into t1 values(3,3,3);

drop table if exists t1,t2;

create table t2(id int primary key,c1 int);

insert into t2 values(3,3);

```

需要提供调用参数和SQL示例.

**Comment by kcxg** [comment]
执行你发的上述sql 我的也是成功的 

我的报错sql:
`DROP TABLE IF EXISTS `t1`;
CREATE TABLE `t1`  (
  `id` int(11) NOT NULL,
  `c1` int(11) DEFAULT NULL,
  `c2` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

INSERT INTO `t1` VALUES (1, 1, 1);

DROP TABLE IF EXISTS `t2`;
CREATE TABLE `t2`  (
  `id` int(11) NOT NULL,
  `c1` int(11) DEFAULT NULL,
  `c2` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;`

![image](https://user-images.githubusercontent.com/31840413/78202754-bb6cb900-74c7-11ea-98cf-a497628c382f.png)

**Comment by hanchuanchuan** [comment]
开启事务导致的，后续会修复。 `--trans=5000`

**Comment by hanchuanchuan** [comment]
该问题已修复. 更新最新版本即可.
