### ISSUE TITLE
建表语句里面不能有json，否则语法错误，是怎么回事

### ISSUE THREAD

**Issue by czxin788** [hanchuanchuan/goInception#186]
**描述**
建表语句里面不能有json，否则语法错误，是怎么回事

**重现**
CREATE TABLE `share_data_template` (
  `id` bigint(32) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id，自增',
    `share_template` json DEFAULT NULL COMMENT '模板内容',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COMMENT='通用分享数据模板表';

您的SQL存在语法错误， near 'json DEFAULT NULL COMMENT '模板内容',
PRIMARY KEY (`id`)
) ENGINE=InnoDB A' at line 3

但是直接到数据库里面是可以执行这个建表语句的。

**环境**
 - 数据库: mysql
 - 版本: 5.7.22

**Comment by hanchuanchuan** [comment]
确认一下goinception版本，升级版本重试。

**Comment by hanchuanchuan** [comment]
语法是支持的。

**Comment by czxin788** [comment]
我用错了，我用成inceptiopn了。不是goinception
