### ISSUE TITLE
pt-online-schema-change工具使用检测

### ISSUE THREAD

**Issue by tiechaowang** [hanchuanchuan/goInception#187]
在goinception里配置了osc相关参数，执行ddl的sql，怎么确认goinception用了pt-online-schema-change工具执行sql；或者看到pt-online-schema-change工具执行的log输出？测试开启debug模式也没看到相关日志输出

**Comment by hanchuanchuan** [comment]
1. 升级到最新版本
2. 在使用pt或者gh-ost时，goinception日志会输出使用了哪个DDL工具
3. 开启参数`osc_print_sql `会打印部分SQL日志

**Comment by ganlanshu** [comment]
> 3. 开启参数`osc_print_sql `会打印部分SQL日志
开启了 osc ，并且osc_print_sql也开启了，但是发现只打印了部分osc的日志，没有全部打印，不知道原因是什么呢
