### ISSUE TITLE
为goInception增加WEB支持

### ISSUE THREAD

**Issue by hhyo** [hanchuanchuan/goInception#19]
为作者持续给力的更新点赞

Archery将会在下一个版本接入goInception的审核与执行 https://github.com/hhyo/Archery/pull/136

目前在线体验版已经更新，🆙🆙🆙

**Comment by hanchuanchuan** [comment]
已在首页添加Archery项目信息，感谢开源~~

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/releases/tag/v1.5.2
