### ISSUE TITLE
go 调用当语法正确时有些列无显示,错误显示

### ISSUE THREAD

**Issue by liuqian1990** [hanchuanchuan/goInception#196]
![image](https://user-images.githubusercontent.com/8868514/79430021-e6442a80-7ffa-11ea-9714-62b151c96993.png)
[goinception.txt](https://github.com/hanchuanchuan/goInception/files/4485651/goinception.txt)

**Comment by hanchuanchuan** [comment]
代码问题。有些列不是string类型的，类型不正确的话，`rows.Scan`写不了值。
可以调整为interface类型，或者调整为正确的类型。
