### ISSUE TITLE
select语句后带有\G会显示错误

### ISSUE THREAD

**Issue by zhuxingtao** [hanchuanchuan/goInception#197]
**描述**
select语句后带有\G会显示错误

**重现**
select * from db.table limit 1\G; 提交给goinception检测, 会认为有错误,去掉\G正常

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**Comment by hanchuanchuan** [comment]
`\G`并非MySQL语法. 只是MySQL Client为了方便显示数据的一种特殊配置. 请注意甄别.
可以通过代码连接MySQL测试一下,会有如下错误:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\G'
```
