### ISSUE TITLE
sql语句复杂时queryTree为空

### ISSUE THREAD

**Issue by zhuxingtao** [hanchuanchuan/goInception#198]
**描述**
sql语句复杂时queryTree为空 返回 []

**重现**
SELECT t.*,
       Count(clazz.clazz_number)                                clazzCount,
       Group_concat(clazz.clazz_number SEPARATOR ';') clazzListStr
FROM   (SELECT assignor.assignor,
               assignor.assignor_name                  assignorName,
               assignor.tag,
               assignor.status,
               assignor.tag                            dominantSubject,
               Count(al.check_status)                  total,
               Sum(IF (al.check_status = 2, 1, 0))     submit,
               Sum(IF (al.check_status = 0
                        OR al.check_status = 1, 1, 0)) unSubmit,
Sum(IF (to_days(al.assign_time) = to_days(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) + 0 DAY)),1,0)) day1,Sum(IF (to_days(al.assign_time) = to_days(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) - 1 DAY)),1,0)) day2,Sum(IF (to_days(al.assign_time) = to_days(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) - 2 DAY)),1,0)) day3,Sum(IF (to_days(al.assign_time) = to_days(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) - 3 DAY)),1,0)) day4,Sum(IF (to_days(al.assign_time) = to_days(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) - 4 DAY)),1,0)) day5,Sum(IF (to_days(al.assign_time) = to_days(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) - 5 DAY)),1,0)) day6,Sum(IF (to_days(al.assign_time) = to_days(date_sub(curdate(),INTERVAL WEEKDAY(curdate()) - 6 DAY)),1,0)) day7        FROM   a_assignor assignor
               LEFT JOIN a_lesson al
                      ON al.assignor = assignor.assignor
           GROUP  BY assignor.assignor) t
       LEFT JOIN a_assignor_clazz clazz
              ON t.assignor = clazz.assignor
   GROUP  BY t.assignor   order by assignorName desc limit 10;

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by zhuxingtao** [comment]
是不是不支持select中用了concat函数？

**Comment by hanchuanchuan** [comment]
支持的。经过测试是ok的。建议升级到最新版本试试看。

**Comment by zhuxingtao** [comment]
> 支持的。经过测试是ok的。建议升级到最新版本试试看。

select CONCAT(id + 158084,';\"',edited_user,'\";\"\";\"',execute_time,'\";\"\";\"\";\"\";\"\";\"',apply_type,'\"') from erp.change_apply where apply_type in (101, 121) and status = 5;

我使用这条语句返回的queryTree为 []

**Comment by hanchuanchuan** [comment]
检查一下你代码，以及是否有其他处理。下面是通过python的示例调用的结果：
id | statement | errlevel | query_tree | errmsg 
-- | -- | -- | -- | ------------
 1  |                                            use test_inc                                            |    0     |  {"text":"use test_inc","DBName":"test_inc"} |  None  |
| 2  | select CONCAT(id + 158084,';"',edited_user,'";"";"',execute_time,'";"";"";"";"";"',apply_type,'"') |    0     | {"text":"select CONCAT(id + 158084,';\"',edited_user,'\";\"\";\"',execute_time,'\";\"\";\"\";\"\";\"\";\"',apply_type,'\"')\nfrom erp.change_apply where apply_type in (101, 121) and status = 5","resultFields":null,"SQLBigResult":false,"SQLBufferResult":false,"SQLCache":true,"SQLSmallResult":false,"CalcFoundRows":false,"StraightJoin":false,"Priority":0,"Distinct":false,"From":{"text":"","TableRefs":{"text":"","resultFields":null,"Left":{"text":"","Source":{"text":"","resultFields":null,"Schema":{"O":"erp","L":"erp"},"Name":{"O":"change_apply","L":"change_apply"},"DBInfo":null,"TableInfo":null,"IndexHints":null,"PartitionNames":null},"AsName":{"O":"","L":""}},"Right":null,"Tp":0,"On":null,"Using":null,"NaturalJoin":false,"StraightJoin":false}},"Where":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Op":1,"L":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Expr":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"apply_type","L":"apply_type"}},"Refer":null},"List":[{"text":"","k":1,"collation":0,"decimal":0,"length":0,"i":101,"b":null,"x":null,"Type":{"Tp":8,"Flag":128,"Flen":3,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"flag":0,"projectionOffset":-1},{"text":"","k":1,"collation":0,"decimal":0,"length":0,"i":121,"b":null,"x":null,"Type":{"Tp":8,"Flag":128,"Flen":3,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"flag":0,"projectionOffset":-1}],"Not":false,"Sel":null},"R":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Op":7,"L":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"status","L":"status"}},"Refer":null},"R":{"text":"","k":1,"collation":0,"decimal":0,"length":0,"i":5,"b":null,"x":null,"Type":{"Tp":8,"Flag":128,"Flen":1,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"flag":0,"projectionOffset":-1}}},"Fields":{"text":"","Fields":[{"text":"CONCAT(id + 158084,';\"',edited_user,'\";\"\";\"',execute_time,'\";\"\";\"\";\"\";\"\";\"',apply_type,'\"')","Offset":8,"WildCard":null,"Expr":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":12,"FnName":{"O":"CONCAT","L":"concat"},"Args":[{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Op":11,"L":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"id","L":"id"}},"Refer":null},"R":{"text":"","k":1,"collation":0,"decimal":0,"length":0,"i":158084,"b":null,"x":null,"Type":{"Tp":8,"Flag":128,"Flen":6,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"flag":0,"projectionOffset":-1}},{"text":"","k":5,"collation":0,"decimal":0,"length":0,"i":0,"b":"OyI=","x":null,"Type":{"Tp":253,"Flag":0,"Flen":2,"Decimal":-1,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"flag":0,"projectionOffset":-1},{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"edited_user","L":"edited_user"}},"Refer":null},{"text":"","k":5,"collation":0,"decimal":0,"length":0,"i":0,"b":"IjsiIjsi","x":null,"Type":{"Tp":253,"Flag":0,"Flen":6,"Decimal":-1,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"flag":0,"projectionOffset":-1},{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"execute_time","L":"execute_time"}},"Refer":null},{"text":"","k":5,"collation":0,"decimal":0,"length":0,"i":0,"b":"IjsiIjsiIjsiIjsiIjsi","x":null,"Type":{"Tp":253,"Flag":0,"Flen":15,"Decimal":-1,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"flag":0,"projectionOffset":-1},{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"apply_type","L":"apply_type"}},"Refer":null},{"text":"","k":5,"collation":0,"decimal":0,"length":0,"i":0,"b":"Ig==","x":null,"Type":{"Tp":253,"Flag":0,"Flen":1,"Decimal":-1,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"flag":0,"projectionOffset":-1}]},"AsName":{"O":"","L":""},"Auxiliary":false}]},"GroupBy":null,"Having":null,"WindowSpecs":null,"OrderBy":null,"Limit":null,"LockTp":0,"TableHints":null,"IsAfterUnionDistinct":false,"IsInBraces":false,"QueryBlockOffset":0} |  None  |

**Comment by zhuxingtao** [comment]
> 检查一下你代码，以及是否有其他处理。下面是通过python的示例调用的结果：
> 
> id	statement	errlevel	query_tree	errmsg
> 1	use test_inc	0	{"text":"use test_inc","DBName":"test_inc"}	None
> 2	select CONCAT(id + 158084,';"',edited_user,'";"";"',execute_time,'";"";"";"";"";"',apply_type,'"')	0	{"text":"select CONCAT(id + 158084,';"',edited_user,'";"";"',execute_time,'";"";"";"";"";"',apply_type,'"')\nfrom erp.change_apply where apply_type in (101, 121) and status = 5","resultFields":null,"SQLBigResult":false,"SQLBufferResult":false,"SQLCache":true,"SQLSmallResult":false,"CalcFoundRows":false,"StraightJoin":false,"Priority":0,"Distinct":false,"From":{"text":"","TableRefs":{"text":"","resultFields":null,"Left":{"text":"","Source":{"text":"","resultFields":null,"Schema":{"O":"erp","L":"erp"},"Name":{"O":"change_apply","L":"change_apply"},"DBInfo":null,"TableInfo":null,"IndexHints":null,"PartitionNames":null},"AsName":{"O":"","L":""}},"Right":null,"Tp":0,"On":null,"Using":null,"NaturalJoin":false,"StraightJoin":false}},"Where":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Op":1,"L":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Expr":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"apply_type","L":"apply_type"}},"Refer":null},"List":[{"text":"","k":1,"collation":0,"decimal":0,"length":0,"i":101,"b":null,"x":null,"Type":{"Tp":8,"Flag":128,"Flen":3,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"flag":0,"projectionOffset":-1},{"text":"","k":1,"collation":0,"decimal":0,"length":0,"i":121,"b":null,"x":null,"Type":{"Tp":8,"Flag":128,"Flen":3,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"flag":0,"projectionOffset":-1}],"Not":false,"Sel":null},"R":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Op":7,"L":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"status","L":"status"}},"Refer":null},"R":{"text":"","k":1,"collation":0,"decimal":0,"length":0,"i":5,"b":null,"x":null,"Type":{"Tp":8,"Flag":128,"Flen":1,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"flag":0,"projectionOffset":-1}}},"Fields":{"text":"","Fields":[{"text":"CONCAT(id + 158084,';"',edited_user,'";"";"',execute_time,'";"";"";"";"";"',apply_type,'"')","Offset":8,"WildCard":null,"Expr":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":12,"FnName":{"O":"CONCAT","L":"concat"},"Args":[{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Op":11,"L":{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"id","L":"id"}},"Refer":null},"R":{"text":"","k":1,"collation":0,"decimal":0,"length":0,"i":158084,"b":null,"x":null,"Type":{"Tp":8,"Flag":128,"Flen":6,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"flag":0,"projectionOffset":-1}},{"text":"","k":5,"collation":0,"decimal":0,"length":0,"i":0,"b":"OyI=","x":null,"Type":{"Tp":253,"Flag":0,"Flen":2,"Decimal":-1,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"flag":0,"projectionOffset":-1},{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"edited_user","L":"edited_user"}},"Refer":null},{"text":"","k":5,"collation":0,"decimal":0,"length":0,"i":0,"b":"IjsiIjsi","x":null,"Type":{"Tp":253,"Flag":0,"Flen":6,"Decimal":-1,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"flag":0,"projectionOffset":-1},{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"execute_time","L":"execute_time"}},"Refer":null},{"text":"","k":5,"collation":0,"decimal":0,"length":0,"i":0,"b":"IjsiIjsiIjsiIjsiIjsi","x":null,"Type":{"Tp":253,"Flag":0,"Flen":15,"Decimal":-1,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"flag":0,"projectionOffset":-1},{"text":"","k":0,"collation":0,"decimal":0,"length":0,"i":0,"b":null,"x":null,"Type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"flag":8,"Name":{"text":"","Schema":{"O":"","L":""},"Table":{"O":"","L":""},"Name":{"O":"apply_type","L":"apply_type"}},"Refer":null},{"text":"","k":5,"collation":0,"decimal":0,"length":0,"i":0,"b":"Ig==","x":null,"Type":{"Tp":253,"Flag":0,"Flen":1,"Decimal":-1,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"flag":0,"projectionOffset":-1}]},"AsName":{"O":"","L":""},"Auxiliary":false}]},"GroupBy":null,"Having":null,"WindowSpecs":null,"OrderBy":null,"Limit":null,"LockTp":0,"TableHints":null,"IsAfterUnionDistinct":false,"IsInBraces":false,"QueryBlockOffset":0}	None

咦，github自动过滤了一些转义字符
原来的sql是如下所示
![image](https://user-images.githubusercontent.com/13105039/80299531-b994cd80-87c7-11ea-8040-80ab4d05367f.png)

**Comment by zhuxingtao** [comment]
> 支持的。经过测试是ok的。建议升级到最新版本试试看。

不OK啊 看我上面的

**Comment by zhuxingtao** [comment]
select path from table  where (id between 57853061 and 88854061)
这种 语句语法树也为空

**Comment by hanchuanchuan** [comment]
以下是sql `select path from table1 where (id between 57853061 and 88854061)` 返回的语法树.
请注意, 如果有语法错误时是无法返回解析语法的. 并且会返回相应的语法错误信息.这点是和旧版本inception有差异的(旧版本做的是自动忽略错误语法,但这样是有风险的).
```json
{
    "text":"select path from table1 where (id between 57853061 and 88854061)",
    "resultFields":null,
    "SQLBigResult":false,
    "SQLBufferResult":false,
    "SQLCache":true,
    "SQLSmallResult":false,
    "CalcFoundRows":false,
    "StraightJoin":false,
    "Priority":0,
    "Distinct":false,
    "From":{
        "text":"",
        "TableRefs":{
            "text":"",
            "resultFields":null,
            "Left":{
                "text":"",
                "Source":{
                    "text":"",
                    "resultFields":null,
                    "Schema":{
                        "O":"",
                        "L":""
                    },
                    "Name":{
                        "O":"table1",
                        "L":"table1"
                    },
                    "DBInfo":null,
                    "TableInfo":null,
                    "IndexHints":null,
                    "PartitionNames":null
                },
                "AsName":{
                    "O":"",
                    "L":""
                }
            },
            "Right":null,
            "Tp":0,
            "On":null,
            "Using":null,
            "NaturalJoin":false,
            "StraightJoin":false
        }
    },
    "Where":{
        "text":"",
        "k":0,
        "collation":0,
        "decimal":0,
        "length":0,
        "i":0,
        "b":null,
        "x":null,
        "Type":{
            "Tp":0,
            "Flag":0,
            "Flen":0,
            "Decimal":0,
            "Charset":"",
            "Collate":"",
            "Elems":null
        },
        "flag":8,
        "Expr":{
            "text":"id between 57853061 and 88854061",
            "k":0,
            "collation":0,
            "decimal":0,
            "length":0,
            "i":0,
            "b":null,
            "x":null,
            "Type":{
                "Tp":0,
                "Flag":0,
                "Flen":0,
                "Decimal":0,
                "Charset":"",
                "Collate":"",
                "Elems":null
            },
            "flag":8,
            "Expr":{
                "text":"",
                "k":0,
                "collation":0,
                "decimal":0,
                "length":0,
                "i":0,
                "b":null,
                "x":null,
                "Type":{
                    "Tp":0,
                    "Flag":0,
                    "Flen":0,
                    "Decimal":0,
                    "Charset":"",
                    "Collate":"",
                    "Elems":null
                },
                "flag":8,
                "Name":{
                    "text":"",
                    "Schema":{
                        "O":"",
                        "L":""
                    },
                    "Table":{
                        "O":"",
                        "L":""
                    },
                    "Name":{
                        "O":"id",
                        "L":"id"
                    }
                },
                "Refer":null
            },
            "Left":{
                "text":"",
                "k":1,
                "collation":0,
                "decimal":0,
                "length":0,
                "i":57853061,
                "b":null,
                "x":null,
                "Type":{
                    "Tp":8,
                    "Flag":128,
                    "Flen":8,
                    "Decimal":0,
                    "Charset":"binary",
                    "Collate":"binary",
                    "Elems":null
                },
                "flag":0,
                "projectionOffset":-1
            },
            "Right":{
                "text":"",
                "k":1,
                "collation":0,
                "decimal":0,
                "length":0,
                "i":88854061,
                "b":null,
                "x":null,
                "Type":{
                    "Tp":8,
                    "Flag":128,
                    "Flen":8,
                    "Decimal":0,
                    "Charset":"binary",
                    "Collate":"binary",
                    "Elems":null
                },
                "flag":0,
                "projectionOffset":-1
            },
            "Not":false
        }
    },
    "Fields":{
        "text":"",
        "Fields":[
            {
                "text":"path",
                "Offset":8,
                "WildCard":null,
                "Expr":{
                    "text":"",
                    "k":0,
                    "collation":0,
                    "decimal":0,
                    "length":0,
                    "i":0,
                    "b":null,
                    "x":null,
                    "Type":{
                        "Tp":0,
                        "Flag":0,
                        "Flen":0,
                        "Decimal":0,
                        "Charset":"",
                        "Collate":"",
                        "Elems":null
                    },
                    "flag":8,
                    "Name":{
                        "text":"",
                        "Schema":{
                            "O":"",
                            "L":""
                        },
                        "Table":{
                            "O":"",
                            "L":""
                        },
                        "Name":{
                            "O":"path",
                            "L":"path"
                        }
                    },
                    "Refer":null
                },
                "AsName":{
                    "O":"",
                    "L":""
                },
                "Auxiliary":false
            }
        ]
    },
    "GroupBy":null,
    "Having":null,
    "WindowSpecs":null,
    "OrderBy":null,
    "Limit":null,
    "LockTp":0,
    "TableHints":null,
    "IsAfterUnionDistinct":false,
    "IsInBraces":false,
    "QueryBlockOffset":0
}
```

**Comment by zhuxingtao** [comment]
update
  table  a
set
  a.category_id = IFNULL(
    (
      select
        category_id
      from
        table2
      where
        number = a.i_number
    ),
    0
  )

这个解析错误，报a.i_number不存在，但实际是存在的
