### ISSUE TITLE
 执行go build报错

### ISSUE THREAD

**Issue by eastdx** [hanchuanchuan/goInception#2]
# 构建二进制包
go build -o goInception tidb-server/main.go

go: downloading github.com/coreos/etcd v3.3.10+incompatible
go: downloading golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: downloading github.com/cznic/sortutil v0.0.0-20150617083342-4c7342852e65
go: downloading github.com/ngaut/sync2 v0.0.0-20141008032647-7a24ed77b2ef
go: downloading github.com/gorilla/mux v1.6.2
go: downloading github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/uber/jaeger-client-go v2.15.0+incompatible
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/pkg/errors v0.8.0
go: downloading github.com/juju/errors v0.0.0-20181118221551-089d3ea4e4d5
go: downloading github.com/klauspost/cpuid v0.0.0-20170728055534-ae7887de9fa5
go: downloading golang.org/x/text v0.3.0
go: downloading github.com/spf13/cast v1.3.0
go: downloading gopkg.in/yaml.v2 v2.2.2
go: verifying github.com/coreos/etcd@v3.3.10+incompatible: checksum mismatch
	downloaded: h1:jFneRYjIvLMLhDLCzuTuU4rSJUjRplcJQ7pD7MnhC04=
	go.sum:     h1:KjVWqrZ5U0wa3CxY2AxlH6/UcB+PK2td1DcsYhA+HRs=

没有生成build文件

**Comment by hanchuanchuan** [comment]
因为依赖包版本有更新，所以检查校验和时没有通过，可以移除go.sum文件 ```rm -f go.sum```

**Comment by hanchuanchuan** [comment]
报错的依赖已修复，无需再移除```go.sum```文件

**Comment by FrommyMind** [comment]
go version go1.15.2 linux/amd64 还有这个错误


[root@localhost goInception]# go build -o goInception tidb-server/main.go
go: downloading github.com/siddontang/go-log v0.0.0-20180807004314-8d05993dda07
go: downloading golang.org/x/net v0.0.0-20191209160850-c0dbc17a3553
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading github.com/pingcap/goleveldb v0.0.0-20171020122428-b9ff6c35079e
go: downloading github.com/pingcap/tipb v0.0.0-20190428032612-535e1abaa330
go: downloading github.com/pingcap/kvproto v0.0.0-20181206061346-54cf0a0dfe55
go: downloading github.com/golang/protobuf v1.3.1
go: downloading github.com/pingcap/pd v2.1.0+incompatible
go: downloading google.golang.org/grpc v1.16.0
go: downloading github.com/CorgiMan/json2 v0.0.0-20150213135156-e72957aba209
go: downloading github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
go: downloading github.com/hanchuanchuan/gh-ost v1.0.49-0.20200114083508-62a578b91654
go: downloading github.com/ngaut/pools v0.0.0-20180318154953-b7bc8c42aac7
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/pkg/errors v0.9.0
go: downloading github.com/klauspost/cpuid v0.0.0-20170728055534-ae7887de9fa5
go: downloading github.com/hanchuanchuan/go-mysql v0.0.0-20200114082439-6d0d8d3a982e
go: downloading github.com/imroc/req v0.2.3
go: downloading github.com/juju/errors v0.0.0-20181118221551-089d3ea4e4d5
go: downloading github.com/satori/go.uuid v1.2.0
go: downloading github.com/shopspring/decimal v0.0.0-20180709203117-cd690d0c9e24
go: downloading github.com/vitessio/vitess v3.0.0-rc.3+incompatible
go: downloading github.com/percona/go-mysql v0.0.0-20190307200310-f5cfaf6a5e55
go: downloading github.com/hanchuanchuan/gcfg.v1 v0.0.0-20190302111942-77c0f3dcc0b3
go: downloading github.com/pingcap/errors v0.11.0
go: downloading github.com/gofrs/uuid v3.2.0+incompatible
go: downloading github.com/opentracing/opentracing-go v1.1.0
go: downloading github.com/gorilla/mux v1.6.2
go: downloading gopkg.in/natefinch/lumberjack.v2 v2.0.0
go: downloading github.com/ngaut/sync2 v0.0.0-20141008032647-7a24ed77b2ef
go: downloading github.com/google/btree v0.0.0-20180813153112-4030bb1f1f0c
go: downloading github.com/hanchuanchuan/golib v0.0.0-20200113085747-47643bc243f1
go: downloading google.golang.org/genproto v0.0.0-20181004005441-af9cb2a35e7f
go: downloading github.com/prometheus/client_golang v0.9.0
go: downloading github.com/blacktear23/go-proxyprotocol v0.0.0-20171102103907-62e368e1c470
go: downloading github.com/go-sql-driver/mysql v1.4.1-0.20191022112324-6ea7374bc1b0
go: downloading github.com/coreos/etcd v3.3.10+incompatible
go: downloading github.com/spf13/viper v1.3.1
go: downloading github.com/spaolacci/murmur3 v0.0.0-20180118202830-f09979ecbc72
go: downloading github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: downloading github.com/prometheus/procfs v0.0.0-20181005140218-185b4288413d
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/spf13/jwalterweatherman v1.0.0
verifying github.com/coreos/etcd@v3.3.10+incompatible: checksum mismatch
        downloaded: h1:jFneRYjIvLMLhDLCzuTuU4rSJUjRplcJQ7pD7MnhC04=
        go.sum:     h1:KjVWqrZ5U0wa3CxY2AxlH6/UcB+PK2td1DcsYhA+HRs=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by hanchuanchuan** [comment]
移除`go.sum`文件后重试。

**Comment by G8bao7** [comment]
删除go.sum，多执行几次build，把返回的 go mod 结果都执行一遍，就正常了

**Comment by warlock-lv** [comment]
go build -o goInception tidb-server/main.go

**Comment by warlock-lv** [comment]
go build -o goInception tidb-server/main.go
如下
[lvjl@emr-header-1 goInception]$ go build -o goInception tidb-server/main.go
go: github.com/BurntSushi/toml@v0.3.1: Get "https://goproxy.baidu.com/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod": x509: certificate has expired or is not yet valid: current time 2022-06-20T16:36:21+08:00 is after 2021-12-09T23:59:59Z
[lvjl@emr-header-1 goInception]$ 

怎么办？
