### ISSUE TITLE
建议提供官方Docker镜像

### ISSUE THREAD

**Issue by hhyo** [hanchuanchuan/goInception#20]
看项目中已经包含了Dockerfile文件，可以考虑维护一个Docker镜像，https://hub.docker.com/

**Comment by hanchuanchuan** [comment]
感谢建议！
已经添加goinception的Docker镜像，可按如下方式获取
```
docker pull hanchuanchuan/goinception
```
地址：https://hub.docker.com/r/hanchuanchuan/goinception
