### ISSUE TITLE
mac执行报错

### ISSUE THREAD

**Issue by liuqian1990** [hanchuanchuan/goInception#200]
➜  ~ ./goInception
################################################
#     Warning: Unspecified config file!        #
################################################
2020/04/24 15:39:39.638 tidb.go:262: [info] new store
2020/04/24 15:39:39.683 terror.go:327: [fatal] file missing
github.com/pingcap/errors.AddStack
	/Users/hanchuanchuan/coding/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/errors.Trace
	/Users/hanchuanchuan/coding/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12
github.com/hanchuanchuan/goInception/store/mockstore/mocktikv.NewMVCCLevelDB
	/Users/hanchuanchuan/hcc/github.com/hanchuanchuan/goInception/store/mockstore/mocktikv/mvcc_leveldb.go:119
github.com/hanchuanchuan/goInception/store/mockstore/mocktikv.NewTiKVAndPDClient
	/Users/hanchuanchuan/hcc/github.com/hanchuanchuan/goInception/store/mockstore/mocktikv/mock.go:29
github.com/hanchuanchuan/goInception/store/mockstore.NewMockTikvStore
	/Users/hanchuanchuan/hcc/github.com/hanchuanchuan/goInception/store/mockstore/tikv.go:105
github.com/hanchuanchuan/goInception/store/mockstore.MockDriver.Open
	/Users/hanchuanchuan/hcc/github.com/hanchuanchuan/goInception/store/mockstore/tikv.go:46
github.com/hanchuanchuan/goInception/session.newStoreWithRetry.func1
	/Users/hanchuanchuan/hcc/github.com/hanchuanchuan/goInception/session/tidb.go:263
github.com/hanchuanchuan/goInception/util.RunWithRetry
	/Users/hanchuanchuan/hcc/github.com/hanchuanchuan/goInception/util/misc.go:39
github.com/hanchuanchuan/goInception/session.newStoreWithRetry
	/Users/hanchuanchuan/hcc/github.com/hanchuanchuan/goInception/session/tidb.go:261
github.com/hanchuanchuan/goInception/session.NewStore
	/Users/hanchuanchuan/hcc/github.com/hanchuanchuan/goInception/session/tidb.go:245
main.createStoreAndDomain
	/Users/hanchuanchuan/hcc/github.com/hanchuanchuan/goInception/tidb-server/main.go:158
main.main
	/Users/hanchuanchuan/hcc/github.com/hanchuanchuan/goInception/tidb-server/main.go:132
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357

**Comment by hanchuanchuan** [comment]
删除默认的 `/tmp/tidb` 文件夹后重试。或者在 `config.toml` 指定 `path` 到其他位置并重试。

**Comment by dongqianzheng** [comment]
我也遇到了这个问题，看来kill的方式关闭不安全呐。最好是有专门的关闭命令
