### ISSUE TITLE
加个Insert重复主键检测

### ISSUE THREAD

**Issue by liuqian1990** [hanchuanchuan/goInception#206]
插入时已有重复数据在表中或者插入列中有重复

**Comment by hanchuanchuan** [comment]
可以尝试着写个PR实现一下, 添加一个审核项, 实现对insert主键存在与否的查询校验.
ps: 另外唯一索引是否有考虑.

注意, 其可能存在的问题如下:
1. 性能问题. 每条insert会额外产生一次请求查询数据是否已存在.
2. 时效性问题. 在审核通过到执行的中间时间如果主键被使用,仍会出现该问题.

**Comment by liuqian1990** [comment]
好的，谢谢

**Comment by liuqian1990** [comment]
debug了在checkinsert没法拿到主键列名,要做这个修改有点大

**Comment by hanchuanchuan** [comment]
是的，这个功能相对来说比较麻烦，所以暂时未考虑添加。
