### ISSUE TITLE
mariabd生成回滚语句建议

### ISSUE THREAD

**Issue by 1393467261** [hanchuanchuan/goInception#208]
**描述您想要的功能：**
mariadb下降低事务交叉导致回滚语句出现移位的概率

**描述您考虑过的解决/替代方案：**
如果每执行一条DML，就立即解析binlog生成回滚语句，那么是否可以降低事务交叉的概率呢

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
现在的实现是这样的。每条DML前后会记录binlog位置的。

**Comment by 1393467261** [comment]
那开启事务(--trans)的话，是不是会提高事务交叉概率呢

**Comment by hanchuanchuan** [comment]
单从回滚的角度来说，开启事务是不利的，因为解析binlog的跨度变长了。
但事务批量提交本身是会减少执行时间的，两者各有利弊吧。

后续计划根据DML类型尽量减少其他会话的并发变更。另外不太建议在这个问题上花费过多的时间，一来回滚操作使用很少，二者回滚肯定是需要多方介入的（DBA，开发等）。

**Comment by 1393467261** [comment]
明白了，谢谢
