### ISSUE TITLE
我使用polardb也返回tidb不支持备份功能

### ISSUE THREAD

**Issue by zhuxingtao** [hanchuanchuan/goInception#209]
**描述**
我使用polardb也返回tidb不支持备份功能

我没有用tidb，用的是polardb，这样报错是不是不太正确?

**Comment by hanchuanchuan** [comment]
帮忙发一下 `show variables like 'version'` 看一下具体版本信息

**Comment by zhuxingtao** [comment]
8.0.16

**Comment by zhuxingtao** [comment]
同时执行失败了看不到是哪一条sql执行失败了

 [{"order_id":1,"stage":"CHECKED","error_level":2,"Errlevel":0,"stage_status":"Audit Completed","error_message":"TiDB暂不支持备份功能.","sql":"inception_magic_start","affected_rows":0,"sequence":"0_0_00000000","backup_dbname":"","execute_time":"0","sqlsha1":"","backup_time":"0","id":null,"statement":null}]

这是返回信息，这个能优化下吗？

**Comment by zhuxingtao** [comment]
[{"order_id":1,"stage":"CHECKED","error_level":2,"Errlevel":0,"stage_status":"Audit Completed","error_message":"TiDB暂不支持备份功能.","sql":"inception_magic_start","affected_rows":0,"sequence":"0_0_00000000","backup_dbname":"","execute_time":"0","sqlsha1":"","backup_time":"0","id":null,"statement":null}]

同时执行结果看不到是哪条sql执行失败了，这个能优化下吗

**Comment by zhuxingtao** [comment]
--backup=1;--ignore_warnings=1   
我在backup后面加上--ignore_warnings 后 会报这个tidb不支持备份功能， 不加好像就没问题

**Comment by hanchuanchuan** [comment]
问题还在版本判断上，返回的详细版本信息是`8.0.16`吗，需要根据这个结果判断数据库类型。

**Comment by zhuxingtao** [comment]
> 问题还在版本判断上，返回的详细版本信息是`8.0.16`吗，需要根据这个结果判断数据库类型。

对的

**Comment by zhuxingtao** [comment]
还有rds也出现了这种情况
