### ISSUE TITLE
提供语法树打印功能

### ISSUE THREAD

**Issue by hhyo** [hanchuanchuan/goInception#21]
是否可以提供类似于Inception的语法树打印功能

- 支持打印完整的语法树
- 支持直接获取SQL涉及的真实库、表名

**Comment by hanchuanchuan** [comment]
[语法树打印](https://hanchuanchuan.github.io/goInception/tree/)功能已添加，类似soar中的tiast-json格式。
后续会逐步裁剪和优化，欢迎Issue和PR
