### ISSUE TITLE
关键字建议兼容MySQL关键字

### ISSUE THREAD

**Issue by yangjiuyi** [hanchuanchuan/goInception#210]
TIDB关键字与MySQL关键字有差异，建议添加审核MySQL关键字

**Comment by hanchuanchuan** [comment]
方便的话可以提供一批关键字列表吗，关键字可以做一下扩展

**Comment by yangjiuyi** [comment]
https://dev.mysql.com/doc/refman/5.7/en/keywords.html MySQL关键字列表
https://pingcap.com/docs-cn/stable/reference/sql/language-structure/keywords-and-reserved-words/ TiDB关键字列表

**Comment by xiaohuazi123** [comment]
666

**Comment by hanchuanchuan** [comment]
该问题已经修复, 请下载最新版本1.2.3.
