### ISSUE TITLE
SetupSignalHandler方法参数错误

### ISSUE THREAD

**Issue by wins1978** [hanchuanchuan/goInception#211]
**描述**
Too many arguments in call to signal.SetupSignalHandler

**重现**
tidb-server/main.go中的signal.SetupSignalHandler(cfg.IgnoreSighup, serverShutdown)
和func SetupSignalHandler(shudownFunc func(bool)) {
参数不一致

**Comment by wins1978** [comment]
上面是master的错误，下面的是v1.2.2源码的错误
session\session_inception.go:945:3: s.mysqlComputeSqlSha1 undefined (type *session has no field or method mysqlComputeSqlSha1)
session\session_inception.go:2209:5: s.mysqlExecuteAlterTableGhost undefined (type *session has no field or method mysqlExecuteAlterTableGhost)
session\session_inception.go:2212:5: s.mysqlExecuteAlterTableOsc undefined (type *session has no field or method mysqlExecuteAlterTableOsc)
session\session_inception.go:3966:5: s.checkAlterUseOsc undefined (type *session has no field or method checkAlterUseOsc)

**Comment by hanchuanchuan** [comment]
请检查一下是源码本身的错误还是有做过什么调整。
所有的正式版本都是会触发详细的CI测试的(所有的commit操作都会触发)，有上述错误的话会直接报出来的。
