### ISSUE TITLE
pt-online-schema-change 中 rename 操作设置超时时间

### ISSUE THREAD

**Issue by jianhaiqing** [hanchuanchuan/goInception#214]
**描述您想要的功能：**
在pt-osc 中加上 两个选项如下， 目标是获取meta lock,或 innodb lock 超时，避免默认的60s 超时，造成影响范围过大
 `--set-vars lock_wait_timeout=3,innodb_lock_wait_timeout=1`

**描述您考虑过的解决/替代方案：**

`--set-vars lock_wait_timeout=3,innodb_lock_wait_timeout=1`

**可参考文档,资料,引用等：**
https://www.percona.com/doc/percona-toolkit/3.0/pt-online-schema-change.html

**Comment by hanchuanchuan** [comment]
感兴趣的话可以参考 #172 来添加一个pt-osc参数.

**Comment by jianhaiqing** [comment]
好的，老板，我明天来加，谢谢老板指导

**Comment by hhyo** [comment]
发现普通的ddl执行也可以考虑加一个这个配置，避免异常场景下受到某些未提交的事务影响

**Comment by jianhaiqing** [comment]
> 发现普通的ddl执行也可以考虑加一个这个配置，避免异常场景下受到某些未提交的事务影响

嗯，说的对，我看怎么加一下

**Comment by bruse-peng** [comment]
工具是自动集成了pt-online-schema-change在实行sql的时候使用pt-online-schema-change吗？
