### ISSUE TITLE
DRDS执行DDL可以DML不行

### ISSUE THREAD

**Issue by baokaijian** [hanchuanchuan/goInception#217]
**描述**
对阿里云DRDS执行同一个库下执行DDL可以正常执行完成，但是执行DML会提示“当前数据库为只读模式,无法执行!”

**环境**
 - 数据库: 阿里云DRDS
 - 版本: 1.2.1和1.2.2都测试了一样的问题

**Comment by hanchuanchuan** [comment]
发一下 `show variables like 'read_only';` 语句的执行结果看一下.
现在是根据该参数判断数据库是否为只读模式的.

**Comment by baokaijian** [comment]
Variable_name | Value
-- | --
read_only | OFF

**Comment by hanchuanchuan** [comment]
只读的判断没有问题.
DDL和DML是同样的执行逻辑, 检查一下goinception有什么错误日志没.
另外可以进一下项目首页的QQ讨论群发一下相关截图以便问题定位.

**Comment by baokaijian** [comment]
2020/05/20 10:17:15.396 server.go:318: [info] con:6 new connection 127.0.0.1:64696
2020/05/20 10:17:15.397 adapter.go:288: [debug] con:0 ActivePendingTxn select HIGH_PRIORITY * from mysql.global_variables where variable_name in ('autocommit', 'sql_mode', 'max_allowed_packet', 'time_zone', 'block_encryption_mode', 'tidb_skip_utf8_check', 'tidb_index_join_batch_size', 'tidb_index_lookup_size', 'tidb_index_lookup_concurrency', 'tidb_index_lookup_join_concurrency', 'tidb_index_serial_scan_concurrency', 'tidb_hash_join_concurrency', 'tidb_projection_concurrency', 'tidb_hashagg_partial_concurrency', 'tidb_hashagg_final_concurrency', 'tidb_backoff_lock_fast', 'tidb_constraint_check_in_place', 'tidb_ddl_reorg_worker_cnt', 'tidb_opt_insubquery_unfold', 'tidb_distsql_scan_concurrency', 'tidb_max_chunk_size', 'tidb_enable_cascades_planner', 'tidb_retry_limit', 'tidb_disable_txn_auto_retry')
2020/05/20 10:17:15.399 adapter.go:365: [debug] [QUERY] [INTERNAL] cost_time:1.317628ms request_count:2 succ:true con:0 user: txn_start_ts:416793502783111168 database: table_ids:[13],index_ids:[1],sql:select HIGH_PRIORITY * from mysql.global_variables where variable_name in ('autocommit', 'sql_mode', 'max_allowed_packet', 'time_zone', 'block_encryption_mode', 'tidb_skip_utf8_check', 'tidb_index_join_batch_size', 'tidb_index_lookup_size', 'tidb_index_lookup_concurrency', 'tidb_index_lookup_join_concurrency', 'tidb_index_serial_scan_concurrency', 'tidb_hash_join_concurrency', 'tidb_projection_concurrency', 'tidb_hashagg_partial_concurrency', 'tidb_hashagg_final_concurrency', 'tidb_backoff_lock_fast', 'tidb_constraint_check_in_place', 'tidb_ddl_reorg_worker_cnt', 'tidb_opt_insubquery_unfold', 'tidb_distsql_scan_concurrency', 'tidb_max_chunk_size', 'tidb_enable_cascades_planner', 'tidb_retry_limit', 'tidb_disable_txn_auto_retry')
2020/05/20 10:17:15.399 adapter.go:288: [debug] con:6 ActivePendingTxn set autocommit=0
2020/05/20 10:17:15.399 set.go:180: [debug] con:6 autocommit=0
2020/05/20 10:17:15.399 adapter.go:365: [debug] [QUERY] cost_time:100.353µs  succ:true con:6 user:root@127.0.0.1 txn_start_ts:416793502783635456 database: sql:set autocommit=0
2020/05/20 10:17:15.405 session_inception.go:2731: [debug] checkBinlogIsOn
2020/05/20 10:17:15.417 session_inception.go:2709: [debug] setSqlSafeUpdates
2020/05/20 10:17:15.417 session_inception.go:2438: [debug] mysqlServerVersion
2020/05/20 10:17:15.438 session_inception.go:2486: [debug] db version: 50726
2020/05/20 10:17:15.438 session_inception.go:2562: [debug] mysqlExplicitDefaultsForTimestamp
2020/05/20 10:17:15.453 session_inception.go:824: [debug] processCommand
2020/05/20 10:17:15.453 session_inception.go:6869: [debug] checkChangeDB
2020/05/20 10:17:15.455 session_inception.go:824: [debug] processCommand
2020/05/20 10:17:15.455 session_inception.go:5580: [debug] checkInsert
2020/05/20 10:17:15.484 session_inception.go:2758: [debug] checkIsReadOnly
2020/05/20 10:17:15.499 server.go:320: [info] con:6 close connection

**Comment by hanchuanchuan** [comment]
程序没有问题, 检查一下是不是连错服务器了, 或者找个测试数据库开启general_log看一下

**Comment by hanchuanchuan** [comment]
@baokaijian 原因确定了吗

**Comment by baokaijian** [comment]
还没解决，判断是drds做了读写流量分离，感觉是检测只读的sql落到了读实例，还在和阿里云沟通解决办法

**Comment by zwunix** [comment]
这个问题解决了吗？我测试也遇到了类似的问题。DDL可以执行和备份成功。但是DML可以执行但是不能备份。

**Comment by zwunix** [comment]
Backup: ERROR 1047 (HY000): [10ed88586212e000][XXX:3306][XXX]Unknown command.

**Comment by hanchuanchuan** [comment]
不是同一个问题，开新的issue吧
