### ISSUE TITLE
解析失败！可能是解析器bug，请联系作者

### ISSUE THREAD

**Issue by 1393467261** [hanchuanchuan/goInception#218]
**描述**
对问题简单清晰的描述
insert ... select ...语句报“解析失败”
**重现**
模拟重现的步骤
已有表结构
CREATE TABLE t1( id INT PRIMARY KEY, name VARCHAR(11) );
CREATE TABLE t2( id INT PRIMARY KEY, name VARCHAR(11) );
CREATE TABLE t3( id INT PRIMARY KEY, name VARCHAR(11) );
执行
insert into t1(name)( select a2.name from t2 point inner join t3 a3 on point.id = a3.id);
**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]
mariadb10.0.22、goInception1.2.2
**参数**
可能与问题相关的设置参数

**Comment by 1393467261** [comment]
debug下观察到s.ParseSQL返回的stmtNodes为空

**Comment by hanchuanchuan** [comment]
关联Issue #219 同样的问题.
