### ISSUE TITLE
point作为别名时审核报错

### ISSUE THREAD

**Issue by 1393467261** [hanchuanchuan/goInception#219]
**描述**
对问题简单清晰的描述
point作为别名时审核报错
**重现**
模拟重现的步骤
**select * from t1 point inner join t2 on point.id = t2.id;**
goInception1.2.2：**You have an error in your SQL syntax, near 'point inner join instance on point.id = instance.id' at line 1**
goInception1.1.1：**line 1 column 28 near " inner join instance on point.id = instance.id" (total length 74)**
**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]
mariadb10.0.22
**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
`point`是MySQL关键字，5.7版本的一种几何数据类型

**Comment by dba-ws** [comment]
> `point`是MySQL关键字，5.7版本的一种几何数据类型

您好，5.7的关键字goninception都会解析失败吗？或者有参数可以控制吗？

**Comment by hanchuanchuan** [comment]
该问题已关闭, 有疑问可提新的issue.
部分关键字会导致原有语法解析失败,需要添加反引号来引用.
建表阶段有关键字相关审核项来限制以避免使用关键字作为表名/列名.
