### ISSUE TITLE
影响行数审核不准

### ISSUE THREAD

**Issue by zhuxingtao** [hanchuanchuan/goInception#220]
**描述**
影响行数审核不准
**重现**
我的表有一千行，我 delete from 表名，按理说影响行数是1000，但结果审核出来的是800多行
**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**Comment by hanchuanchuan** [comment]
影响行数为预估行数, 数据来源于`explian`结果.
在`调用选项`有参数`real_row_count`获取真正的行数,但有性能影响(转换为`select count`)

**Comment by fancy-lee** [comment]
> 影响行数为预估行数, 数据来源于`explian`结果. 在`调用选项`有参数`real_row_count`获取真正的行数,但有性能影响(转换为`select count`)

请问这个real_row_count怎么设置？

**Comment by fancy-lee** [comment]
mysql> inception set real_row_count=true;
ERROR 1105 (HY000): 无效参数
