### ISSUE TITLE
DDL在前加列,后面做更新导致扫描行数不准

### ISSUE THREAD

**Issue by liuqian1990** [hanchuanchuan/goInception#221]
显示行数 200W行 `alter table tb_test99 
add column SPU_ID bigint(20) DEFAULT 0 COMMENT 'spuId' AFTER USER_ID,
add column CATEGORY_ID int(11) DEFAULT 100 COMMENT '类别' AFTER SPU_ID`

显示为0行 `update tb_test99 set SPU_ID=ALBUM_ID where SPU_ID=0 显示0行`

**Comment by liuqian1990** [comment]
执行结束后又是正常的

**Comment by hanchuanchuan** [comment]
这个并非是异常的. 说明一下操作流程:
`alter table`前会获取表的所有行数, 该表DDL操作的预估影响行数即是表总行数.
而DML语句会执行`explain`获取预估影响行数, 但该操作有一个大前提,即表结构是存在的(非新增表,新增字段等),不然无法执行`explain`

**Comment by liuqian1990** [comment]
这种能直接返回行数超标吗

**Comment by hanchuanchuan** [comment]
可以配置`max_ddl_affect_rows`参数, 该参数仅用于限制DDL操作的预估影响行数.
