### ISSUE TITLE
普通DDL执行改表时，也设置 lock_wait_timeout，以免meta lock 影响DML

### ISSUE THREAD

**Issue by jianhaiqing** [hanchuanchuan/goInception#223]
**描述您想要的功能：**
在小表改表过程中，都是直接改表，执行改表时，设置 lock_wait_timeout 避免改表过程中，因为未提交事务（或只读事务的时间过长），导致的锁表时间过长；

**描述您考虑过的解决/替代方案：**
执行改表时，MySQL建连配置上添加 lock_wait_timeout，为配置项

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
可以参考`sql_safe_updates`的实现方式, 需要注意默认值应为`-1`, 此时不做任何操作(即不改变上一版本的原有逻辑)

**Comment by hanchuanchuan** [comment]
在生产环境中该参数通常是本就设置的,该功能算是做个双保险吧

**Comment by hhyo** [comment]
https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_lock_wait_timeout

元数据锁默认超时时间比较长，由于场景限制也不方便全局设置，在执行会话中设置是比较好的方式

**Comment by jianhaiqing** [comment]
小圈圈，那就是说，最好的办法时在全局设置这个值 my.cnf: lock_wait_timeout=5
5秒是不是比较合理的？
默认是365天？

**Comment by hhyo** [comment]
先我一步，😁

**Comment by jianhaiqing** [comment]
承让承让
