### ISSUE TITLE
update 审核行数和更新行数不一致

### ISSUE THREAD

**Issue by skymoou** [hanchuanchuan/goInception#228]
**描述**
在做update 带where 条件更新的时候，会出现审核行数为全表总行数，但是实际更新行数只有几行

这种情况偶尔出现

**重现**
正常的更新操作

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.6.16-log]

**参数**
默认审核参数

**Comment by hanchuanchuan** [comment]
请注意, 审核时的影响行数为预估行数, 获取来源为`explain`的结果.
如果想获取真实行数请在调用时开启调用选项`--real_row_count=true;`

**Comment by skymoou** [comment]
好的，感谢
