### ISSUE TITLE
当隐式转换开启后使用in为SQL时，无法校验数据类型

### ISSUE THREAD

**Issue by apaul030515** [hanchuanchuan/goInception#229]
**描述**
当隐式转换开启后使用in为SQL时，无法校验数据类型，并且审核会通过，但当真正执行的时候会校验数据类型，并执行失败，是否为BUG，如果开启隐式转换，则sql使用=或者in时，在审核时就需要报错提示。

**重现**
CREATE TABLE `media_city ` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
city int null,
second_media_sn varchar(50),
PRIMARY KEY (`id`),
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

second_media_sn 是varchar类型,并且开启隐式转换为TRUE
use test;
UPDATE media_city SET  city = 0 WHERE second_media_sn =2314; 审核的时候会报隐世转换，
UPDATE media_city SET  city = 0 WHERE second_media_sn in (2314) 审核的时候不会报错，会审核通过 ，此为有问题，执行的时候会校验数据类型，并报错;

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.15]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
当前仅在等值表达式中添加了隐式转换的审核，其他表达式暂不支持。
