### ISSUE TITLE
同时执行pt-ddl + dml；无法生成dml回滚语句

### ISSUE THREAD

**Issue by 1393467261** [hanchuanchuan/goInception#230]
**描述**
对问题简单清晰的描述

同时执行pt-ddl + dml；无法生成dml回滚语句

**重现**
模拟重现的步骤
同时执行以下三条语句，其中alter走pt：
insert into t(c) values('v');
alter table t add column c2 varchar(10);
insert into t(c) values('v');
两条dml的binlog pos点正确，但第二条的回滚语句没有写入备份库
**环境**
mariadb 10.0.22

**参数**
可能与问题相关的设置参数

**Comment by 1393467261** [comment]
||       start_pos          ||           file                                    |            end_pos
||       579175440       ||          mariadb-bin.000018         ||           579175640
||       0                       ||                                                   ||           0
||       579179590       ||          mariadb-bin.000018         ||           579179792


1，以上是三条sql对应的backup info
2，没有开始批量提交

**Comment by 1393467261** [comment]
debug后发现，生成第一条dml回滚语句时的threadId为0，而生成第二条dml回滚语句时threadId不为0，checkFilter()返回false

**Comment by 1393467261** [comment]
原因：show master status得到的position是最近一个事件的endPos，go-mysql里的event.header.logPos也是代表事件的endPos；所以解析binlog时，需要不仅要忽略 curPos < startPos，还要忽略curPos == startPos的事件；否则最近的一个事件也会算入该事务中

**Comment by 1393467261** [comment]
另外[这行代码](https://github.com/hanchuanchuan/goInception/blob/b7343db5ecf702372f0f16f17ff5277a04bc0ff0/session/parser.go#L419)中，可不可以把条件"currentThreadID == 0"去掉，因为既然确定是mariadb了，就没必要关注currentThreadID了

**Comment by hanchuanchuan** [comment]
已修复.
相关PR #232
问题原因:
问题原因是MariaDB在v10版本的binlog移除了DML操作前的QueryEvent事件, 导致无法获取到DML操作的线程号connection_id,
而在DML的binlog范围内如果有其他事件产生的QueryEvent时,则会获取到错误的线程号.
