### ISSUE TITLE
不支持Json字段校验

### ISSUE THREAD

**Issue by aclstack** [hanchuanchuan/goInception#234]
**描述**
不支持对json字段的校验

**重现**
CREATE TABLE `test1` (
  `user` json DEFAULT NULL
);

检测（check）结果
Identifier 'user' is keyword in MySQL. Json type not allowed in column 'user'.

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.23]

**参数**
可能与问题相关的设置参数

**Comment by aclstack** [comment]
如果在库中 修改 enable_json_type  确实能够生效， 但是库重启后又变为false，所以想知道，配置文件如何设置才能让enable_json_type为true

**Comment by aclstack** [comment]
er_json_type_support 设置为2 重启后还是false

**Comment by aclstack** [comment]
er_json_type_support 设置为1 重启后也是false

**Comment by hanchuanchuan** [comment]
可以看看 使用文档>配置文件的说明 https://hanchuanchuan.github.io/goInception/config.html 
和MySQL是类似的, 分为内存级的修改和配置文件的修改.
