### ISSUE TITLE
columns_must_have_index 审核逻辑问题

### ISSUE THREAD

**Issue by nevfo** [hanchuanchuan/goInception#235]
**描述**
设置了 columns_must_have_index 之后, 如果审核语句同时存在其他问题, 不论是否存在该列索引, 都会显示 "The specified column: 'xxx' must have index"

**重现**
1. 开启 columns_must_have_index
2. 审核如下语句
 CREATE TABLE `test0615` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `status` varchar(128) NOT NULL DEFAULT '' COMMENT '操作原因',
  `ctime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `ix_mtime` (`mtime`)
) ENGINE=InnoDB  COMMENT='test' ;

**环境**
 - 数据库: [mariadb]
 - 版本: 10.1.22 - 10.3.18

**参数**
columns_must_have_index

**Comment by hanchuanchuan** [comment]
该问题未能复现，要不下载最新版试一下。
