### ISSUE TITLE
无法创建视图

### ISSUE THREAD

**Issue by wins1978** [hanchuanchuan/goInception#238]
**描述**
命令禁止! 无法创建视图'LIVER_ACCEPT_V'.

视图也无法支持吗？

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.1]

**Comment by hanchuanchuan** [comment]
暂不支持该功能

**Comment by hanchuanchuan** [comment]
已添加新参数 enable_use_view 以启用视图的支持.
可查看 #262
