### ISSUE TITLE
报invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by liuqian1990** [hanchuanchuan/goInception#239]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x120cc47]

goroutine 1268061 [running]:
github.com/hanchuanchuan/gh-ost/go/logic.(*Applier).ReadMigrationMinValues(0xc012297710, 0x0, 0x0, 0x0)
  /Users/hanchuanchuan/coding/go/pkg/mod/github.com/hanchuanchuan/gh-ost@v1.0.49-0.20200114083508-62a578b91654/go/logic/applier.go:360 +0x37
github.com/hanchuanchuan/gh-ost/go/logic.(*Applier).ReadMigrationRangeValues(0xc012297710, 0x0, 0x0)
  /Users/hanchuanchuan/coding/go/pkg/mod/github.com/hanchuanchuan/gh-ost@v1.0.49-0.20200114083508-62a578b91654/go/logic/applier.go:402 +0x3f
github.com/hanchuanchuan/gh-ost/go/logic.(*Migrator).FinalizeMigration(0xc00f2d60a0)
  /Users/hanchuanchuan/coding/go/pkg/mod/github.com/hanchuanchuan/gh-ost@v1.0.49-0.20200114083508-62a578b91654/go/logic/migrator.go:403 +0x283
created by github.com/hanchuanchuan/gh-ost/go/logic.(*Migrator).Migrate
  /Users/hanchuanchuan/coding/go/pkg/mod/github.com/hanchuanchuan/gh-ost@v1.0.49-0.20200114083508-62a578b91654/go/logic/migrator.go:368 +0x438

**Comment by hanchuanchuan** [comment]
请提供完整的模拟示例~
包括表结构，索引信息，执行的ALTER语句等

**Comment by liuqian1990** [comment]
出过一次错后面是好的

**Comment by andycluo** [comment]
untime error: invalid memory aime="2020/10/23 02:29:55.262" level=info msg="con:2 new connection 127.0.0.1:42644" file=server.go func=onConn line=318
time="2020/10/23 02:29:55.264" level=warning msg=inception_magic_start file=session_inception.go func=parseOptions line=1962
time="2020/10/23 02:29:55.264" level=error msg="lastCmd inception_magic_start, runtime error: invalid memory address or nil pointer dereference, goroutine 105 [running]:\ngithub.com/hanchua
nchuan/goInception/server.(*clientConn).Run.func1(0xc0005aa340, 0xc00089fdae)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/conn.go:420 +0x105\npanic(0x158a6c0, 0x2942c40)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc(0xc0005c0600, 0x1a4c000, 0xc0005b0a00, 0xc00003fb61, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/session/session_inception.go:281 +0x23c5\ngithub.com/hanchuanchuan/goInception/session.(*session).ExecuteInc(0xc0005c0600, 0x1a4c000, 0xc0005b0a00, 0xc00003fb61, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/session/session_inception.go:122 +0x1c8\ngithub.com/hanchuanchuan/goInception/server.(*TiDBContext).Execute(0xc0005b29c0, 0x1a4c000, 0xc0005b0a00, 0xc00003fb61, 0x15, 0x0, 0x0, 0x0, 0x1a, 0xc0005c4010)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/driver_tidb.go:259 +0x7c\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).handleQuery(0xc0005aa340, 0x1a4c000, 0xc0005b0a00, 0xc00003fb61, 0x15, 0x0, 0x0)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/conn.go:880 +0xae\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).dispatch(0xc0005aa340, 0xc00003fb61, 0x16, 0x16, 0x0, 0x0)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/conn.go:632 +0x6e7\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run(0xc0005aa340)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/conn.go:465 +0x161\ngithub.com/hanchuanchuan/goInception/server.(*Server).onConn(0xc0003a40e0, 0x1a5fd20, 0xc00000e240)\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/server.go:326 +0x21d\ncreated by github.com/hanchuanchuan/goInception/server.(*Server).Run\n\t/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/server/server.go:271 +0x3f8\n" file=conn.go func=func1 line=422time="2020/10/23 02:29:55.264" level=info msg="con:2 close connection" file=server.go func=func1 line=320
ddress or nil pointer dereference

**Comment by hanchuanchuan** [comment]
麻烦提供一下调用的命令吧(`inception_magic_start`前面的内容),应该是指定的格式不正确.
例如:
```sql
/*--user=root;--password=root;--host=127.0.0.1;--check=1;--port=3306;*/
inception_magic_start;
```

**Comment by andycluo** [comment]
mysql> /*--user=root;--password=123456;--host=192.168.244.1;--port=3306;*/
mysql> inception_magic_start;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1
Current database: mysql

ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by andycluo** [comment]
/*--user=root;--password=123456;--host=192.168.244.1;--port=3306;*/

**Comment by hanchuanchuan** [comment]
你是第一次使用吧, goinception和inception均不支持MySQL交互式请求这种方式的.
请使用支持MySQL驱动的编程语言调用, 在文档中有python和golang的两个示例.

**Comment by andycluo** [comment]
是的，只有编程语言才行是吧。好的，谢谢，我用编程试试看看。
