### ISSUE TITLE
polardb的日志格式与mysql有点不同，是否能够支持？

### ISSUE THREAD

**Issue by zwunix** [hanchuanchuan/goInception#240]
**描述您想要的功能：**
polardb的日志格式与mysql有点不同，是否能够支持？

**可参考文档,资料,引用等：**
https://help.aliyun.com/document_detail/161318.html?spm=a2c4g.11186623.6.661.66d41266DNJkY9

**Comment by hanchuanchuan** [comment]
如果和标准和MySQL事件不同，是无法支持备份的。

DML备份失败的原因可能是polardb修改了标准的复制协议，导致无法模拟从库。

**Comment by zwunix** [comment]
描述
通过DRDS访问PolarDB，DDL执行和备份正常，DML备份异常

错误提示
Backup: ERROR 1047 (HY000): [10ed958cd3fe7000][IP:3306][数据库名]Unknown command.

环境

数据库: [DRDS/POLARDB]
版本: [POLARDB MYSQL 8]
+----------------------------------+-----------------------+
| Variable_name | Value |
+----------------------------------+-----------------------+
| innodb_polar_restore_old_version | OFF |
| innodb_version | 8.0.13 |
| polardb_version | 8.0.1.1.4 |
| protocol_version | 10 |
| rds_audit_log_version | MYSQL_V2 |
| rds_version | 13 |
| slave_type_conversions | |
| tls_version | TLSv1,TLSv1.1,TLSv1.2 |
| version | 8.0.13 |
| version_comment | Source distribution |
| version_compile_machine | x86_64 |
| version_compile_os | Linux |
| version_compile_zlib | 1.2.11 |
+----------------------------------+-----------------------+

**Comment by hanchuanchuan** [comment]
通过 https://github.com/siddontang/go-mysql#example 首页的demo测试是否可以模拟`数据库slave`从库，
如果失败的话，则暂时无法支持PolarDB数据库。

**Comment by zwunix** [comment]
polardb主从单独测试ddl和dml是正常的。但是在polardb前加上drds，把polardb作为分库的数据库接入。通过drds连接访问库，ddl是正常的，可以执行和备份，dml则是可以执行，但是备份异常。
