### ISSUE TITLE
make parser编译卡住

### ISSUE THREAD

**Issue by niumanniu** [hanchuanchuan/goInception#241]
**描述**
执行make parser，一直卡在命令行

**重现**
执行 make parser

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

编译环境对网络有要求吗？是否需要能ping通github.com?目前我的环境可以ping通baidu

**Comment by hanchuanchuan** [comment]
部分包需要访问`gopkg.in`或`golang.org`等地址，请使用二进制包或自行查找解决方案。

**Comment by FrommyMind** [comment]
国内添加代理就可以了
https://goproxy.cn/
