### ISSUE TITLE
通过DRDS访问PolarDB，DDL执行和备份正常，DML备份异常

### ISSUE THREAD

**Issue by zwunix** [hanchuanchuan/goInception#242]
**描述**
通过DRDS访问PolarDB，DDL执行和备份正常，DML备份异常

**错误提示**
Backup: ERROR 1047 (HY000): [10ed958cd3fe7000][IP:3306][数据库名]Unknown command.

**环境**
 - 数据库: [DRDS/POLARDB]
 - 版本: [POLARDB MYSQL 8]

+----------------------------------+-----------------------+
| Variable_name                    | Value                 |
+----------------------------------+-----------------------+
| innodb_polar_restore_old_version | OFF                   |
| innodb_version                   | 8.0.13                |
| polardb_version                  | 8.0.1.1.4             |
| protocol_version                 | 10                    |
| rds_audit_log_version            | MYSQL_V2              |
| rds_version                      | 13                    |
| slave_type_conversions           |                       |
| tls_version                      | TLSv1,TLSv1.1,TLSv1.2 |
| version                          | 8.0.13                |
| version_comment                  | Source distribution   |
| version_compile_machine          | x86_64                |
| version_compile_os               | Linux                 |
| version_compile_zlib             | 1.2.11                |
+----------------------------------+-----------------------+

**Comment by hanchuanchuan** [comment]
duplicate #240
