### ISSUE TITLE
执行多个文件

### ISSUE THREAD

**Issue by wins1978** [hanchuanchuan/goInception#244]
**描述您想要的功能：**
数据库发布时，一般是有多个文件，比如
01_create_table.sql
02_init_data.sql
检查、执行时可以按照文件进行吗？

现在的情况是，如果分开校验，第一个文件:create table test,第二个文件insert into test ...
则会提示表不存在

**Comment by hanchuanchuan** [comment]
给出一些优化方案，但该需求不适宜针对goInception项目。

* 比如同时审核(一次性审核)，用时主要在goInception到数据库的连接上；
* 比如建表操作提前做，等审核并创建完成后再提insert工单；
* 再比如两个脚本都写一下建表语法`create table if not exists table_name`也应该可行的。

**Comment by wins1978** [comment]
我现在想到的办法是，程序后台合并为一个文件传递到goinception了，
因为这是一个平台项目，可能会有其他部门的DBA发布脚本，脚本是不通部门的开发提供的，很难约束别人会按照特定的规则来。
现在还有另外一种情况，脚本并不会特别规范，比如添加了-- 注释  /*注释*/ DELIMITER关键字、甚至PROCEDURE、VIEW等等。各种奇怪的mysql命令行支持的语法都无法通过

**Comment by hanchuanchuan** [comment]
审核的目的就是为了更加规范的
