### ISSUE TITLE
是否可以支持这样的语法  create TABLE t2  as  SELECT * from t1

### ISSUE THREAD

**Issue by qq290070744** [hanchuanchuan/goInception#246]
**描述您想要的功能：**
是否可以支持这样的语法

` create TABLE t2  as  SELECT * from t1`

执行这条语句保错     ”表至少需要有一个列. 不支持的语法类型.“

这条语句在MySQL命令行可以执行成功

**Comment by hanchuanchuan** [comment]
暂不支持的。

该语法会同时建表和写入数据，但表结构不容易确定，所以近期无计划支持。

**Comment by hanchuanchuan** [comment]
已添加CREATE TABLE AS SELECT语法支持.

[Releases](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.3) (选择`v1.2.3-29`或以上版本)

功能说明:
会审核mysql参数enforce_gtid_consistency和gtid_mode参数.
(MySQL的GTID一致性验证可能会报错: Statement violates GTID consistency: CREATE TABLE ... SELECT.)
