### ISSUE TITLE
上万条的delete语句直接把goinception后台搞挂了

### ISSUE THREAD

**Issue by ljerom-github** [hanchuanchuan/goInception#252]
执行几万条的delete语句，最后的时候报错了，发现是goinception后台挂了，goinception日志打印：level=fatal msg="parse rows event panic runtime error: slice bounds out of range。  语句其实已经正常执行完了，回滚语句生成失败。 状态栏显示“goInception Error: (2013, 'Lost connection to MySQL server during query')”以及“异常终止”。

**Comment by hanchuanchuan** [comment]
发一下详细的goinception错误日志吧, 该问题出现在生成回滚语句的binlog解析部分.

**Comment by liuqian1990** [comment]
我也遇到这样的问题了

**Comment by ljerom-github** [comment]
> 发一下详细的goinception错误日志吧, 该问题出现在生成回滚语句的binlog解析部分.

这个是详细日志：
time="2020/08/05 14:12:51.205" level=info msg="con:103 new connection 10.****:51408" file=server.go func=onConn line=318
time="2020/08/05 14:13:12.199" level=info msg="con:104 new connection 10.****:51512" file=server.go func=onConn line=318
time="2020/08/05 14:13:13.503" level=info msg="create BinlogSyncer with config {2000111215 mariadb 10.**** 3306 archery    false false <nil> false UTC true 0 0s 0s 0 false false 0}" file=binlogsyncer.go func=NewBinlogSyncer line=144
time="2020/08/05 14:13:13.503" level=info msg="begin to sync binlog from position (binlog.035144, 26578219)" file=binlogsyncer.go func=StartSync line=359
time="2020/08/05 14:13:13.798" level=info msg="rotate to (binlog.035144, 26578219)" file=binlogsyncer.go func=parseEvent line=776
time="2020/08/05 14:13:14.018" level=info msg="syncer is closing..." file=binlogsyncer.go func=close line=175
time="2020/08/05 14:13:14.135" level=info msg="kill last connection id 196950281" file=binlogsyncer.go func=killConnection line=849
time="2020/08/05 14:13:14.135" level=info msg="syncer is closed" file=binlogsyncer.go func=close line=202
time="2020/08/05 14:13:14.142" level=info msg="con:104 close connection" file=server.go func=func1 line=320
time="2020/08/05 14:14:00.339" level=info msg="con:105 new connection 10.****:51626" file=server.go func=onConn line=318
time="2020/08/05 14:14:24.141" level=info msg="con:106 new connection 10.****:51734" file=server.go func=onConn line=318
time="2020/08/05 14:15:25.857" level=info msg="create BinlogSyncer with config {2000111214 mariadb 10.**** 3306 archery    false false <nil> false UTC true 0 0s 0s 0 false false 0}" file=binlogsyncer.go func=NewBinlogSyncer line=144
time="2020/08/05 14:15:25.858" level=info msg="begin to sync binlog from position (binlog.035144, 31707984)" file=binlogsyncer.go func=StartSync line=359
time="2020/08/05 14:15:26.074" level=info msg="rotate to (binlog.035144, 31707984)" file=binlogsyncer.go func=parseEvent line=776
time="2020/08/05 14:15:36.808" level=fatal msg="parse rows event panic runtime error: slice bounds out of range, data \"q\\xe9\\x1b\\x00\\x00\\x00\\x01\\x00\\n\\xff\\xff`\\xfc=\\x8a\\x00\\x00\\x1e\\x00106.121.128.64, 182.254.220.28_*NP\\x00\\x00\\x1coL2Z_wdsby6nf-wbX-kvKHF-p7Ms CDB9C02EA60505C3E252FA23362B92E1@D5B389B83DAEAC9D895965CC6D7EE30EC6105D1FB277BF8D5C37FD2177730E7F4\\x00http://wechat.xb.sinosig.com/port/policy/queryNew.do\\f保单查询\", parsed rows &replication.RowsEvent{Version:1, tableIDSize:6, tables:map[uint64]*replication.TableMapEvent{0x1be971:(*replication.TableMapEvent)(0xc0326fbcc0)}, needBitmap2:false, Table:(*replication.TableMapEvent)(0xc0326fbcc0), TableID:0x1be971, Flags:0x1, ExtraData:[]uint8(nil), ColumnCount:0xa, ColumnBitmap1:[]uint8{0xff, 0xff}, ColumnBitmap2:[]uint8(nil), Rows:[][]interface {}{}, parseTime:false, timestampStringLocation:(*time.Location)(nil), useDecimal:true, ignoreJSONDecodeErr:false}, table map &replication.TableMapEvent{tableIDSize:6, TableID:0x1be971, Flags:0x1, Schema:[]uint8{0x67, 0x77, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74}, Table:[]uint8{0x77, 0x78, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x6c, 0x6f, 0x67}, ColumnCount:0xa, ColumnType:[]uint8{0x3, 0xf, 0x7, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf}, ColumnMeta:[]uint16{0x0, 0x186, 0x0, 0x60, 0x60, 0xf0, 0xf, 0xf0, 0xc00, 0xb4}, NullBitmap:[]uint8{0xf8, 0x3}}\ngoroutine 32076 [running]:\ngithub.com/hanchuanchuan/go-mysql/mysql.Pstack(...)\n\t/root/go/pkg/mod/github.com/hanchuanchuan/go-mysql@v0.0.0-20200114082439-6d0d8d3a982e/mysql/util.go:20\ngithub.com/hanchuanchuan/go-mysql/replication.(*RowsEvent).Decode.func1(0xc0327130f4, 0xf9, 0x10c, 0xc0327d2000)\n\t/root/go/pkg/mod/github.com/hanchuanchuan/go-mysql@v0.0.0-20200114082439-6d0d8d3a982e/replication/row_event.go:283 +0xb6\npanic(0x15f8cc0, 0x2b4dde0)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/hanchuanchuan/go-mysql/replication.decodeString(0xc032713148, 0xa5, 0xb8, 0xc00, 0xc03271312c, 0x1c, 0x1d)\n\t/root/go/pkg/mod/github.com/hanchuanchuan/go-mysql@v0.0.0-20200114082439-6d0d8d3a982e/replication/row_event.go:550 +0x13b\ngithub.com/hanchuanchuan/go-mysql/replication.(*RowsEvent).decodeValue(0xc0327d2000, 0xc032713148, 0xa5, 0xb8, 0xc00c00710f, 0x1572820, 0xc032747420, 0x1d, 0x0, 0x0)\n\t/root/go/pkg/mod/github.com/hanchuanchuan/go-mysql@v0.0.0-20200114082439-6d0d8d3a982e/replication/row_event.go:519 +0xb31\ng" file=row_event.go func=func1 line=283

**Comment by hanchuanchuan** [comment]
mariadb数据库对吗. bug原因是引用的三方库 [go-mysql](https://github.com/siddontang/go-mysql) 在解析binlog时出错了.
可能的原因可能是对字符串处理时未判断极端情况导致了索引下标溢出.

详细的原因和修复方案还要测试确认, 需要你们帮忙提供一下信息哈:
1. 数据库版本
2. 完整表结构
3. 执行的SQL语句(如果能定位到出错的SQL更好)
4. 如果有可用于重现的原始数据就更方便了.

**Comment by ljerom-github** [comment]
> mariadb数据库对吗. bug原因是引用的三方库 [go-mysql](https://github.com/siddontang/go-mysql) 在解析binlog时出错了.
> 可能的原因可能是对字符串处理时未判断极端情况导致了索引下标溢出.
> 
> 详细的原因和修复方案还要测试确认, 需要你们帮忙提供一下信息哈:
> 
> 1. 数据库版本
> 2. 完整表结构
> 3. 执行的SQL语句(如果能定位到出错的SQL更好)
> 4. 如果有可用于重现的原始数据就更方便了.

1. 数据库版本：基于MariaDB 10.0.10设计(兼容Mysql 5.5)
2. 表结构
CREATE TABLE `ab_direct_media_file` (
`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`apply_id` varchar(100) DEFAULT NULL COMMENT '申请号',
`business_no` varchar(50) DEFAULT NULL COMMENT '流水号',
`plan_id` int(11) DEFAULT NULL COMMENT '产品id',
`file_name` varchar(64) DEFAULT NULL COMMENT '文件名',
`file_type` varchar(10) DEFAULT NULL COMMENT '文件类型',
`file_url` varchar(200) DEFAULT NULL COMMENT '文件路径',
`down_flag` varchar(1) DEFAULT NULL COMMENT '文件下载状态',
`upload_flag` varchar(1) DEFAULT NULL COMMENT '文件上传状态',
`upload_time` datetime DEFAULT NULL COMMENT '上传时间',
`notified_time` datetime DEFAULT NULL COMMENT '通知时间',
`is_valid` varchar(1) DEFAULT NULL COMMENT '是否有效',
`create_oper` varchar(20) DEFAULT NULL COMMENT '创建人',
`create_time` datetime DEFAULT NULL COMMENT '创建时间',
`modify_oper` varchar(20) DEFAULT NULL COMMENT '修改人',
`modify_time` datetime DEFAULT NULL COMMENT '修改时间',
PRIMARY KEY (`id`),
KEY `mediaFile_applyID_idx` (`apply_id`) USING BTREE,
KEY `mediaFile_busiNO_idx` (`business_no`) USING BTREE,
KEY `mediaFile_planId_idx` (`plan_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 98540 DEFAULT CHARSET = utf8 COMMENT = '媒体表';
3. 执行的语句（后面我重现了错误，相同的表，相同的语句，手动重现了同样的错误）
DELETE FROM ab_direct_media_file WHERE apply_id = '01032020052900000015' and file_type = '11' AND is_valid = '1';
4. 原始数据(批量插入几千条即可)
INSERT INTO `ab_direct_media_file` VALUES (67, '01032020052900000015', 'HBHPH001202001230004', 4446, 'DFHPH001202001290032_11_1.pdf', '11', '/fdnfsflafffrf/ffac/DLFPF001202005210222_11_1.pdf', '1', '0', '2020-5-30 00:03:05', NULL, '1', '1', '2020-5-30 00:03:05', '1', '2020-6-1 11:52:00');

*另外补充一点，报错后查看流程详细信息，sql没有像正常的完成的流程分成一条一条的区分开，点开+号就是全部的sql。
goinception打印的错误日志好像相关表的数据没啥关联呢，是解析binlog日志的时候串了嘛？

**Comment by hanchuanchuan** [comment]
该问题未能重现. 可能和数据本身有关. 以下是测试步骤, 分别在MariaDB和MySQL做了测试.

数据库版本
 - MariaDB 10.4.10
 - MySQL 5.7.26

测试步骤如下:

**构建测试数据**
```sql
-- 1. create table ab_direct_media_file ...

-- 2. insert values

-- 3. 重复写入大批量数据(100w以上)
INSERT INTO ab_direct_media_file(apply_id,business_no,plan_id,file_name,file_type,file_url,down_flag,upload_flag,upload_time,notified_time,is_valid,create_oper,create_time,modify_oper,modify_time)
select apply_id,business_no,plan_id,file_name,file_type,file_url,down_flag,upload_flag,upload_time,notified_time,is_valid,create_oper,create_time,modify_oper,modify_time from ab_direct_media_file;

```

**执行删除测试**

  - 方法一: 

```py
delete_range = []
start_id = 0
for i in range(1, 200001):
    delete_range.append(
        "DELETE FROM ab_direct_media_file WHERE `id`=%s;" % (i+start_id))
sql = '''/*--user=test;--password=test;--host=127.0.0.1;--port=3333;--execute=1;--backup=1;ignore-warnings=1;*/
inception_magic_start;
use test_inc;
%s
inception_magic_commit;''' % ("\n".join(delete_range))
```
  - 方法二:
```py
sql = '''/*--user=test;--password=test;--host=127.0.0.1;--port=3333;--execute=1;--backup=1;--ignore-warnings=1;*/
inception_magic_start;
use test_inc;

DELETE FROM ab_direct_media_file WHERE `id` < 1300000;

inception_magic_commit;'''
```

执行SQL
```py
import pymysql

# 此处替换为上述方法的SQL

conn = pymysql.connect(host='127.0.0.1', user='', passwd='',
                       db='', port=4000, charset="utf8",
                       cursorclass=pymysql.cursors.DictCursor)
cur = conn.cursor()
ret = cur.execute(sql)
result = cur.fetchall()
cur.close()
conn.close()

if len(result) > 100:
    result = result[len(result) - 100:]

print(result)
 
```

**Comment by ljerom-github** [comment]
> 该问题未能重现. 可能和数据本身有关. 以下是测试步骤, 分别在MariaDB和MySQL做了测试.
> 
> 数据库版本
> 
> * MariaDB 10.4.10
> * MySQL 5.7.26
> 
> 测试步骤如下:
> 
> **构建测试数据**
> 
> ```sql
> -- 1. create table ab_direct_media_file ...
> 
> -- 2. insert values
> 
> -- 3. 重复写入大批量数据(100w以上)
> INSERT INTO ab_direct_media_file(apply_id,business_no,plan_id,file_name,file_type,file_url,down_flag,upload_flag,upload_time,notified_time,is_valid,create_oper,create_time,modify_oper,modify_time)
> select apply_id,business_no,plan_id,file_name,file_type,file_url,down_flag,upload_flag,upload_time,notified_time,is_valid,create_oper,create_time,modify_oper,modify_time from ab_direct_media_file;
> ```
> 
> **执行删除测试**
> 
> * 方法一:
> 
> ```python
> delete_range = []
> start_id = 0
> for i in range(1, 200001):
>     delete_range.append(
>         "DELETE FROM ab_direct_media_file WHERE `id`=%s;" % (i+start_id))
> sql = '''/*--user=test;--password=test;--host=127.0.0.1;--port=3333;--execute=1;--backup=1;ignore-warnings=1;*/
> inception_magic_start;
> use test_inc;
> %s
> inception_magic_commit;''' % ("\n".join(delete_range))
> ```
> 
> * 方法二:
> 
> ```python
> sql = '''/*--user=test;--password=test;--host=127.0.0.1;--port=3333;--execute=1;--backup=1;--ignore-warnings=1;*/
> inception_magic_start;
> use test_inc;
> 
> DELETE FROM ab_direct_media_file WHERE `id` < 1300000;
> 
> inception_magic_commit;'''
> ```
> 
> 执行SQL
> 
> ```python
> import pymysql
> 
> # 此处替换为上述方法的SQL
> 
> conn = pymysql.connect(host='127.0.0.1', user='', passwd='',
>                        db='', port=4000, charset="utf8",
>                        cursorclass=pymysql.cursors.DictCursor)
> cur = conn.cursor()
> ret = cur.execute(sql)
> result = cur.fetchall()
> cur.close()
> conn.close()
> 
> if len(result) > 100:
>     result = result[len(result) - 100:]
> 
> print(result)
>  
> ```

我也看不出来数据有啥异常的，刚又去确认了下，看起来每行数据都差不多的。 然后我使用主键删除跑了一遍，不会出现异常了。以后我让开发统一使用主键去操作数据吧。

**Comment by hanchuanchuan** [comment]
倒是和用主键或者其他条件删除没有关系, binlog解析的是已变更/删除的数据日志.

有可能是数据本身的问题, 数据特殊字符/乱码之类的?

已测试utf8mb4表情,特殊符号&数学符号等, 均无问题.
(其中utf8mb4类型会报Incorrect string value,因为表为utf8类型的)

**Comment by hanchuanchuan** [comment]
更新了版本 [goInception-linux-amd64-v1.2.3-17-g629ac3a.tar.gz](https://github.com/hanchuanchuan/goInception/releases/download/v1.2.3/goInception-linux-amd64-v1.2.3-17-g629ac3a.tar.gz)
更新内容是解析binlog时添加了recover处理,看能否捕获和记录错误信息.
需要你帮忙在可重现的环境试试看哈.

**Comment by ljerom-github** [comment]
> 更新了版本 [goInception-linux-amd64-v1.2.3-17-g629ac3a.tar.gz](https://github.com/hanchuanchuan/goInception/releases/download/v1.2.3/goInception-linux-amd64-v1.2.3-17-g629ac3a.tar.gz)
> 更新内容是解析binlog时添加了recover处理,看能否捕获和记录错误信息.
> 需要你帮忙在可重现的环境试试看哈.

升级到v1.2.3-17版本后，用之前完全相同的数据和脚本去测试，现在可以正常执行了，没有报错。 
测试数据之前我试过两次，都能重现错误。

**Comment by hanchuanchuan** [comment]
在goInception的日志中没有error吗, 更新只添加了异常捕获, 无其他变更内容的. 
之前出错的版本号是多少, 我想对比一下差异内容.

**Comment by ljerom-github** [comment]
> 在goInception的日志中没有error吗, 更新只添加了异常捕获, 无其他变更内容的.
> 之前出错的版本号是多少, 我想对比一下差异内容.

工单能正常执行完成了的，没有error； 之前的版本我是在修改了这个bug后编译安装的：
go.mod
fix: 修复MariaDB可能出现dml未备份成功的问题
2 months ago

**Comment by hanchuanchuan** [comment]
好的, 这两个版本之间没有针对MariaDB的变更内容.
现在已经添加了异常捕获, 再次遇到时会保存错误信息的, 所以该问题暂时标记为已解决啦.
