### ISSUE TITLE
多版本数据库同时支持

### ISSUE THREAD

**Issue by aclstack** [hanchuanchuan/goInception#253]
**描述您想要的功能：**
由于历史遗留问题，还有一些5.1的  MySQL没有升级，但在审核过程中，如果default_charset设置为utf8mb4 (也就是默认值)，此时5.1版本库将无法使用

**描述您考虑过的解决/替代方案：**
尝试为特定数据库指定字符集，而不是全局设置

**可参考文档,资料,引用等：**
暂无。

**Comment by hanchuanchuan** [comment]
可以启动两套审核服务,指定不同端口.
