### ISSUE TITLE
modifyBinlogFormatRow 修改aws mysql数据库时出现错误

### ISSUE THREAD

**Issue by lework** [hanchuanchuan/goInception#254]
**描述**

当在aws mysql数据库上执行dml语句并备份数据时，出现：
```
time="2020/08/04 10:45:54.703" level=error msg="con:3 Error 1227: Access denied; you need (at least one of) the SUPER privilege(s) for this operation" file=conn.go line=101
time="2020/08/04 10:45:54.704" level=error msg="con:3 Error 1227: Access denied; you need (at least one of) the SUPER privilege(s) for this operation" file=session_inception.go line=2258
```
相关代码：
https://github.com/hanchuanchuan/goInception/blob/6896aa45220fea92e511f7e08b496bc70692e9dc/session/session_inception.go#L1819-L1832

**重现**
执行dml语句并备份数据

**环境**
 - 云平台：aws
 - 数据库: [mysql]
 - 版本: [5.7.26]

**参数**

binlog_format MIXED

**Comment by hanchuanchuan** [comment]
需要设置 `binlog_format = row`, 如果指定为` MIXED `的话, 语句级binlog无法生成回滚语句的.

**Comment by woshihaoren** [comment]
@hanchuanchuan 假如binlog_format = MIXED，有什么办法能接着用吗?回滚语句不要了，可以执行完sql。

**Comment by hanchuanchuan** [comment]
@woshihaoren 关闭备份功能即可。
