### ISSUE TITLE
存储过程等语句的支持

### ISSUE THREAD

**Issue by zouzhicun** [hanchuanchuan/goInception#256]
**描述您想要的功能：**
有部分语句未支持，比如存储过程的创建，set语句等

**描述您考虑过的解决/替代方案：**
未支持审核的语句建议增加一个开关，选择可否跳过审核，直接传给后端数据库运行。

**Comment by hanchuanchuan** [comment]
这部分很难支持. 主要困难在于语法解析器不支持(基于TiDB语法解析器)

**Comment by zouzhicun** [comment]
是否可以选择将未支持的语句跳过审核阶段，直接传给后端数据库？

**Comment by qq290070744** [comment]
直接传给后端数据库 ，那还调用 goInception 干什么

**Comment by zouzhicun** [comment]
比如更新一个sql文件，其中存在部分未支持的语句

**Comment by waitspring** [comment]
@hanchuanchuan @LeoQuote
