### ISSUE TITLE
能否支持一些alter ddl操作不需调用osc的禁止调用

### ISSUE THREAD

**Issue by zwunix** [hanchuanchuan/goInception#258]
**描述您想要的功能：**
在osc默认开启的情况下，能否增加支持一些alter ddl操作不需调用osc的禁止调用。比如alter字符集，alter drop index等。

**Comment by hanchuanchuan** [comment]
我测试了一下, 只有以下几种写法是完全不会锁表的.
```sql
ALTER TABLE tbl_name CHARACTER SET = charset_name;
ALTER TABLE tbl_name COLLATE = 'utf8_bin';
ALTER TABLE tbl_name COMMENT = '...';
```
接下来这几种操作如果是单个操作的话会跳过调用OSC, 并计划添加一个自定义选项来设置想要跳过的alter table子句.

**Comment by zwunix** [comment]
赞

**Comment by hanchuanchuan** [comment]
已添加参数`ignore_osc_alter_stmt`, 可配置强制忽略osc的Alter子句, 直接执行.

[Releases](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.3) (选择`v1.2.3-26`或以上版本)



格式为drop index,add column等,配置要跳过的子句格式,多个时以逗号分隔

例 `ignore_osc_alter_stmt = 'add index,drop index'`

以下格式的语法已自动跳过osc:
```sql
ALTER TABLE tbl_name CHARACTER SET = charset_name;
ALTER TABLE tbl_name COLLATE = 'utf8_bin';
ALTER TABLE tbl_name COMMENT = '...';
```

**Comment by zwunix** [comment]
很赞

发自我的iPhone
