### ISSUE TITLE
8.0和日志

### ISSUE THREAD

**Issue by 402309718** [hanchuanchuan/goInception#261]
是否支持8.0吗，最近在测试archery(容器版),但是goinception日志无法打印改成debug和text，执行DDL不确定是否真正经过处理转换成gh-ost或者OSC方式处理，是否还是会判断表的记录数确认是否会走gh-ost或者OSC，不是必然走配置GH-OST或osc转化

**Comment by hanchuanchuan** [comment]
请查阅goinception说明和配置文档
