### ISSUE TITLE
goInception 不支持 select 语句中包含子查询

### ISSUE THREAD

**Issue by sheenzxx** [hanchuanchuan/goInception#266]
在select 语句中出现的只查询。不能识别from 列表的 的字段。

CREATE TABLE temp_test1(id INT,NAME VARCHAR(30));
CREATE TABLE temp_test2(id INT ,salesid INT ,title VARCHAR(100));

INSERT INTO temp_test1 VALUES (1,'helo'),(2,'bilgo'),(3,'dolot');
INSERT INTO temp_test2 VALUES (1,1,'月光光'),(2,2,'品牌效应'),(3,3,'李白醉酒');

SELECT a.id,a.title,(SELECT b.name FROM temp_test1 b WHERE b.id = a.salesid) AS salesname
  FROM temp_test2 a

![image](https://user-images.githubusercontent.com/3350015/92679962-69746d00-f35c-11ea-8527-e4a2e4d4bf81.png)

在 (SELECT b.name FROM temp_test1 b WHERE b.id = a.salesid)  子句中。识别不了a.salesid
**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.6.3]

**Comment by hanchuanchuan** [comment]
该问题已修复.
[Releases](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.3) (选择`v1.2.3-32`或以上版本)

**Comment by sheenzxx** [comment]
谢谢@hanchuanchuan
