### ISSUE TITLE
goinception配置参数不生效

### ISSUE THREAD

**Issue by iCloudFly** [hanchuanchuan/goInception#268]
**描述**
goinception配置参数文件中修改参数不生效。

**重现**
比如参数：enable_json_type 
1：在config.toml文件中把enable_json_type = false 改为 enable_json_type = true:
2：然后重启服务，不生效。
3：登录goinception后查看inception show variables查看enable_json_type = false。
4：通过set 修改enable_json_type = true， 建个表带json的字段是有效的。
5：然后重启服务，再登录查看inception show variable，参数enable_json_type又变为false了。
6：建个表带json的字段的又审核不通过了。

**环境**
 - 数据库: [mysql]
 - 版本: [8.0.16]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
审核选项的开关配置在`[inc]`段.参考文档再试一下.
[config.toml说明](https://hanchuanchuan.github.io/goInception/config.html)
另外, goinception的参数和是mysql类似的, 所以会出现配置内存参数在重启后失效的问题.
