### ISSUE TITLE
我们需要在tidb支持auto_random

### ISSUE THREAD

**Issue by fengyubiao** [hanchuanchuan/goInception#269]
**描述您想要的功能：**
我们需要在tidb支持auto_random

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
该功能已实现.
[Releases](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.3) (选择`v1.2.3-35`或以上版本)
