### ISSUE TITLE
没有加别名的字段放在order by 中会报错 Column 'xxx' in field list is ambiguous.

### ISSUE THREAD

**Issue by sheenzxx** [hanchuanchuan/goInception#271]
**描述**
没有加别名的字段放在order by 中会报错 Column 'xxx' in field list is ambiguous.

**重现**
create table gl_keygen (
table_name varchar(20),
last_used_id bigint
)
select table_name from gl_keygen  order by table_name
![image](https://user-images.githubusercontent.com/3350015/94415713-7f818a80-01b0-11eb-864b-21526c0019c6.png)

下面这2种写法 却能正常解析并执行
select a.table_name from gl_keygen order by a.table_name
select table_name from gl_keygen  order by last_used_id 

**环境**
 - 数据库: [mysql]
 - 版本: [5.6.32]

**Comment by hanchuanchuan** [comment]
好，收到了，稍后会查看和修复。

**Comment by hanchuanchuan** [comment]
该问题已修复.
请更新后重试.
[releases](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.3) 选择`v1.2.3-37`及以后版本.

**Comment by sheenzxx** [comment]
> 该问题已修复.
> 请更新后重试.
> [releases](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.3) 选择`v1.2.3-37`及以后版本.

感谢
