### ISSUE TITLE
8.0的递归语法不支持

### ISSUE THREAD

**Issue by zwunix** [hanchuanchuan/goInception#274]
**描述您想要的功能：**
希望能支持递归

**可参考文档,资料,引用等：**
with recursive cte as
(
select o.n_id,o.father_id from org o where o.father_id = 43532
union all
select og.n_id,og.father_id from org og 
inner join cte r on  og.father_id = r.organization_id 
where  level_id not in (3,4)
)select group_concat(n_id) from cte

**Comment by hanchuanchuan** [comment]
暂不支持, 对查询支持的不完善, 当前主要着重于数据变更SQL的审核

**Comment by hanchuanchuan** [comment]
目录TiDB的语法解析器尚不支持该语法, 暂时无法添加.

**Comment by duguwo** [comment]
大佬，目前mysql8版本使用已经比较普遍了，能否考虑支持with 子句呢？

**Comment by duguwo** [comment]
MySQL版本的Archery+goInception已经支持with as 语法，有需要的童鞋请+QQ327092839

**Comment by amnesiaer** [comment]
8.0的递归语法不支持 https://github.com/hhyo/Archery/issues/2862
