### ISSUE TITLE
审核时检测非法日期

### ISSUE THREAD

**Issue by ganlanshu** [hanchuanchuan/goInception#277]
**描述您想要的功能：**
sql 自动检测时，对于非法的日期可以检测出来吗？如2020-11-31 日，2020-9-31，希望能检测出非法日期

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
当前仅对默认值添加了该检测, 该需求后续实现.

**Comment by hanchuanchuan** [comment]
该需求已添加. 请下载最新版本~~
[Release v1.2.3-46](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.3) 请选择小版本46及之后的版本.

**Comment by ganlanshu** [comment]
> 该需求已添加. 请下载最新版本~~
> [Release v1.2.3-46](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.3) 请选择小版本46及之后的版本.

下载了mac 46 版本，测试的时候，报了以下错误
![image](https://user-images.githubusercontent.com/8706441/98758672-5177a300-240a-11eb-8c64-1056709dabcb.png)
输入的sql语句是
![image](https://user-images.githubusercontent.com/8706441/98758727-710ecb80-240a-11eb-922a-e5dac3a95540.png)

**Comment by ganlanshu** [comment]
在配置文件里找到了  er_incorrect_datetime_value ,这个是错误级别，check的项目应该是哪个呢

**Comment by hanchuanchuan** [comment]
这种审核发给MySQL也会报错的, 所以没有开关. 而 审核的错误级别`er_incorrect_datetime_value`是为了可自定义是警告还是错误.
