### ISSUE TITLE
显式提供事务支持

### ISSUE THREAD

**Issue by ganlanshu** [hanchuanchuan/goInception#278]
**描述您想要的功能：**
可以显式支持事务的语句
begin, commit, start transactio, commit 吗
现在想用事务只能配置trans参数，控制dml的个数结合参数实现批量dml提交

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
暂只能通过`--trans`来实现事务, 或者未指定该参数时逐行提交.
通常业务端申请执行DML/DDL工单时,应该不考虑事务问题吧.

**Comment by ganlanshu** [comment]
> 暂只能通过`--trans`来实现事务, 或者未指定该参数时逐行提交.
> 通常业务端申请执行DML/DDL工单时,应该不考虑事务问题吧.

和业务端沟通了，需要上线的sql 很少需要考虑事务的，所以这里暂时没有太多要求了，--trans 参数应该够用了
