### ISSUE TITLE
建议在检测语句没有delimiter结尾时给出友好提示

### ISSUE THREAD

**Issue by hhyo** [hanchuanchuan/goInception#28]
**描述您想要的功能：**
希望在检测语句时，如果语句没有以delimiter结尾，可以给出比较友好的提示
- 语句
```
INSERT INTO `archer_test`.`test0412`(`id`) VALUES(1);
INSERT INTO `archer_test`.`test0412`(`id`) VALUES(1)
```
- 结果
![image](https://user-images.githubusercontent.com/8842982/57501230-52ada880-7319-11e9-9d17-f331b0c78d18.png)

- log
```
time="2019/05/10 03:42:29.037" level=error msg="解析失败! line 2 column 51 near \"\" (total length 103)" file=session_inception.go line=311
time="2019/05/10 03:42:29.037" level=error msg="INSERT INTO `archer_test`.`test0412`(`id`) VALUES(1)\n                            inception_magic_commit" file=session_inception.go line=312
```
**描述您考虑的解决/替代方案：**
使用更友好文案

**可参考文档,资料,引用等：**
- Inception的结果
![image](https://user-images.githubusercontent.com/8842982/57501460-25152f00-731a-11e9-9a57-5272f34aa39d.png)

**Comment by hanchuanchuan** [comment]
首先感谢建议！
可能有个更好的主意，因为我们没办法控制使用人员的输入，所以能否由程序控制结尾呢

**Comment by hhyo** [comment]
阔以，程序处理最后补`;`就好
