### ISSUE TITLE
[咨询] 当前是不支持 tidb 的 备份功能么？

### ISSUE THREAD

**Issue by Graywd** [hanchuanchuan/goInception#280]
你好， 在对 tidb 进行审计的时候， 会有这样一个报错信息，当前是不支持 tidb 么， 之后会考虑支持么。。。
inception 是不是也不支持 tidb 😳
![image](https://user-images.githubusercontent.com/11515336/99509268-82cf1080-29c0-11eb-83c1-e02bb64b28e1.png)

**Comment by hanchuanchuan** [comment]
备份功能是通过MySQL的`slave`复制协议实现的, 即模拟从库的方式.
而TiDB目前的`slave`差别很大, 所以暂时无法支持备份功能.

**Comment by Graywd** [comment]
好的，感谢🙏
