### ISSUE TITLE
支持MySQL8.0新增的keyword

### ISSUE THREAD

**Issue by nideqiao** [hanchuanchuan/goInception#283]
**描述您想要的功能：**
支持MySQL8.0新增的keyword

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**
https://dev.mysql.com/doc/refman/8.0/en/keywords.html

**Comment by hanchuanchuan** [comment]
该需求后续会更新~

**Comment by hanchuanchuan** [comment]
关键字列表已更新,请下载最新版本.
