### ISSUE TITLE
能发一个v1.2.4的版本吗

### ISSUE THREAD

**Issue by a935855375** [hanchuanchuan/goInception#284]
**描述您想要的功能：**
有依赖本项目alter table检查分区表的功能，发现有些常量丢失了

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
`golang`的项目依赖可以使用指定固定`git commit id`的方式指向固定版本,以避免版本更新导致的不兼容问题.
例如`go get github.com/hanchuanchuan/goInception@a4b1e20`

**Comment by a935855375** [comment]
感谢回答，问题已解决
