### ISSUE TITLE
ERROR 9002 (28000): SSL connection is required. Please specify SSL options and retry

### ISSUE THREAD

**Issue by jiaozhipei** [hanchuanchuan/goInception#285]
**描述**
Azure的MSYQL服务器开启在强制SSL，我在执行语句时日志报“ERROR 9002 (28000): SSL connection is required. Please specify SSL options and retry”，--ssl=required参数已经添加过了，请问这个如何解决谢谢。

**重现**
通过arcerhy执行SQL，选择【备份】

**环境**
 - 数据库: mysql
 - 版本: 5.6.47.0 MySQL Community Server (GPL)

错误日志：
time="2020/12/17 15:00:25.789" level=info msg="create BinlogSyncer with config {2000111114 mysql host01.mysql.database.chinacloudapi.cn 3306 mysql_user@host01    false false <nil> false UTC true 0 0s 0s 0 false false 0}" file=binlogsyncer.go func=NewBinlogSyncer line=144
time="2020/12/17 15:00:25.789" level=info msg="begin to sync binlog from position (mysql-bin.000012, 5464107)" file=binlogsyncer.go func=StartSync line=359
time="2020/12/17 15:00:25.795" level=info msg="Start sync error: ERROR 9002 (28000): SSL connection is required. Please specify SSL options and retry.\x00\n" file=parser.go func=parserBinlog line=249
time="2020/12/17 15:00:25.795" level=info msg="syncer is closing..." file=binlogsyncer.go func=close line=175

**Comment by hanchuanchuan** [comment]
备份功能是通过MySQL Slave复制协议实现的,以模拟从库的方式摘取Binlog.
这个报错应该是Azure MySQL做了自定义,禁止了该行为.和`--ssl`参数无关的.

**Comment by jiaozhipei** [comment]
感谢您的解答
我尝试在Azure上把强制SSL关闭就可以正常备份，重新打开就会备份失败，所以我觉得这个对MySQL Slave并没有进行限制。另外，我看您的config.toml文件示例中有这[security]，这个是做什么用的呢，我在里面加上了这些备份，但是似乎没有效果，依然是SSL connection is required那个错误。
[security]
skip_grant_table = true
# Path of file that contains list of trusted SSL CAs for connection with mysql client.
ssl-ca = "/opt/ca.pem"
# Path of file that contains X509 certificate in PEM format for connection with mysql client.
ssl-cert = "/opt/client-cert.pem"
# Path of file that contains X509 key in PEM format for connection with mysql client.
ssl-key = "/opt/client-key.pem"

**Comment by hanchuanchuan** [comment]
既然关闭SSL可以备份, 说明协议是没问题的. 
我检查了一下`go-mysql`包有SSL参数支持, 只是我没有测试环境,需要你提供一下详细的ssl设置.

另外,如果你熟悉golang的话,可以按如下方式测试:
参考 [go-mysql](https://github.com/siddontang/go-mysql) 项目首页,该包是用来支持MySQL复制协议的.
1. 复制项目首页的demo到新文件`main.go`
2. import导入包`"crypto/tls"`
3. 修改cfg到测试的Azure MySQL数据库
4. 在 `syncer := replication.NewBinlogSyncer(cfg)` 上面添加一行:
`cfg.TLSConfig = &tls.Config{InsecureSkipVerify: true}`
5. 之后运行该文件看是否有报错即可.

PS: `[security]`段可以设置到远程数据库的访问方式,如开启`ssl`安全访问. 
或者开启`skip_grant_table`打开鉴权功能,goinception默认免密,因为其没有任何数据,只作为中间件存在的.

**Comment by jiaozhipei** [comment]
我用上面的方法测试了一下，加上`cfg.TLSConfig = &tls.Config{InsecureSkipVerify: true}`这一行，即可正常获取到binlog数据，
如果不加的话，会提示显示下面的提示，所以我觉得那一行，还是有效果的。
```
[2020/12/18 08:04:32] [info] binlogsyncer.go:360 begin to sync binlog from position (mysql-bin.000012, 5524015)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x606177]

goroutine 1 [running]:
github.com/siddontang/go-mysql/replication.(*BinlogStreamer).GetEvent(0x0, 0x6d9f20, 0xc0000b2000, 0x544a2f, 0x0, 0x6d62c0)
        /go/pkg/mod/github.com/siddontang/go-mysql@v1.1.0/replication/binlogstreamer.go:25 +0x37
main.main()
        /go/sql_test/main.go:32 +0xd4
exit status 2
```

**Comment by hanchuanchuan** [comment]
`--ssl`参数你设置的是什么

**Comment by jiaozhipei** [comment]
我在archery里的`sql/engines/goinception.py`设置的设置是`--ssl=required`

**Comment by hanchuanchuan** [comment]
更新了版本,可以试一下.
改动内容如下:
![image](https://user-images.githubusercontent.com/18544383/102596922-d1ed9a00-4154-11eb-973a-3e66525491ac.png)

https://github.com/hanchuanchuan/goInception/releases/download/v1.2.3/goInception-linux-v1.2.3-58-ga4b1e20-dirty.tar.gz

**Comment by jiaozhipei** [comment]
您好，备份成功了，回滚的日志里也可以下载了。我看日志里还有一些错误，麻烦看一下是否有影响吧。谢谢
```
time="2020/12/18 18:29:17.188" level=info msg="begin to sync binlog from position (mysql-bin.000012, 5551303)" file=binlogsyncer.go func=StartSync line=359
time="2020/12/18 18:29:17.250" level=info msg="rotate to (mysql-bin.000012, 5551303)" file=binlogsyncer.go func=parseEvent line=776
time="2020/12/18 18:29:17.251" level=info msg="syncer is closing..." file=binlogsyncer.go func=close line=175
time="2020/12/18 18:29:17.302" level=error msg="kill connection 64358 error ERROR 1094 (HY000): Unknown thread id: 64358" file=binlogsyncer.go func=killConnection line=843
time="2020/12/18 18:29:17.303" level=info msg="kill last connection id 64358" file=binlogsyncer.go func=killConnection line=849
time="2020/12/18 18:29:17.351" level=info msg="syncer is closed" file=binlogsyncer.go func=close line=202
```

**Comment by hanchuanchuan** [comment]
这个可以忽略,只是断开binlog复制,我优化一下.

**Comment by jiaozhipei** [comment]
OK，那暂时没问题了。多谢
