### ISSUE TITLE
是不是不支持select语句的执行

### ISSUE THREAD

**Issue by zhuzhuwonder** [hanchuanchuan/goInception#290]
**描述**
对select语句select version_name from version_table where id=1;发起检测的时候没有报错，但是发起执行的时候报错Not supported statement type. 

**环境**
 - 数据库: [mysql]
 - 版本: [例如 v1.2.3-55]

**参数**
安装包的default参数

**Comment by hanchuanchuan** [comment]
不支持执行的，goinception是用来做审核服务的。

**Comment by zhuzhuwonder** [comment]
> 不支持执行的，goinception是用来做审核服务的。

--check=1的时候做审核，--execute=1的时候做执行吧。我试了一下update是可以执行的，但是select不行

**Comment by hanchuanchuan** [comment]
不支持`select`的执行。

**Comment by hanchuanchuan** [comment]
支持DDL/DML语句。
