### ISSUE TITLE
数据库密码包含 * 号 无法正确解析 连接串

### ISSUE THREAD

**Issue by sheenzxx** [hanchuanchuan/goInception#291]
**描述**
在python2.7 代码中调用goinception
db 为连接goinception 服务器的数据库游标

ip='xxx,xx,xx,xx'
port=3306
dbname='youname'
db_user='youname'
password='%\*xssdfsd'
sql="select 1"
inceptionstr="""/\*--host=%s;--port=%s;--user=%s;--password=%s;%s;\*/
                inception_magic_start;
                use %s;
                %s;
                inception_magic_commit;
    """%(ip,port,db_user,password,options,dbname,sql)
db.execute(inceptionstr)
data=db.fetchall()
print(data)
((1L, u'CHECKED', 2, u'Audit Completed', u'Invalid source infomation(主机名为空,端口为0,用户名为空).', u'\n                inception_magic_start', 0L, u'0_0_00000000', None, u'0', None, u'0'),)

**Comment by hanchuanchuan** [comment]
`--password=%s;`
改成
`--password='%s';` 试试看

**Comment by sheenzxx** [comment]
> `--password=%s;`
> 改成
> `--password='%s';` 试试看

可以了。谢谢
