### ISSUE TITLE
gbk字符集备份失败问题

### ISSUE THREAD

**Issue by liuxinwang** [hanchuanchuan/goInception#292]
**描述**
mysql数据库使用gbk编码，dml执行后生成备份sql包含中文导致乱码，无法写入备份库：
Incorrect string value: '\xD3\xD1\xC7\xE9\xC1\xB4...' for column 'rollback_statement' at row 1.

通过对go-mysql进行测试，问题出在go-mysql，对gbk字符集表数据行解析binlog也是出现乱码问题：
`CREATE TABLE `t1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=gbk;

insert into t1 values(26, '哈哈');

WriteRowsEventV1
Date: 2020-12-29 18:05:31
Log position: 5384
Event size: 39
TableID: 4712
Flags: 1
Column count: 2
Values:

0:26
1:"\xb9\xfe\xb9\xfe"
`
**重现**
对一个包含中文字段的行进行修改。

**环境**
 - 数据库: mysql
 - 版本: 5.5.30

**参数**
无

**Comment by hanchuanchuan** [comment]
可以设置参数 `hex_blob` 来强制以二进制方式写入数据库。

另外默认字符集是`utf8mb4`，参数 `default_charset` 可以用来指定client字符集，如果使用时出现了DML写入乱码问题可配置该项。

**Comment by liuxinwang** [comment]
> 可以设置参数 `hex_blob` 来强制以二进制方式写入数据库。
> 
> 另外默认字符集是`utf8mb4`，参数 `default_charset` 可以用来指定client字符集，如果使用时出现了DML写入乱码问题可配置该项。

我是通过archery平台进行测试的，目前更新了最新的v1.2.4-6-g296ef6c 版本，经过测试，创建表指定gbk是不会报错了，另一个问题是无论archery给实例配置utf8还是gbk，goinception都是只会使用`default_charset`进行连接处理，如果`default_charset`配置为gbk，archery提交的dml写入中文还是会出现乱码，这块感觉是archery默认给到goinception是用的utf8，所以导致乱码；

**Comment by hanchuanchuan** [comment]
那你只设置 `hex_blob` 参数试试看， `default_charset` 保持不变。

**Comment by liuxinwang** [comment]
> 那你只设置 `hex_blob` 参数试试看， `default_charset` 保持不变。

这个没有测试，设置了sql只能备份成二进制了吧，回滚sql中是看到正常的语句了吧；我现在是在解析binlog的逻辑中对string字段字符串非utf8格式的进行了一次字符集编码的转换，暂时用这种办法解决了现在的问题。

**Comment by hanchuanchuan** [comment]
**GBK备份结果：**
![image](https://user-images.githubusercontent.com/18544383/103526363-c2dc4b00-4ebb-11eb-8e73-fc3b5281e0e3.png)

**回滚测试：**
![image](https://user-images.githubusercontent.com/18544383/103526409-d7b8de80-4ebb-11eb-8ce2-17effe065f61.png)
