### ISSUE TITLE
自定义审核级别里关于mariadb的提示信息

### ISSUE THREAD

**Issue by lenovore** [hanchuanchuan/goInception#295]
mariadb做dml操作时会有提示信息：MariaDB v100324 对回滚支持不完美,请注意确认回滚语句是否正确

错误等级是1，如何设置成0或者不提示这个信息

看图
![clipboard](https://user-images.githubusercontent.com/29646774/104554647-75a86800-5677-11eb-9c57-87ca13702ce3.png)

**Comment by hanchuanchuan** [comment]
该问题之后会支持自定义规则来控制是否提示.

**Comment by hanchuanchuan** [comment]
该问题已优化.
可更新到[v1.2.4-15](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.4)版本后执行如下命令:
```
inc set level er_mariadb_rollback_warn = 0;
```

**Comment by lenovore** [comment]
ok
