### ISSUE TITLE
goinception在进行审核的时候报源库信息错误

### ISSUE THREAD

**Issue by skymoou** [hanchuanchuan/goInception#297]
**描述**
进行审核时候报错

**重现**
登陆goinception 控制台
执行如下
 /*--user=root;-password=123456;--host=127.0.0.1;--port=3306;--check=1;*/
inception_magic_start;

结果：
+----------+---------+-------------+-----------------+---------------------------------------------------------+-----------------------+---------------+--------------+---------------+--------------+---------+-------------+
| order_id | stage   | error_level | stage_status    | error_message                                           | sql                   | affected_rows | sequence     | backup_dbname | execute_time | sqlsha1 | backup_time |
+----------+---------+-------------+-----------------+---------------------------------------------------------+-----------------------+---------------+--------------+---------------+--------------+---------+-------------+
|        1 | CHECKED |           2 | Audit Completed | Invalid source infomation(inception语法格式错误).       | inception_magic_start |             0 | 0_0_00000000 | NULL          | 0            | NULL    | 0           |
+----------+---------+-------------+-----------------+---------------------------------------------------------+-----------------------+---------------+--------------+---------------+--------------+---------+-------------+

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.32]

**Comment by hanchuanchuan** [comment]
审核操作只能以编程方式调用. 在交互式窗口仅能执行管理命令.

**Comment by skymoou** [comment]
哦哦，好的，谢谢
