### ISSUE TITLE
执行alter datatbase报错语法问题

### ISSUE THREAD

**Issue by liuhaibo0303** [hanchuanchuan/goInception#299]
提供如下sql
alter database test_inc default character set utf8

报错如下：
You have an error in your SQL syntax, near 'database test_inc default character set utf8' at line 1" 
![image](https://user-images.githubusercontent.com/32126569/106101423-db691980-6178-11eb-8e14-9b9f98175dc2.png)

直接在mysql上执行是没有问题的

**环境**
 - 数据库: mysql 5.6/5.7
 - 版本: goInception-macOS-v1.2.4

**Comment by hanchuanchuan** [comment]
语法已添加支持, 默认是关闭的,可通过选项`enable_alter_database`启用.

可升级到版本 `v1.2.4-23`.
