### ISSUE TITLE
表DDL变更支持pt-online-schema-change 或者 gh-ost工具么？

### ISSUE THREAD

**Issue by dikang123** [hanchuanchuan/goInception#3]
如题，非常好奇

**Comment by hanchuanchuan** [comment]
已支持pt-online-schema-change，后续也会添加gh-ost的支持

[releases](https://github.com/hanchuanchuan/goInception/releases)

**Comment by dikang123** [comment]
👍

**Comment by xialuo1990** [comment]
个人觉得可以将gh-ost包直接引入过去

**Comment by hanchuanchuan** [comment]
是的，多谢建议！
有这方面的打算，现阶段还在完善审核和执行的测试用例，所以可能会晚一点添加。

**Comment by hanchuanchuan** [comment]
已支持gh-ost

[releases](https://github.com/hanchuanchuan/goInception/releases)
