### ISSUE TITLE
Not supported statement type

### ISSUE THREAD

**Issue by jerryhu1234** [hanchuanchuan/goInception#30]
**描述**
不支持alter table test auto_increament 20000 comment 'test'
原生的inception支持。
**重现**
alter table test auto_increament 20000 comment 'test'
提示：
Not supported statement type

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**

**Comment by hanchuanchuan** [comment]
感谢指出，会尽快予以支持。

**Comment by hanchuanchuan** [comment]
[v0.7.4版本](https://github.com/hanchuanchuan/goInception/releases/tag/v0.7.4) 已更新
