### ISSUE TITLE
使用inception stop alter 终止 gh-ost 执行可能导致应用 hang

### ISSUE THREAD

**Issue by hhyo** [hanchuanchuan/goInception#305]
**描述**
使用 inception kill osc  终止 gh-ost 执行可能导致 goInception 应用 hang 住，无法新建连接，也无日志打印，只能强制结束进程

**重现**
暂时无法稳定重现，目前出现过三次，大致步骤
- 调用 inception kill osc 终止正在执行的语句 ，终止请求成功
- 此后再也无法连接goInception，最长等待10分钟左右，最终只能强制结束进程

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.20]

**参数**
暂无

**Comment by hanchuanchuan** [comment]
该问题已优化。

**Comment by hhyo** [comment]
优化代码具体是？

**Comment by hanchuanchuan** [comment]
还是之前已经优化过的osc并发问题。
