### ISSUE TITLE
执行过程中远程数据库连接中断，重新连接时没有设置数据库信息（No database selected ）

### ISSUE THREAD

**Issue by hhyo** [hanchuanchuan/goInception#306]
**描述**
一个执行工单有多条语句，其中某条语句执行时间过长（通过osc），远程数据库连接超时被关闭，下一条语句执行时，虽然自动进行了重连，但是并没有指定database，导致执行失败

**重现**
- 配置`ignore_osc_alter_stmt = 'drop index'`，提交工单，或者是一个大表变更，一个小表变更也可以
```
ALTER TABLE query_log add INDEX idx_idm(id);
ALTER TABLE query_log drop INDEX idx_idm;
```
- 第一条执行完成后，kill掉远端的数据库链接
- 执行第二条语句时报错，提示 No database selected 
- 截图
![image](https://user-images.githubusercontent.com/8842982/108618488-c6bb3100-7459-11eb-8a77-d3a1047be7b1.png)

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.20]

**参数**
`ignore_osc_alter_stmt = 'drop index'`

**日志**
```
INFO[2021/02/21 15:23:07.130] Closed streamer connection. err=<nil>         file=streamer.go func=Close line=216
INFO[2021/02/21 15:23:07.130] Tearing down throttler                        file=migrator.go func=teardown line=1377
[mysql] 2021/02/21 15:23:37 packets.go:122: closing bad idle connection: EOF
ERRO[2021/02/21 15:23:49.483] con:8 Error 1046: No database selected sql:ALTER TABLE query_log drop INDEX idx_idm  file=conn.go func=exec line=91
ERRO[2021/02/21 15:23:49.485] con:8 Error 1046: No database selected        file=session_inception.go func=executeRemoteStatement line=1462
```

错误方法：exec，好像s.db.DB().Exec有内部重试，并没有触发ErrInvalidConn，直接是Error 1046，所以没有进入initConnection的逻辑
```
// exec 执行sql语句,连接失败时自动重连,自动重置当前数据库
func (s *session) exec(sqlStr string, retry bool) (res sql.Result, err error) {
	// 连接断开无效时,自动重试
	for i := 0; i < maxBadConnRetries; i++ {
		res, err = s.db.DB().Exec(sqlStr)
		if err == nil {
			return
		}
		log.Errorf("con:%d %v sql:%s", s.sessionVars.ConnectionID, err, sqlStr)
		if err == mysqlDriver.ErrInvalidConn {
			err1 := s.initConnection()
			if err1 != nil {
				return res, err1
			}
			if retry {
				s.appendErrorMessage(mysqlDriver.ErrInvalidConn.Error())
				continue
			} else {
				return
			}
		}
		return
	}
	return
}
```

**Comment by hanchuanchuan** [comment]
之前已经开放了参数`wait_timeout`来设置会话级超时。
现在新提交了PR将两个功能相结合，仅在wait_timeout>=600s时才会判断`数据库未选择错误`并进行**重连和重新执行**。

**Comment by hhyo** [comment]
什么场景会出现mysqlDriver.ErrInvalidConn这个，测试wait_timeout和主动kill都是1046的错误

**Comment by hanchuanchuan** [comment]
`go-sql-driver`自动维护的线程池连接失效时间如果大于数据库`wait_timeout`可能出现该异常。

之前偶尔出现在备份库中，比如备份库`wait_timeout`为10min，而执行使用了20min，此时数据库便需要重连。
