### ISSUE TITLE
大表调用OSC，执行进度显示：没有找到匹配的记录，goinception报错：runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhituanchen** [hanchuanchuan/goInception#309]
**描述**
您好：麻烦分析一下以下情况：
archery工具SQL上线执行时候，大表调用OSC，点击查看进度，执行进度显示：没有找到匹配的记录，工单最后是执行成功；
查看到goinception报错(每次点击刷新按钮就会出现一次报错)：
msg="lastCmd inception get osc_percent '*8F7341D6DEFD21714B24B21D82A5BA3AD0C9242D';, runtime error: invalid memory address or nil pointer dereference, goroutine 859
备注：之前使用时候是有进度；

**重现**
使用archery工具大表OSC功能，点击查看进度信息，执行进度显示：没有找到匹配的记录，查看goinception日志出现报错
截图信息：
![image](https://user-images.githubusercontent.com/71009460/109240875-4b6bcd80-7813-11eb-9a72-01f07a5f509f.png)

archery日志信息：
![image](https://user-images.githubusercontent.com/71009460/109240916-5a528000-7813-11eb-90c5-939b8b62123d.png)

goinception日志：
![image](https://user-images.githubusercontent.com/71009460/109240954-6e967d00-7813-11eb-812f-cbc991e1c0bb.png)

time="2021/02/25 10:25:32.255" level=error msg="lastCmd inception get osc_percent '*8F7341D6DEFD21714B24B21D82A5BA3AD0C9242D';, runtime error: invalid memory address or nil pointer dereference, goroutine 859 [running]:\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run.func1(0xc00a8d0000, 0xc00a759ddf)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:420 +0x106\npanic(0x15f7d60, 0x2b57ad0)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\nsync.(*RWMutex).RLock(...)\n\t/usr/local/go/src/sync/rwmutex.go:48\ngithub.com/hanchuanchuan/goInception/session.(*session).executeLocalShowOscProcesslist(0xc00ae4c000, 0xc00a9c10e0, 0xc00a019558, 0x1, 0x1, 0xc00aeb8d08, 0x1)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:5961 +0x614\ngithub.com/hanchuanchuan/goInception/session.(*session).processCommand(0xc00ae4c000, 0x1abda20, 0xc00ac22f80, 0x1ac3220, 0xc00a9c10e0, 0xc0002a5f91, 0x45, 0x1832c3c, 0x12, 0xc00ac267f0, ...)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:661 +0x1181\ngithub.com/hanchuanchuan/goInception/session.(*session).executeInc(0xc00ae4c000, 0x1abda20, 0xc00ac22f80, 0xc0002a5f91, 0x46, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:379 +0x2aae\ngithub.com/hanchuanchuan/goInception/session.(*session).ExecuteInc(0xc00ae4c000, 0x1abda20, 0xc00ac22f80, 0xc0002a5f91, 0x46, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/session/session_inception.go:122 +0x1cb\ngithub.com/hanchuanchuan/goInception/server.(*TiDBContext).Execute(0xc00a9c0cf0, 0x1abda20, 0xc00ac22f80, 0xc0002a5f91, 0x46, 0xc00b5fbaf8, 0xc00f34eb0c, 0xf34eb0c0a019c08, 0xc00a019c08, 0x42c73f)\n\t/go/src/github.com/hanchuanchuan/goInception/server/driver_tidb.go:259 +0x7c\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).handleQuery(0xc00a8d0000, 0x1abda20, 0xc00ac22f80, 0xc0002a5f91, 0x46, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:880 +0x80\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).dispatch(0xc00a8d0000, 0xc0002a5f91, 0x47, 0x47, 0x0, 0x0)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:632 +0x5bd\ngithub.com/hanchuanchuan/goInception/server.(*clientConn).Run(0xc00a8d0000)\n\t/go/src/github.com/hanchuanchuan/goInception/server/conn.go:465 +0x158\ngithub.com/hanchuanchuan/goInception/server.(*Server).onConn(0xc00bddcf50, 0x1ad42c0, 0xc00b7b0b38)\n\t/go/src/github.com/hanchuanchuan/goInception/server/server.go:327 +0x20d\ncreated by github.com/hanchuanchuan/goInception/server.(*Server).Run\n\t/go/src/github.com/hanchuanchuan/goInception/server/server.go:272 +0x407\n" file=conn.go func=func1 line=422

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.18]

**参数**
修改过以下参数（config.toml）：
[inc]                                 
enable_fingerprint                      =true                                                                         
enable_not_innodb                       =false                                                                         
enable_pk_columns_only_int              =false                                     
enable_set_collation                    =true                                    
enable_set_engine                       =false                              
max_keys                                =5                                         
max_key_parts                           =5                                                                       
max_primary_key_parts                   =5                                         
support_collation                       ="utf8_general_ci,utf8mb4_general_ci,utf8mb4_unicode_ci" 

[osc]
osc_on = true
osc_min_table_size = 16
osc_print_none = true
osc_bin_dir = "/usr/local/bin"
osc_max_thread_connected = 3000
osc_critical_thread_connected = 2500
osc_check_replication_filters = false
osc_alter_foreign_keys_method = "auto"

**备注**
archery的issue：https://github.com/hhyo/Archery/issues/1033

**Comment by hanchuanchuan** [comment]
已修复，稍后发布新版本

**Comment by zhituanchen** [comment]
好的：
 发布版本后麻烦说明一下哪个版本修复，非常感谢。

**Comment by hanchuanchuan** [comment]
版本已更新，请选择v1.2.4-32及之后版本下载。
https://github.com/hanchuanchuan/goInception/releases

**Comment by zhituanchen** [comment]
您好：
可以使用docker方式下载对应的镜像么，我这边拉取镜像文件报错
![image](https://user-images.githubusercontent.com/71009460/110426131-80fc9a80-80e0-11eb-93e5-a7279c067696.png)
还是有其他的安装方式

**Comment by zhituanchen** [comment]
您好：
这边已经使用v1.2.4-32及之后版本替换，当前使用正常了，但是还是看到有一些报错，看看能否优化一下（暂时没有发现影响使用）
![image](https://user-images.githubusercontent.com/71009460/110431024-3252fe80-80e8-11eb-90f3-d25a4c9b9509.png)
