### ISSUE TITLE
mysql5.6版本操作DDL提供ALGORITHM=INPLACE, LOCK=NONE;

### ISSUE THREAD

**Issue by jerryhu1234** [hanchuanchuan/goInception#31]
**描述您想要的功能：**
mysql5.6版本操作DDL提供ALGORITHM=INPLACE, LOCK=NONE;
alter table add column a varchar(4) ,ALGORITHM=INPLACE, LOCK=NONE;
这个操作可以不锁表操作，支持在线DDL功能。
**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**
https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl-operations.html

**Comment by jerryhu1234** [comment]
目前 测试报不支持的类型。

**Comment by hanchuanchuan** [comment]
[v0.7.5版本](https://github.com/hanchuanchuan/goInception/releases/tag/v0.7.5) 已更新
