### ISSUE TITLE
建议增加超时控制

### ISSUE THREAD

**Issue by xxlrr** [hanchuanchuan/goInception#310]
**描述您想要的功能：**
通过goInception修改数据库时，goIncep的会话可能被阻塞，希望能增加全局或会话级别的调度选项来控制单挑语句最大执行时间。

**描述您考虑过的解决/替代方案：**
> '>= mysql 5.7.?  可通过session.max_execution_time控制
 '< mysql 5.7.?  goInception需要自维护定时器(子线程)，超时登陆mysql server端kill线程。（曾测试过mysql client端主动结束连接，没用）

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
添加新参数`max_execution_time`的设置，来控制DML语句的最大执行时间，下载最新版本即可。
