### ISSUE TITLE
gbk加进support_charset检测还是不通过，是我配置的有问题吗？求助

### ISSUE THREAD

**Issue by dba-ws** [hanchuanchuan/goInception#311]
**描述**
这个gbk加到参数support_charset 检测还是不通过，是我配置的有问题吗？求助[表情]

**重现**
CREATE TABLE `demo` (
  `id` bigint(20) NOT NULL DEFAULT '0' COMMENT '主键',
  `ver` mediumint(8) NOT NULL DEFAULT '0' COMMENT '版本号',
  `name` varchar(60) NOT NULL DEFAULT '' COMMENT '名称',
  `description` varchar(2700) NOT NULL DEFAULT '' COMMENT '描述',
  `status` varchar(20) NOT NULL DEFAULT '' COMMENT '状态',
  `userid` bigint(20) NOT NULL DEFAULT '0' COMMENT 'userid',
  `starttime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '开始时间',
  `endtime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '结束时间',
  `exceptionStatus` tinyint(5) NOT NULL DEFAULT '0' COMMENT '异常状态',
  `ctime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  `utime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_ctime` (`ctime`),
  KEY `idx_userid_status` (`userid`, `status`)
) ENGINE = InnoDB DEFAULT CHARSET = gbk COMMENT = 'demo表';

检测提示：
error   Unknown charset gbk.

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.26]

**参数**
enable_set_charset                      =true
enable_set_collation                    =false
support_charset                         ="gbk,utf8,utf8mb4"
support_collation                       ="utf8_general_ci,utf8mb4_general_ci"

**Comment by hanchuanchuan** [comment]
该问题在两个月前的版本中已修复，可升级后重试。
