### ISSUE TITLE
varchar超出长度未拦截

### ISSUE THREAD

**Issue by 380847438** [hanchuanchuan/goInception#313]
该sql审核通过：
CREATE TABLE `t_app_version_info` (
 `id` BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
 `channel` INT (11) DEFAULT NULL COMMENT '客户端类型',
 `white_list` VARCHAR (16000) DEFAULT NULL COMMENT '升级白名单',
 `black_list` VARCHAR (2000) DEFAULT NULL COMMENT '升级黑名单',
 PRIMARY KEY (`id`)
) ENGINE = INNODB AUTO_INCREMENT = 1 COMMENT = '升级信息配置表';
执行报错：
Execute: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs.
原因分析：
VARCHAR (16000) 未检出
建议改进：
VARCHAR (16000)能够提示报错，或者提示该位置可能会有错误。

**Comment by 380847438** [comment]
这算是个bug

**Comment by hanchuanchuan** [comment]
已完善表行大小的审核逻辑，请下载 `v1.2.4-53` 及之后版本后重试。
