### ISSUE TITLE
alter语句未走osc

### ISSUE THREAD

**Issue by qq290070744** [hanchuanchuan/goInception#315]
**描述**
alter语句未走osc
`ALTER TABLE
  px_coupon_expire_back_2 CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`
**重现**
模拟重现的步骤
![image](https://user-images.githubusercontent.com/18340634/110599310-ae6b4600-81bd-11eb-8e6f-dd96aca48ee8.png)

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
osc_min_table_size 已经设置为 0

**Comment by qq290070744** [comment]
![image](https://user-images.githubusercontent.com/18340634/110604785-694a1280-81c3-11eb-93c9-1ff47698c220.png)

**Comment by qq290070744** [comment]
![image](https://user-images.githubusercontent.com/18340634/110910051-ccff4780-834b-11eb-816a-107e5d249ec9.png)
这条语句估计是被自动跳过osc了，但是是会锁表的

**Comment by qq290070744** [comment]
`ALTER TABLE tbl_name CHARACTER SET = charset_name;`   是改的是新进来的数据的字符集，老数据的字符集不变化。
`ALTER TABLE tbl_name CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`   加上CONVERT是把老的数据和新的数据的字符集都改变，会锁表

**Comment by hanchuanchuan** [comment]
该问题已优化，请升级到`v1.2.4-45`版本后重试。

**Comment by qq290070744** [comment]
ok
