### ISSUE TITLE
gh-ost终止后再执行报错：sock: bind: address already in use.

### ISSUE THREAD

**Issue by sona-yuan** [hanchuanchuan/goInception#317]
**描述**
gh-ost终止后再执行报错：sock: bind: address already in use.

**重现**
大表alter使用gh-ost，终止操作后sock依然存在，再次执行报错sock: bind: address already in use.

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.31]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
在最新版本会缓解该问题。另外该sock文件(`/tmp`目录下)可手动清理掉。
