### ISSUE TITLE
请问goinception是否支持检查指定字段是否存在的功能

### ISSUE THREAD

**Issue by czxin788** [hanchuanchuan/goInception#318]
**描述您想要的功能：**
请问goinception是否支持检查指定字段是否存在。
因为我们的规范要求，创建的表必须有创建时间字段（create_time）和更新时间字段（update_time），否则创建的该表不给创建。
请问这个需求goinception支持吗，应该怎么设置。
比如创建的表如下：
create table t (
id int primary key,
name varchar(10),
create_time datetime,
update_time timestamp
........
)

**Comment by hanchuanchuan** [comment]
可配置参数 `must_have_columns`

文档 https://hanchuanchuan.github.io/goInception/options.html
