### ISSUE TITLE
配置backup等参数不生效

### ISSUE THREAD

**Issue by yab** [hanchuanchuan/goInception#32]
**描述**
配置以下参数后，启动不生效：
backup_host = "10.1.3.100"
backup_port = 3306
backup_user = "xxx"
backup_password = "xxxxx"

**重现**
模拟重现的步骤
1，修改config/config.toml.template为config/config.toml
2，在lower-case-table-names = 2下面，加入以下备份参数：
backup_host = "10.1.3.100"
backup_port = 3306
backup_user = "xxx"
backup_password = "xxxxx"
3，启动：
nohup ./goInception -config=config/config.toml &
4，登录到inception,查看参数：
mysql> inception show variables like "backup%";
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| backup_host     |       |
| backup_password |       |
| backup_port     | 0     |
| backup_user     |       |
+-----------------+-------+
4 rows in set (0.00 sec)
**环境**
 - goInception版本: goInception-linux-amd64-v0.8.1.tar.gz
 - goInception -V显示的内容：
Release Version: None
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: None
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
 - go的版本：
go version go1.12.5 linux/amd64
 - linux版本：
CentOS Linux release 7.6.1810 (Core) 
Linux conf122 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hanchuanchuan** [comment]
`backup_*`相关参数写在配置文件的[inc]下，报歉这一部分模板不够详细，稍后会更新模板文件，明确所有参数的位置。

**Comment by yab** [comment]
> `backup_*`相关参数写在配置文件的[inc]下，报歉这一部分模板不够详细，稍后会更新模板文件，明确所有参数的位置。

测试将backup等参数放到[inc]下面以后就生效啦，谢谢解答！
mysql> inception show variables like 'backup%';
+-----------------+-------------------------------------------+
| Variable_name   | Value                                     |
+-----------------+-------------------------------------------+
| backup_host     | 10.1.3.100                                |
| backup_password | *xxxxx |
| backup_port     | 3306                                      |
| backup_user     | xxxx                                       |
+-----------------+-------------------------------------------+
4 rows in set (0.00 sec)
