### ISSUE TITLE
能否公布 GoInception 后续的发展计划和发展进度

### ISSUE THREAD

**Issue by waitspring** [hanchuanchuan/goInception#322]
**描述您想要的功能：**
能否在 wiki 或是 readme 文档内公布 GoInception 项目后续的发展计划和发展进度。
这样，已经部署有 GoInception 中间件的团队，才能够根据项目的发展情况，计划是否在相应节点升级中间件

**描述您考虑过的解决/替代方案：**
基于 wiki 或是 readme 文档公布 GoInception 项目的发展计划

**可参考文档,资料,引用等：**
暂无

**Comment by hanchuanchuan** [comment]
goInception在一年多前已经正式发布了，后面的更新主要是一些BUG或者小需求，如兼容MySQL8.0之类的。

因其定位就是类MySQL数据库的SQL语法审核和执行，功能比较单一，所以只会在现有功能上做些小优化，不会再做大范围的调整。
