### ISSUE TITLE
生成虚拟列表delete操作生成的回滚无法正常执行

### ISSUE THREAD

**Issue by skyecool** [hanchuanchuan/goInception#324]
**描述**
生成虚拟列表的delete操作生成的insert回滚语句无法正常执行，原因是生成的insert 回滚语句包含了虚拟的的字段数据，虚拟列不能指定数据
Execute: The value specified for generated column 'project' in table 't1' is not allowed.

**重现**
模拟重现的步骤

-- 创建测试表
CREATE TABLE `t1` (
  `id` int(10) unsigned NOT NULL primary key auto_increment  comment "主键",
  `c1` int(10) NOT NULL default 1  comment "c1",
  `jdoc` json DEFAULT NULL comment "json类型字段",
  `project` varchar(30) GENERATED ALWAYS AS (json_unquote(json_extract(`jdoc`,'$."project"'))) VIRTUAL NOT NULL comment "json生成虚拟列",
  `author` varchar(15) GENERATED ALWAYS AS (json_unquote(json_extract(`jdoc`,'$."author"'))) VIRTUAL NOT NULL comment "json生成虚拟列",
  `url` varchar(200) GENERATED ALWAYS AS (json_unquote(json_extract(`jdoc`,'$."url"'))) VIRTUAL NOT NULL comment "json生成虚拟列",
  `c2` int(11) GENERATED ALWAYS AS ((`c1` + 1)) STORED comment "json生成虚拟列"
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment '生成虚拟列表delete回滚测试';

-- 写入测试数据
INSERT INTO t1(jdoc,c1) VALUES('{"project": "goInception","author": "hanchuanchuan", "url": "https://github.com/hanchuanchuan/goInception"}',100);

-- delete删除测试
DELETE FROM `t1` WHERE `id`=1

-- 提交delete删除回滚工单并执行，报异常

![image](https://user-images.githubusercontent.com/25856760/111742296-e0b62b00-88c2-11eb-90a5-1a7d69091319.png)

**环境**
 - 数据库: MySQL
 - 版本: 5.7.32

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
该问题已修复。
可升级到`v1.2.4-49`及之后版本后重试。
