### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by ywhywl** [hanchuanchuan/goInception#332]
采用 ：
go.mod_wall 
go： 1.15
编译报错如下
# github.com/hanchuanchuan/goInception/session
session/osc.go:536:31: cannot use migrationContext (type *"github.com/hanchuanchuan/gh-ost/go/base".MigrationContext) as type *"github.com/github/gh-ost/go/base".MigrationContext in argument to logic.NewMigrator
session/osc.go:571:10: migrator.Log undefined (type *logic.Migrator has no field or method Log)
session/osc.go:602:31: migrator.Log undefined (type *logic.Migrator has no field or method Log)

**Comment by hanchuanchuan** [comment]
使用`go.mod`文件或者把`go.mod`文件中`replace`部分的内容复制到`go.mod_wall`也可以。

**Comment by hanchuanchuan** [comment]
`master`分支已更新`go.mod_wall`内容，可重新下载。
