### ISSUE TITLE
调用PT-OSC 失败

### ISSUE THREAD

**Issue by 402309718** [hanchuanchuan/goInception#335]
**描述**
连接非3306端口mysql时候，使用OSC去操作时候出发https://jira.percona.com/browse/PT-1911?attachmentViewMode=list bug

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by chengegelaile** [comment]
我也是这个问题，楼主怎么解决的？

**Comment by hanchuanchuan** [comment]
该问题已修复，可更新到版本 [v1.2.4-71](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.4)及之后版本并重试。
