### ISSUE TITLE
可以支持对字段类型定义null ？

### ISSUE THREAD

**Issue by lazzyfu** [hanchuanchuan/goInception#337]
**描述您想要的功能：**
业务场景需求，需要对不同类型的字段支持允许定义为null
比如：finished_at datetime null default null 
这种时候需要对finished_at 定义为null

或者软删除时候的唯一索引，字段允许为null

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
暂时没有相应参数来实现该功能，警告信息可以忽略。
