### ISSUE TITLE
帐号密码不支持封号字符

### ISSUE THREAD

**Issue by ianherman** [hanchuanchuan/goInception#338]
描述：
1、在v1.1.4 支持封号字符的密码（mysql)
./goInception -V
Release Version: v1.1.4
2、在1.2.4 不支持封号字符的密码（mysql)
./goInception -V
Release Version: v1.2.4-69-ge6a8caa-dirty
比如密码为 aadsfsa#$%;  是支持的
在新版中密码为 aadsfsa#$%;  不支持

**Comment by ianherman** [comment]
不支持非分区表转分区表功能

**Comment by hanchuanchuan** [comment]
分号是配置项的分割符，所以密码中是不能出现分号的，无法解析出正确的密码。

**Comment by hanchuanchuan** [comment]
分区表问题请另提一个issue，麻烦提供相应SQL语句。
