### ISSUE TITLE
SQL检测对tidb检测报错

### ISSUE THREAD

**Issue by sona-yuan** [hanchuanchuan/goInception#339]
**描述**
对tidb的delete和update执行sql检测时报错，create 和 alter暂时未发现报错

**重现**
sql: Scan error on column index 1, name "estRows": converting driver.Value type []uint8 ("N/A") to a float64: invalid syntax.
**环境**
 - 数据库: [tidb]
 - 版本: [4]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
稍后会优化该问题。

**Comment by hanchuanchuan** [comment]
该问题已修复，可更新到版本 [v1.2.4-70](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.4)及之后版本并重试。

**Comment by sona-yuan** [comment]
已修复
