### ISSUE TITLE
incepition参数均通过mysql客户端连接,通过命令行形式方式调用goinception(类似MySQL服务)失效

### ISSUE THREAD

**Issue by WuhuGoldPilot** [hanchuanchuan/goInception#341]
**描述**
在mysql客户端输入inception命令无效

**重现**
如图
![image](https://user-images.githubusercontent.com/32405381/118089796-59d18a80-b3fb-11eb-9f5c-927019a49756.png)

**环境**
 - 数据库: [mysql]
 - 版本: [ 5.7.21]

**Comment by hanchuanchuan** [comment]
参考 #297
