### ISSUE TITLE
Goinception 备份 SSL问题

### ISSUE THREAD

**Issue by CrazyCry** [hanchuanchuan/goInception#342]
**描述**
我的mysql数据库都开启了ssl。参考，如下地址，做了ssl相关修改。关于第二个issue中的解决办法，我看1.2.4中说解决了，但是我联系到了提issue的本人，他实际没有解决，只是关闭了服务器端的ssl认证。

https://github.com/hhyo/Archery/issues/988
https://github.com/hanchuanchuan/goInception/issues/285

查询，检查sql语句没问题。
如果提交工单，选择备份，就提示SSL required，如果提交工单选择不备份，就可以正常连接到开启了ssl的数据库去执行

**环境**
goinception：1.2.4
archery：1.8.1

**参数**

**报错**
```
time="2021/05/17 13:05:04.522" level=error msg="con:3 con:3 Error 9002: SSL connection is required. Please specify SSL options and retry.\x00" file=session_inception.go func=parseOptions line=2067
time="2021/05/17 13:05:04.522" level=info msg="[GENERAL_LOG] con:3 user:root@192.168.64.3 sql:/*--user='myuser';--password='*****';--host='my.mysql.com';--port=3306;--execute=1;--ignore-warnings=1;--backup=1;--sleep=200;--sleep_rows=100;--real_row_count=1;--ssl=REQUIRED;--ssl-ca=/my.pem;*/                             inception_magic_start;                                                          use `info`;                             -- 请在此输入SQL，以分号结尾，仅支持DML和DDL语句，查询语句请使用SQL查询功能。  update info set size = '2032' where id = 1132;                             inception_magic_commit;" file=session.go func=logQuery line=1599
```

**Comment by hanchuanchuan** [comment]
[文档](https://hanchuanchuan.github.io/goInception/params.html)中有参数可以启用ssl支持。

**Comment by CrazyCry** [comment]
您好，
我尝试配置了以下三种组合，都没办法执行备份。
--ssl=REQUIRED;
--ssl=REQUIRED;--ssl-ca=/my.pem;
--ssl=verify_ca;--ssl-ca=/my.pem;

**Comment by hanchuanchuan** [comment]
方便提供一下MySQL版本以及其开启SSL的相关配置吗，另外记得使用最近的goinception版本。

**Comment by CrazyCry** [comment]
mysql 5.7
ssl: azure 页面上打开了强制SSL的选项
goinception，用的最新的1.2.4
![image](https://user-images.githubusercontent.com/15623287/118773856-c810c400-b8b7-11eb-9371-9c1339178c96.png)

**Comment by dongwanyang** [comment]
> 您好， 我尝试配置了以下三种组合，都没办法执行备份。 --ssl=REQUIRED; --ssl=REQUIRED;--ssl-ca=/my.pem; --ssl=verify_ca;--ssl-ca=/my.pem;

Hi，打扰了，最后您解决了吗

**Comment by dongwanyang** [comment]
我的数据库也是有同样的问题，不知道在哪块添加ssl参数可以解决这个问题？
