### ISSUE TITLE
docker 启动方式

### ISSUE THREAD

**Issue by WuhuGoldPilot** [hanchuanchuan/goInception#343]
**描述您想要的功能：**
请问docker如何启动？docker hub和readme文档都没有docker的启动方式

![image](https://user-images.githubusercontent.com/32405381/118454374-e0070d00-b72a-11eb-94dc-462dcaf2ec14.png)

**Comment by qq290070744** [comment]
docker run --name goinception -p 4000:4000 -e TZ=Asia/Shanghai -v /data/goinception/config.toml:/etc/config.toml   -d  hanchuanchuan/goinception

**Comment by WuhuGoldPilot** [comment]
> docker run --name goinception -p 4000:4000 -e TZ=Asia/Shanghai -v /data/goinception/config.toml:/etc/config.toml -d hanchuanchuan/goinception

@qq290070744 感谢
