### ISSUE TITLE
max_update_rows错误告警

### ISSUE THREAD

**Issue by wins1978** [hanchuanchuan/goInception#344]
**描述**
表中有21974行数据，执行脚本校验时
update table_1 set privacyName='xxx' where  eventTypeId = 20011;
实际行数是298行，结果却提示：
Update(21760 rows) more than 5000 rows.
1、如果将条件eventTypeId = 20011 改为id < 300不会报错
2、如果将条件改为任何其他列，都会报错

**重现**
创建一个行数超过2万行的表，用非id字段查询

**环境**
 - 数据库: [mysql]
 - 版本: 
5.7.17-11-V2.0R541D002-20200219-2204-log

**Comment by hanchuanchuan** [comment]
功能没有问题。出现该问题的原因是执行计划不准确，受影响行数的结果由`explian`获取。

调用选项 `real_row_count` 可以设置是否通过count(*)获取真正的受影响行数，默认为`false`，需注意该配置可能会影响数据库，特别是where条件不走索引时。

相关issue: #53
