### ISSUE TITLE
是否可以对一些高危sql做标记

### ISSUE THREAD

**Issue by sona-yuan** [hanchuanchuan/goInception#345]
**描述您想要的功能：**
对于alter drop的相关操作，可能对线上业务产生影响的高危sql做审核提示呢，比如删除索引，删除字段等操作

**描述您考虑过的解决/替代方案：**
可以类似enable_change_column这个参数，加一个enable_alter_drop，check 登记可以默认为1

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
`AlTER TABLE`操作会显示预估的受影响行数(通过`SHOW TABLE STATUS`获取)，可通过影响行数相关审核项替代。

**Comment by sona-yuan** [comment]
> `AlTER TABLE`操作会显示预估的受影响行数(通过`SHOW TABLE STATUS`获取)，可通过影响行数相关审核项替代。

影响行数在开启osc之后，关心的就是在业务低峰期执行。但是 drop  index和drop column 是会影响业务的。可以和drop table  drop database类似加一个审核限制
