### ISSUE TITLE
Invalid default value for column 'a_bit_field'

### ISSUE THREAD

**Issue by Arrowarcher** [hanchuanchuan/goInception#346]
**描述**
创建表时某个字段使用bit类型，默认值设置为NULL，会报错
```mysql
CREATE TABLE test.test_bit  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `a_bit_field` bit(8) DEFAULT NULL COMMENT 'xxxxxx',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;
```
报错：
(2, 'CHECKED', 2, 'Audit Completed', "Invalid default value for column 'a_bit_field'.", "CREATE TABLE test_autodb_t2.test_bit  (\n  `id` bigint(20) NOT NULL AUTO_INCREMENT,\n  `a_bit_field` bit(8) DEFAULT NULL COMMENT 'xxxxxx',\n  PRIMARY KEY (`id`)\n)", 0, '0_0_00000001', None, '0', None, '0')

**Comment by hanchuanchuan** [comment]
已修复，可更新到`v1.2.4-72`版本后重试。
