### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by WuhuGoldPilot** [hanchuanchuan/goInception#347]
**描述**
请问启动时报了这个是什么原因，我只修改了默认的config文件的：
backup_host = "xxx"
backup_port = xx
backup_user = "xx"
backup_password = "xxx"
这几个信息

![image](https://user-images.githubusercontent.com/32405381/119454278-f59fb680-bd6a-11eb-9ff6-e3f287201d3b.png)

**环境**
 - 数据库: [mysql]
 - 版本: [5.7.21]

**Comment by WuhuGoldPilot** [comment]
![image](https://user-images.githubusercontent.com/32405381/119475926-2a6a3880-bd80-11eb-962d-a03102469725.png)
这是正常的吗？

**Comment by hanchuanchuan** [comment]
没有error不就成功了

**Comment by hanchuanchuan** [comment]
像第一个资源不足的问题重试即可。
