### ISSUE TITLE
自定义审核级别只有默认的59个可以配置吗？

### ISSUE THREAD

**Issue by xuxygo** [hanchuanchuan/goInception#348]
**描述您想要的功能：**
1. 审核选项有150多个，审核级别设置有59个。假如我要求对在审核级别中没有的审核选项去自定义审核级别，这个是无法实现的吗？有没有折中方法可以替代哈？
2. 审核级别中的desc 是否可以修改？

**描述您考虑过的解决/替代方案：**
例如: 审核选项 check_primary_key 开启，我要所有的创建表都要有主键，所以想要设置审核级别为error，尝试使用inception set level er_check_primary_key = 2; 报错无效参数

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
审核选项和审核级别并非一一对应的，可能会有遗漏。
部分审核选项在开启时直接就是error级别(可能涉及生产环境安全的操作)。

**Comment by xuxygo** [comment]
OK
