### ISSUE TITLE
对于包含 ;\n的检测

### ISSUE THREAD

**Issue by itmeryn** [hanchuanchuan/goInception#349]
**描述**
正常的sql
<img width="878" alt="wecom-temp-4b90a11b907408d9905ab9d1da9e5f84" src="https://user-images.githubusercontent.com/18156931/120439237-df21dc80-c3b4-11eb-9090-7a7b2e2a3750.png">

**重现**
对于 包含  ;\n 这样的sql goinception检测是不能通过的 直接会在;后边截取为一行

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
分号是内部解析的分隔符，对单引号做了特殊处理，可以将双引号换成单引号来解决这个问题。
