### ISSUE TITLE
怎么配置gh-ost的max-load 和 critical-load

### ISSUE THREAD

**Issue by kobyt2** [hanchuanchuan/goInception#350]
**执行变更的时候报错：**
我在执行变更的时候报错 Execute: critical-load met: Threads_running=85, >=80

我看官方文档的参数里面好像没有设置这个两个参数变量的值，请问有什么办法控制吗？
mysql> inception show variables like '%critical%';
+---------------------------------------+-------+
| Variable_name                         | Value |
+---------------------------------------+-------+
| osc_critical_thread_running           | 80    |
| osc_critical_thread_connected         | 1000  |
| ghost_critical_load_interval_millis   | 0     |
| ghost_critical_load_hibernate_seconds | 0     |
+---------------------------------------+-------+
4 rows in set (0.00 sec)

**Comment by kobyt2** [comment]
mysql> inception show variables like '%load%';
+---------------------------------------+-------+
| Variable_name                         | Value |
+---------------------------------------+-------+
| ghost_critical_load_interval_millis   | 0     |
| ghost_critical_load_hibernate_seconds | 0     |
+---------------------------------------+-------+
2 rows in set (0.00 sec)

**Comment by hanchuanchuan** [comment]
请参阅文档说明
https://hanchuanchuan.github.io/goInception/ghost.html
如下是`config.toml`说明
https://hanchuanchuan.github.io/goInception/config.html
