### ISSUE TITLE
视图 union 语法解析问题

### ISSUE THREAD

**Issue by Graywd** [hanchuanchuan/goInception#351]
**描述**
对问题简单清晰的描述

设置支持视图参数后， 不支持 view 的 union 语法， tidb 在 3.06 才支持的 union (https://www.codetd.com/en/article/8055648)，
当前 goinception 使用的是 tidb 哪个版本？？

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数
enable_use_view

**Comment by hanchuanchuan** [comment]
该问题已修复，语法解析器由于自定义内容较多，所以和tidb的解析器版本不相关。
请下载`v1.2.4-73`版本后重试。
