### ISSUE TITLE
对于阿里云RDS for MySQL上的无主键表无法进行数据备份

### ISSUE THREAD

**Issue by xiaozhute** [hanchuanchuan/goInception#352]
**描述** 
> 阿里云RDS FOR MySQL,对于无主键的表，无论是 insert、update、delete ，使用 --backup=1 无法生成对应的回滚语句，也就是binlog没被读取到的样子。对于有主键的表可正常生成回滚语句，ddl语句回滚句也可正常生成。

**重现**
```sql
-- 创建无主键表
create table no_primary(id int,va varchar(10));

-- 使用goInception执行插入语句
insert into no_primary values (1,'a');

-- 查看备份库，表中没有对应的回滚语句产生
```
**环境**
 - 数据库: [阿里云RDS for MySQL]
 - 版本: [例如 5.7.32]
 - goInception 版本：[1.2.24-72]
**参数**
默认参数

**Comment by xiaozhute** [comment]
e

**Comment by hanchuanchuan** [comment]
没有测试RDS的binlog event是什么格式的, 在社区版的MySQL无主键时是可以备份的, 建议添加主键, 无主键场景比较少.
