### ISSUE TITLE
mysq8.0.18以上版本，无法备份sql

### ISSUE THREAD

**Issue by sislcb** [hanchuanchuan/goInception#354]
**描述**
mysql8.0.18版本，binlog格式修改了，目前无法备份了。

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql]
 - 版本: [例如 8.0.18]

**参数**
可能与问题相关的设置参数

**Comment by xiaozhute** [comment]
> 我测试了下   8.0.24  是可以的啊
* goInception 版本：1.2.4-72
* MySQL 8.0.24 社区版

**Comment by WhaleKids** [comment]
我也是mysql8备份报错
Backup: invalid sequence 8 != 1.
暂时还没有找到原因
