### ISSUE TITLE
ddl是否存在指纹检测结果缓存

### ISSUE THREAD

**Issue by itmeryn** [hanchuanchuan/goInception#356]
**描述**
![image](https://user-images.githubusercontent.com/18156931/122890977-bd45c500-d376-11eb-8de7-f1e5a680d238.png)
如图所示 对于同一个数据库的操作 第二条成功执行 第三条的检测结果是一直提示 (之前配置错误，执行失败过)

修改错误sql 语句（修改的增加字段的名字） 后尝试执行 可以成功执行

推测  ddl是否存在指纹检测结果缓存

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
DDL并不存在什么检测缓存, 这个问题有点不清楚, 建议看看缺少什么权限,加上即可.
另外, 审核信息中,如果前缀是`Execute:`,表示这个错误是真实发送到远端数据库后返回的报错.
