### ISSUE TITLE
现在审核检查并不支持注释，有考虑增加这个功能吗？

### ISSUE THREAD

**Issue by WuhuGoldPilot** [hanchuanchuan/goInception#358]
**描述**
现在审核检查并不支持注释，出现注释的时候会不支持语法，还会分割语句错误，导致语句丢失

![image](https://user-images.githubusercontent.com/32405381/123759926-f50eb880-d8f2-11eb-83c7-bc4a9461d8a0.png)

**Comment by hanchuanchuan** [comment]
mysqldump工具导出的SQL语句中会包含一些特定语法的SET命令, 这些命令是有实际含义的, 当前需要手动移除,不支持自动忽略.
其他的普通注释是支持的.
