### ISSUE TITLE
可以支持字段类型修改吗？

### ISSUE THREAD

**Issue by IT-xiaoge** [hanchuanchuan/goInception#36]
线上用goinception做审核，在提交修改列类型时报错：
Error Type conversion warning for column 'table_name' bigint(20) unsigned -> varchar(64)

我们现在有参数支持修改字段的类型吗？

**Comment by hanchuanchuan** [comment]
可以设置参数 `check_column_type_change` 为`false`，关闭字段类型变更检查。
