### ISSUE TITLE
sql审核可以多线程嘛

### ISSUE THREAD

**Issue by sona-yuan** [hanchuanchuan/goInception#362]
**描述**
对于一个事务里面有上万条sql，进行sql审核时，审核时长较久，是否可以用更多线程

**重现**
上万条update  sql，一个事务里提交审核，耗时非常久，5W条差不多20分钟

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
不可以的,原因是后面的审核会基于前面的审核结果,存在逻辑关联的. 比如添加字段后执行insert/update之类的有序逻辑.

建议如果是多表的话,可以拆分一下,给SQL条数添加一个上限.

另外5w条的话审核用不了那么久的,goinception和远程数据库跨网络了吗?
