### ISSUE TITLE
是否可以将库名解析出来后返回出来

### ISSUE THREAD

**Issue by xiaozhute** [hanchuanchuan/goInception#365]
**描述您想要的功能：**
想要将权限控制到库级别，能否在 check 的时候将解析到的`库名称`返回出来用于判断，例如如下语句，能否返回添加的前缀库的名称 db1,db2
```sql
use dbtest;
insert into db1.testa valuse (1,1);
insert into db2.testa values(2,2);
insert into testa values(3,3);
```
由于创建的MySQL用户有这3个库的权限，因此切换到dbtest库后还能执行所有语句。

基于goInception进行二次开发的话，若能进行库判断的话，可判断执行操作的用户是否拥有这三个库的权限，能将权限控制到库粒度，或者是否有规则限制无法使用前缀库名

**Comment by hanchuanchuan** [comment]
暂无计划把库名通过审核的方式返回(如果需要该功能需要fork后修改源码实现)
后续会通过扩展脱敏功能来返回DML操作涉及的库/表 ( #355 ).
