### ISSUE TITLE
关于新增二次开发的审核规则描述

### ISSUE THREAD

**Issue by xu-yuchen** [hanchuanchuan/goInception#366]
**描述您想要的功能：**
goInception目前已经实现了多种mysql审核规则，但是每个公司可能有自己独有的需求，请问我如果想要新增属于自己的审核规则，应该在源码的哪些地方做出修改呢？
目前我看到可能和sql审核相关的文件为config.go, congifg.toml, errors.go, sessions_inception.go，但是没有详细的介绍。

**Comment by hanchuanchuan** [comment]
有一个添加审核选项的例子以供参考(#175 ).
如果是通用规则的话,可以提交PR来合并到主分支(可通过添加新的审核选项来启用新规则).
