### ISSUE TITLE
default 类型解析错误

### ISSUE THREAD

**Issue by niumanniu** [hanchuanchuan/goInception#369]
**描述**
datetime(6) default current_timestamp 语法是错误，没有审核出来。
正确的写法应该是datetime(6) default current_timestamp(6)

**重现**
create table t1(id int primary key,c1 int,rep_time datetime(6) DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6));

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
该问题已优化.请升级到[`v1.2.4-95`](https://github.com/hanchuanchuan/goInception/releases)版本后重试.
