### ISSUE TITLE
关于goinception后端返回数据问题

### ISSUE THREAD

**Issue by xu-yuchen** [hanchuanchuan/goInception#371]
**描述您想要的功能：**
您好，小白想请教一下关于goinception后端返回值归属问题。
在参考使用文档当中调用python脚本执行sql语句之后，终端得到的结果集是由连接的数据库执行产生的吗？
还是说goinception启动之后处于监听4000端口状态，检测到有特定sql语句之后，再由后端处于监听状态的goinception处理，并返回结果集？

**Comment by hanchuanchuan** [comment]
你可以将goinception理解为一个独立的MySQL服务,只是不存储数据而已.
