### ISSUE TITLE
goInception v.1.2.4 check_primary_key = true并不能阻止提交，只是发出警告

### ISSUE THREAD

**Issue by wineejam** [hanchuanchuan/goInception#372]
**描述**
![image](https://user-images.githubusercontent.com/8789004/128280358-da9bf372-8f15-49b6-8312-554091a6b578.png)
goInception v.1.2.4 在 config.toml 中设置了check_primary_key = true，但是实际上不能限制提交不带主键的建表SQL
![image](https://user-images.githubusercontent.com/8789004/128280504-df7fc903-449b-4674-a5e5-be45622927fc.png)

**重现**
使用以下SQL建表
CREATE TABLE wh_logrecord (
logrecord_id int(11) NOT NULL ,
user_name varchar(100) default NULL,
operation_time datetime default NULL,
logrecord_operation varchar(100) default NULL,
) comment 'test'

审核状态为 warning 
审核信息为 Set a primary key for table 'wh_logrecord'.
按变量文档中说明，应该是报错，不能提交
https://hanchuanchuan.github.io/goInception/zh/options.html#variables列表

<html>
<body>

check_primary_key | false | true,false | 建表时，如果没有主键，则报错
-- | -- | -- | --

</body>
</html>

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.34]
 - goInception v.1.2.4

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
请查看 [params](https://hanchuanchuan.github.io/goInception/params.html) 文档的 `ignore_warnings` 设置

**Comment by hanchuanchuan** [comment]
请查看 [params](https://hanchuanchuan.github.io/goInception/params.html) 文档的 `ignore_warnings` 设置

**Comment by wineejam** [comment]
er_table_must_have_pk = 2
已解决，是需要修改这个级别
