### ISSUE TITLE
tidb检测影响行数可能超出阈值

### ISSUE THREAD

**Issue by Nanrer** [hanchuanchuan/goInception#375]
**描述**
tidb影响行数java 报错, java.sql.SQLDataException: Invalid integer format for value '2709787456'

**重现**
1,检测行数超过java  Integer.MAX_VALUE 就报错(或者修改goinception的影响行数返回给java查询结果)

**环境**
 - 数据库: tidb
 - 版本: 任何版本

**参数**
无

原因: 
![image](https://user-images.githubusercontent.com/21291978/129841080-3b5cdfa4-7764-4c17-b999-2ce3f10cc589.png)
影响行数的类型应该是 mysql.TypeLonglong 才能存下

**Comment by hanchuanchuan** [comment]
是的,当数据量过大时会超过int32上限,稍后会修复该问题.

**Comment by hanchuanchuan** [comment]
该问题已修复. 请下载[v1.2.4-99](https://github.com/hanchuanchuan/goInception/releases)版本后重试.
