### ISSUE TITLE
复杂密码可能导致无法审核

### ISSUE THREAD

**Issue by xiaozhute** [hanchuanchuan/goInception#376]
**描述**
MySQL 端若使用复杂密码，特别是包含 $ 符号的密码，会导致 goinception 在check时候就无法获取到对应的值，类似整个在后面审核的时候出现断层了，导致报错如下：”不正确的数据源信息（主机名为空，端口为0，用户名为空）“
无法在goinception 的配置中将密码用 引号 包起来，写了引号后执行报错。
**重现**
将MySQL密码改为： &w1@3$8SR7pAQen@

**环境**
 - 数据库: [mysql]
 - 版本: [ 5.7.21]

**Comment by hanchuanchuan** [comment]
已测试,没有问题. 
例如: `/*--user=test;--password='&w1@3$8SR7pAQen@';--host=127.0.0.1;--check=1;--port=3306;ignore-warnings=1;*/`
