### ISSUE TITLE
是否支持varchar长度审核

### ISSUE THREAD

**Issue by hexiaohui003** [hanchuanchuan/goInception#377]
**描述您想要的功能：**
生产已经禁用了text,blob类型，但是目前无法限制varchar类型长度

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by pen1120** [comment]
> 该需求之后将会支持。

想从这个issue开始加入你们的开源项目，请问加入有什么标准吗？

**Comment by hanchuanchuan** [comment]
非常欢迎！[CONTRIBUTING步骤](https://github.com/hanchuanchuan/goInception/blob/master/CONTRIBUTING.md)
