### ISSUE TITLE
索引前缀提示（中文）问题

### ISSUE THREAD

**Issue by MagMongoing** [hanchuanchuan/goInception#380]
**描述**
索引前缀审核提示： 索引 'channel' 需要指定'test_table'前缀(表'idx_').

**重现**
新建普通索引即可重现

**环境**
审核提示选择中文

**参数**
- session/errors.go:

> ER_INDEX_NAME_IDX_PREFIX:  
> 英文提示： "Index '%s' in table '%s' need '%s' prefix." 
> 中文提示： "索引 '%s' 需要指定'%s'前缀(表'%s')."

中英文习惯问题， 传参顺序一致时，会导致表名和前缀的显示不一致

简单修复： 中文提示修改为:
>  "索引 '%s' (表'%s') 需要指定'%s'前缀"

**Comment by hanchuanchuan** [comment]
好的，感谢提醒，下个小版本会进行修复。
