### ISSUE TITLE
gh-ost 的ghost_initially_drop_socket_file 参数不生效

### ISSUE THREAD

**Issue by myocm** [hanchuanchuan/goInception#382]
**描述**
gh-ost 的 ghost_initially_drop_socket_file 参数不生效

**重现**
使用 gh-ost 修改表结构过程中，终止掉 osc进程
此时数据库有 
_表名_ghc
_表名_gho
两个临时表
和
gh-ost.数据库.表名.sock 
socket 文件

手动删除 
_表名_ghc
_表名_gho
两个临时表
保留  gh-ost.数据库.表名.sock  socket 文件

查看 ghost 配置
inception show variables like 'ghost%';
| ghost_initially_drop_socket_file       | true   |

重新执行表结构修改
报  listen unix socket file already in use. 错误

手工使用官方gh-ost ，而不使用 goInception 执行表结构修改时，可以删除socket文件，正常执行。

**环境**
 - 数据库: mysql 5.7
 - 版本:  5.7.22-22-log
 - goInception 版本： https://github.com/hanchuanchuan/goInception/releases/download/v1.2.4/goInception-linux-v1.2.4.tar.gz  和 从最新源码编译的版本

**参数**
ghost_initially_drop_socket_file

**Comment by hanchuanchuan** [comment]
该问题已修复，稍后发布新版本。

**Comment by dbadylan** [comment]
这个问题应该还是存在：

<img width="710" alt="企业微信20220523-230446@2x" src="https://user-images.githubusercontent.com/46683377/169849589-95dbfadc-df57-4764-aaa6-f9560dbd5897.png">

<img width="560" alt="企业微信20220523-230136@2x" src="https://user-images.githubusercontent.com/46683377/169849633-f80add8f-08ca-4e90-8a90-f992960b974d.png">
