### ISSUE TITLE
希望可以兼容 inception 的注释参数

### ISSUE THREAD

**Issue by sleepingfatty** [hanchuanchuan/goInception#388]
最近要做 goInception 平滑替换 inception 的操作，目前想 goInception 的灰度上线，发现 goInception 不完全兼容 inception 的注释。

平台层封装的 inception 审核和执行的注释如下
/*--user=xxx;--password=xxx;--host=127.0.0.1;--port=3306;--enable-check;*/
/*--user=xxx;--password=xxx;--host=127.0.0.1;--port=3306;--execute;*/

可以将 --enable-check  替换成 --check=1，--execute  替换成--execute=1，这样 inception 和 goInception 都可以识别，但是指定 --execute inception 可以执行加备份，goInception 仅执行不备份，希望可以兼容 inception 的注释参数并相应的实现其功能。

另外注释中不可有空格和换行符，大佬如果有精力的话也希望在解析参数的时候一并处理。

**Comment by hanchuanchuan** [comment]
备份功能有对应的参数,设置即可,两者应该是一致的.至于空格和换行符,由于采用的正则解析,不太方便过于复杂. 另外该注释通常是自行开发程序实现,这些问题应该可以避免.
