### ISSUE TITLE
阿里云rds执行ddl调用gh-ost报错

### ISSUE THREAD

**Issue by luckycakesun** [hanchuanchuan/goInception#39]
**描述**
goinception-v0.8.2执行如下ddl报错如下：
alter  table  saas_system_config  ADD  (
`conventional_curing_cycle1`  int  (  3  )  NOT  NULL  DEFAULT  '30'  COMMENT  '常规养护周期  单位天',
  `critical_curing_period1`  int  (  3  )  NOT  NULL  DEFAULT  '15'  COMMENT  '重点养护周期  单位天',
  `advance_warning_curing1`  int  (  3  )  NOT  NULL  DEFAULT  '3'  COMMENT  '养护提前预警天数',
  `routine_inspection_cycle1`  int  (  3  )  NOT  NULL  DEFAULT  '30'  COMMENT  '常规检查周期  单位天',
  `critical_inspection_cycle1`  int  (  3  )  NOT  NULL  DEFAULT  '15'  COMMENT  '重点检查周期  单位天',
  `advance_warning_inspection1`  int  (  3)  NOT  NULL  DEFAULT  '3'  COMMENT  '检查提前预警天数',
  early_warning_days1  int  (  3)  NOT  NULL  DEFAULT  '5'  COMMENT  '近效期提前预警天数  默认5天')
![image](https://user-images.githubusercontent.com/50308927/58796392-bcc32000-862f-11e9-9ced-8c2eb2f32f2c.png)

**重现**
模拟重现的步骤

**环境**
 - 数据库: 阿里云rds mysql
 - 版本: 5.7

**参数**
可能与问题相关的设置参数
![image](https://user-images.githubusercontent.com/50308927/58796807-e0d33100-8630-11e9-9940-507d5109464f.png)

**Comment by hanchuanchuan** [comment]
原因如下:
![image](https://user-images.githubusercontent.com/18544383/58847620-3b62a080-86b6-11e9-89fe-c640e7241b84.png)

现已更新,在使用阿里云RDS数据库时,自动设置assume-master-host参数
https://github.com/hanchuanchuan/goInception/commit/fcfc4f92a2aabed60c909abf14e0fd3d5ab2c025
