### ISSUE TITLE
goinception 启动报错（非docker部署）

### ISSUE THREAD

**Issue by hongfei0114** [hanchuanchuan/goInception#390]
**描述**

启动命令：  goInception -config=/etc/goinception/config.toml
启动报错：
file missing
github.com/pingcap/errors.AddStack
	/Users/hanchuanchuan/coding/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/errors.Trace
	/Users/hanchuanchuan/coding/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12
github.com/hanchuanchuan/goInception/store/mockstore/mocktikv.NewMVCCLevelDB
	/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/store/mockstore/mocktikv/mvcc_leveldb.go:119
github.com/hanchuanchuan/goInception/store/mockstore/mocktikv.NewTiKVAndPDClient
	/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/store/mockstore/mocktikv/mock.go:29
github.com/hanchuanchuan/goInception/store/mockstore.NewMockTikvStore
	/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/store/mockstore/tikv.go:105
github.com/hanchuanchuan/goInception/store/mockstore.MockDriver.Open
	/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/store/mockstore/tikv.go:46
github.com/hanchuanchuan/goInception/session.newStoreWithRetry.func1
	/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/session/tidb.go:263
github.com/hanchuanchuan/goInception/util.RunWithRetry
	/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/util/misc.go:39
github.com/hanchuanchuan/goInception/session.newStoreWithRetry
	/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/session/tidb.go:261
github.com/hanchuanchuan/goInception/session.NewStore
	/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/session/tidb.go:245
main.createStoreAndDomain
	/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/tidb-server/main.go:154
main.main
	/Users/hanchuanchuan/coding/github.com/hanchuanchuan/goInception/tidb-server/main.go:128
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373

**环境**
cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

goInception -V
Release Version: v1.2.3-52-gfeccee1
Git Commit Hash: feccee1b80ad850ae96c7507b4937430d037f85f
Git Branch: master
UTC Build Time: 2020-11-25 20:56:35
GoVersion: go version go1.14.3 darwin/amd64

**Comment by shengminjie** [comment]
最终goInception使用就是一个二进制文件哦，检查是否把源码弄混了呢？

**Comment by hanchuanchuan** [comment]
清理`/tmp/tidb`目录后重试即可, 这个错误可能会在非正常关闭服务器时出现.
