### ISSUE TITLE
修改已有列，列名为关键字时，关键字检查 bug

### ISSUE THREAD

**Issue by Graywd** [hanchuanchuan/goInception#392]
**描述**
修改已有的列信息，如果列名是关键字，对于已有列不应该检查列名，但实际会检查

**重现**
![image](https://user-images.githubusercontent.com/11515336/135199996-4c3b8390-6181-4993-becd-c436df1e7dad.png)

**Comment by hanchuanchuan** [comment]
好的, 稍后会优化该逻辑.
