### ISSUE TITLE
开窗函数支持

### ISSUE THREAD

**Issue by xionglihdfs** [hanchuanchuan/goInception#393]
**描述**
在SQL语句有 
row_number() over(partition by id) 时不支持语法书解析

**重现**
模拟重现的步骤
CREATE TABLE test
(
	a INT,
	b INT,
	c CHAR
);

INSERT INTO test VALUES(1,3,'E');
INSERT INTO test VALUES(2,4,'A');
INSERT INTO test VALUES(3,2,'D');
INSERT INTO test VALUES(3,5,'B');
INSERT INTO test VALUES(4,2,'C');
INSERT INTO test VALUES(2,4,'B');

整个结果集是一个分组，以a进行排名
SELECT a,b,c,rank () OVER (ORDER BY a) ranks FROM test;

模拟器的执行结果:
mysql> SELECT a,b,c,rank () OVER (ORDER BY a) ranks FROM test;
+----------+-------+-------------+-----------------+-------------------------------------------------------------------------------------+--------------------------------------------------------+---------------+--------------+---------------+--------------+---------+-------------+
| order_id | stage | error_level | stage_status    | error_message                                                                       | sql                                                    | affected_rows | sequence     | backup_dbname | execute_time | sqlsha1 | backup_time |
+----------+-------+-------------+-----------------+-------------------------------------------------------------------------------------+--------------------------------------------------------+---------------+--------------+---------------+--------------+---------+-------------+
|        1 | RERUN |           2 | Audit Completed | You have an error in your SQL syntax, near '(ORDER BY a) ranks FROM test' at line 1 | SELECT a,b,c,rank () OVER (ORDER BY a) ranks FROM test |             0 | 0_0_00000000 | NULL          | 0            | NULL    | 0           |
+----------+-------+-------------+-----------------+-------------------------------------------------------------------------------------+--------------------------------------------------------+---------------+--------------+---------------+--------------+---------+-------------+
1 row in set (0.00 sec)

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 tidb 5.2.1]

**参数**
可能与问题相关的设置参数
tidb无特殊配置参数. 此SQL在MySQL 8.0.26上运行 和 直连 tidb 5.2.1 上执行通过.

**Comment by xionglihdfs** [comment]
大神您好, 能用 github.com/pingcap/parser 代码再重构下吗? 需要有一套模拟器配和archery认证体系用下,
archery地址 https://github.com/hhyo/Archery , 这套开窗函数 rank () OVER (ORDER BY a) 使用不了, 提示SQL语法错误.

**Comment by wineejam** [comment]
请问这个在哪个版本恢复了？v1.2.5同样有这个问题

**Comment by Mike-Ge** [comment]
同样咨询这个问题，什么时间可以支持窗口函数

**Comment by chaigang0** [comment]
同样咨询这个问题，什么时间可以支持窗口函数
