### ISSUE TITLE
set变量后执行select提示不支持的语法类型

### ISSUE THREAD

**Issue by JoesWu** [hanchuanchuan/goInception#395]
**描述**
set变量后执行select调用变量提示不支持的语法类型。

**重现**
set @a = 'abc';
select * from abc where a=@a;

((1, 'CHECKED', 0, 'Audit Completed', None, 'set @a = "abc"', 0, '0_0_00000000', None, '0', None, '0'), (2, 'CHECKED', 0, 'Audit Completed', '不支持的语法类型.', 'select * from abc where a=@a', 0, '0_0_00000001', None, '0', None, '0'))

**环境**
 - 数据库: mysql
 - 版本: 5.7

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
不支持该类语法。

**Comment by persistanceTube** [comment]
请问后续有支持的计划吗？
