### ISSUE TITLE
go build一直报错

### ISSUE THREAD

**Issue by halodba** [hanchuanchuan/goInception#396]
(base) [root@test_5_186 monitor]# git clone https://github.com/hanchuanchuan/goInception
正克隆到 'goInception'...
remote: Enumerating objects: 12093, done.
remote: Counting objects: 100% (773/773), done.
remote: Compressing objects: 100% (459/459), done.
remote: Total 12093 (delta 407), reused 579 (delta 303), pack-reused 11320
接收对象中: 100% (12093/12093), 19.19 MiB | 7.04 MiB/s, done.
处理 delta 中: 100% (6680/6680), done.
(base) [root@test_5_186 monitor]# cd goInception
(base) [root@test_5_186 goInception]# make parser
GO111MODULE=on go build -o bin/goyacc parser/goyacc/main.go parser/goyacc/format_yacc.go
bin/goyacc -o parser/parser.go -p yy -t Parser parser/parser.y
Parse table entries: 885102 of 2213747, x 16 bits == 1770204 bytes
SUCCESS!
bin/goyacc -o parser/hintparser.go -p yyhint -t hintParser parser/hintparser.y
Parse table entries: 13069 of 24128, x 16 bits == 26138 bytes
SUCCESS!
(base) [root@test_5_186 goInception]# go build -o goInception tidb-server/main.go
go: downloading github.com/coreos/etcd v3.3.10+incompatible
go: downloading github.com/pingcap/pd v2.1.0+incompatible
go: downloading github.com/CorgiMan/json2 v0.0.0-20150213135156-e72957aba209
go: downloading github.com/go-sql-driver/mysql v1.4.1-0.20191022112324-6ea7374bc1b0
go: downloading github.com/hanchuanchuan/gh-ost v1.0.49-0.20210117111015-ca873c0b5ca6
go: downloading github.com/hanchuanchuan/go-mysql v0.0.0-20200114082439-6d0d8d3a982e
go: downloading github.com/imroc/req v0.2.3
go: downloading github.com/jinzhu/gorm v1.9.2
verifying github.com/coreos/etcd@v3.3.10+incompatible: checksum mismatch
        downloaded: h1:jFneRYjIvLMLhDLCzuTuU4rSJUjRplcJQ7pD7MnhC04=
        go.sum:     h1:KjVWqrZ5U0wa3CxY2AxlH6/UcB+PK2td1DcsYhA+HRs=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by halodba** [comment]
尝试了删掉go.sum文件，
重新go build，最后如下报错：
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
# github.com/hanchuanchuan/goInception/parser
parser/hintparser.go:1199:1: invalid UTF-8 encoding
parser/parser.go:11936:1: invalid UTF-8 encoding

**Comment by halodba** [comment]
(base) [root@test_5_186 goInception]# make parser 
make: 对“parser”无需做任何事。
(base) [root@test_5_186 goInception]#

**Comment by hanchuanchuan** [comment]
报错的文件删除后重试`make parser`
如`parser/parser.go`等

**Comment by halodba** [comment]
(base) [root@test_5_186 parser]# rm -rf parser.go 
(base) [root@test_5_186 parser]# rm -rf hintparser.go
(base) [root@test_5_186 parser]# cd ..
(base) [root@test_5_186 goInception]# make parser
bin/goyacc -o parser/parser.go -p yy -t Parser parser/parser.y
Parse table entries: 885102 of 2213747, x 16 bits == 1770204 bytes
SUCCESS!
bin/goyacc -o parser/hintparser.go -p yyhint -t hintParser parser/hintparser.y
Parse table entries: 13069 of 24128, x 16 bits == 26138 bytes
SUCCESS!
(base) [root@test_5_186 goInception]# go build -o goInception tidb-server/main.go
session/session_masking.go:14:2: missing go.sum entry for module providing package github.com/CorgiMan/json2 (imported by github.com/hanchuanchuan/goInception/session); to add:
        go get github.com/hanchuanchuan/goInception/session
server/server.go:46:2: missing go.sum entry for module providing package github.com/blacktear23/go-proxyprotocol (imported by github.com/hanchuanchuan/goInception/server); to add:
        go get github.com/hanchuanchuan/goInception/server
ddl/ddl.go:25:2: missing go.sum entry for module providing package github.com/coreos/etcd/clientv3 (imported by github.com/hanchuanchuan/goInception/ddl); to add:
        go get github.com/hanchuanchuan/goInception/ddl
ddl/syncer.go:26:2: missing go.sum entry for module providing package github.com/coreos/etcd/clientv3/concurrency (imported by github.com/hanchuanchuan/goInception/ddl); to add:
......
然后继续尝试还是下面的错：
(base) [root@test_5_186 goInception]# go get github.com/hanchuanchuan/goInception/session
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
# github.com/hanchuanchuan/goInception/parser
parser/hintparser.go:1199:1: invalid UTF-8 encoding
parser/parser.go:11936:1: invalid UTF-8 encoding
-----------------------------
cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)

**Comment by halodba** [comment]
(base) [root@test_5_186 goInception]# go build -o goInception tidb-server/main.go
# github.com/hanchuanchuan/goInception/parser
parser/hintparser.go:1199:1: invalid UTF-8 encoding
parser/parser.go:11936:1: invalid UTF-8 encoding
(base) [root@test_5_186 goInception]# rm -rf parser/hintparser.go 
(base) [root@test_5_186 goInception]# rm -rf parser/parser.go 
(base) [root@test_5_186 goInception]# make parser
bin/goyacc -o parser/parser.go -p yy -t Parser parser/parser.y
Parse table entries: 885102 of 2213747, x 16 bits == 1770204 bytes
SUCCESS!
bin/goyacc -o parser/hintparser.go -p yyhint -t hintParser parser/hintparser.y
Parse table entries: 13069 of 24128, x 16 bits == 26138 bytes
SUCCESS!
(base) [root@test_5_186 goInception]# go build -o goInception tidb-server/main.go
# github.com/hanchuanchuan/goInception/parser
parser/hintparser.go:1199:1: invalid UTF-8 encoding
parser/parser.go:11936:1: invalid UTF-8 encoding
(base) [root@test_5_186 goInception]# go run tidb-server/main.go
# github.com/hanchuanchuan/goInception/parser
parser/hintparser.go:1199:1: invalid UTF-8 encoding
parser/parser.go:11936:1: invalid UTF-8 encoding

**Comment by huanghuazhang** [comment]
1、go require file to be utf-8 encoded.
2、check these two file encoding:
`file -I parser/parser.go
parser/parser.go: text/plain; charset=us-ascii`

3、as the build info shows, line 1199 and 12132 is wierd，vi these two file and check these line, delete wierd characters, then everything will be ready to be build successfully
`# github.com/hanchuanchuan/goInception/parser
parser/hintparser.go:1199:1: invalid UTF-8 encoding
parser/parser.go:12132:1: invalid UTF-8 encoding`
