### ISSUE TITLE
可以设置禁用 longtext\LongBlob\MediumBlob\MediumText类型吗？

### ISSUE THREAD

**Issue by anchen418857063** [hanchuanchuan/goInception#400]
在新建/修改表字段类型时 设置如果设置了longtext\LongBlob\MediumBlob\MediumText类型，点击“SQL检测”时 能不能设置提示 error

**Comment by hanchuanchuan** [comment]
已更新 [v1.2.5-15](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.5)
新参数 `disable_types` 禁用数据库类型,多个时以逗号分隔.
(以下参数将弃用: enable_blob_type,enable_json_type,enable_enum_set_bit,enable_timestamp_type)
