### ISSUE TITLE
大批量insert或者update时能否控制执行速度

### ISSUE THREAD

**Issue by honor100** [hanchuanchuan/goInception#401]
**描述您想要的功能：大批量insert或者update时能否控制执行速度： 比如多少条sleep 几秒之类的； 或者多少条commit一次，并sleep几秒

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
查看 [调用选项](https://hanchuanchuan.github.io/goInception/zh/params.html) 页面的`sleep`和`sleep_rows`参数。

**Comment by honor100** [comment]
赞，孤陋寡闻了
