### ISSUE TITLE
pt只建立dml的触发器,ddl操作依然只生效到老表,pt过程中对同一张表禁止或者排队执行ddl

### ISSUE THREAD

**Issue by Nanrer** [hanchuanchuan/goInception#402]
**描述您想要的功能：**
pt执行的ddl过程中,禁止对于同一张表的DDL操作工单

**描述您考虑过的解决/替代方案：**
同一张表的DDL工单需要排队执行

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
当前的逻辑是同实例的同一个表会生成一样的socket文件，所以会拒绝第二个工单执行。
