### ISSUE TITLE
bug default语法审核

### ISSUE THREAD

**Issue by ocpeng** [hanchuanchuan/goInception#406]
**描述**
错误字段：update_time timestamp default null ON UPDATE CURRENT_TIMESTAMP comment "更新时间",
inception能审核出来，返回："Invalid default value for column 'update_time'."
goinception返回：pass（审核不出来这种错误的语法）

goinception v1.2.4

**Comment by hanchuanchuan** [comment]
好的，已测试，下述两种写法在MySQL 5.7时第一种是没问题的。
但在MySQL v5.6时第一种写法也会报错，稍后会添加版本判断。
```sql
create table t1(id int primary key,c1 int,
update_time timestamp default null ON UPDATE CURRENT_TIMESTAMP comment "更新时间");

create table t2(id int primary key,c1 int,
update_time timestamp not null default null ON UPDATE CURRENT_TIMESTAMP comment "更新时间");
```

**Comment by ocpeng** [comment]
首先感谢。
我再描述一下，这种错误的写法（update_time timestamp default null ON UPDATE CURRENT_TIMESTAMP comment "更新时间",）
这种错误的写法v5.6，v5.7是都会报错的：返回：ERROR 1067 (42000): Invalid default value for 'update_time'
但是inception能够审核出来；而goinception不能审核出来。
我觉得是goinception没有加入这块功能判断么？请作者再次确认

**Comment by hanchuanchuan** [comment]
这个逻辑在goinception优化了，在MySQL v5.7是允许`
update_time timestamp default null ON UPDATE CURRENT_TIMESTAMP`这种写法的，而且也是合理并建议这么做的，更新时间首次写入时是应该为空的。
inception是基于MySQL 5.6源码改造的，并且主要管理5.6版本，所以是这个审核逻辑。
goinception更多的审核逻辑是v5.7版本的。
