### ISSUE TITLE
建表时bit类型字段默认值设置 b'0' 用goInception检测语法错误，直接在数据库里执行成功

### ISSUE THREAD

**Issue by dba-ws** [hanchuanchuan/goInception#409]
**描述**
建表时bit类型字段默认值设置 b'0' 用goInception检测语法错误，直接在数据库里执行成功

**重现**
SQL：
CREATE TABLE `aaa` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '1: deleted, 0: normal',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用表';

检测错误：
line 3 column 40 near "b '0' COMMENT '1: deleted, 0: normal',
PRIMARY KEY (`Id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '应用表'"

直接在库里执行：
![image](https://user-images.githubusercontent.com/44385881/142840535-bc1cfab4-4e74-4980-b99f-410f08d3a083.png)

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.26]

**参数**
enable_enum_set_bit                     =true     //三种类型有没有单独设置开关的方法？enum确实要单独禁

**Comment by hanchuanchuan** [comment]
默认值 `b'0'`的问题在之前的版本已经修复, 请升级到最新版本重试.
类型禁用问题已经添加新的自定义方式, 稍后发布新版本.
