### ISSUE TITLE
希望添加判断数据库是否可读的开关

### ISSUE THREAD

**Issue by quanbisen** [hanchuanchuan/goInception#412]
**描述您想要的功能：**
我目前有在基于开源项目archery定制开发，支持公司内部的mycat数据库中间件，不做SQL备份。不过有一个问题，goinception每次执行的时候会判断数据库是否是read_only模式，如果mycat是读写分离模式的话，goinception可能直接返回，不执行了，参见代码
```
if s.checkIsReadOnly() { 
        s.appendErrorMessage("当前数据库为只读模式,无法执行!") 
        return 
}
```

**描述您考虑过的解决/替代方案：**
希望能在提交给goinception执行的配置中能添加是否开启数据库read_only检查，参数建议为read_only_check，谢谢。

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
即使不进行read_only的检查，SQL语句也无法执行成功吧？或者只是SELECT语句吗？

**Comment by quanbisen** [comment]
> 即使不进行read_only的检查，SQL语句也无法执行成功吧？或者只是SELECT语句吗？

执行是可以执行的，但是mycat是读写分离模式的话，select @@read_only返回的是只读模式的。mycat是不支持备份模式。

**Comment by hanchuanchuan** [comment]
版本已升级，新参数`check_read_only`，值默认为`true`，请下载[v1.2.5-11](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.5)版本后重试。

**Comment by quanbisen** [comment]
> 版本已升级，新参数`check_read_only`，值默认为`true`，请下载[v1.2.5-11](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.5)版本后重试。

您好，我看了一下更新的代码，好像这个参数是写在了配置文件的，这个配置参数可以在提交给goinception的文本中设置吗？

**Comment by quanbisen** [comment]
> 版本已升级，新参数`check_read_only`，值默认为`true`，请下载[v1.2.5-11](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.5)版本后重试。

我看了一下源码，确实是在配置文件中设置，提交给goinception的sql文本中并没有加载参数的操作，好像这个是直接交给下面的引擎执行的了。那就没必要解析它了，这个参数是goinception的设置，理论上是只放在配置文件。谢谢大佬。
