### ISSUE TITLE
max_execution_time参数无效

### ISSUE THREAD

**Issue by swords1999** [hanchuanchuan/goInception#413]
**描述**
对问题简单清晰的描述

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by swords1999** [comment]
max_execution_time只是针对select语句有用，对DML无效
max_execution_time applies as follows:

The global max_execution_time value provides the default for the session value for new connections. The session value applies to SELECT executions executed within the session that include no MAX_EXECUTION_TIME(N) optimizer hint or for which N is 0.

max_execution_time applies to read-only SELECT statements. Statements that are not read only are those that invoke a stored function that modifies data as a side effect.

max_execution_time is ignored for SELECT statements in stored programs.

**Comment by hanchuanchuan** [comment]
是的，稍后会改写这部分逻辑。
