### ISSUE TITLE
对建表语句的审核，没有指定排序规则 报错或者告警。有没有这个审核规则。

### ISSUE THREAD

**Issue by gaoqiang-0327** [hanchuanchuan/goInception#416]
**描述您想要的功能：**
审核建表语句的时候，如果没有指定COLLATE=utf8mb4_unicode_ci 则报错。

**Comment by hanchuanchuan** [comment]
文档：https://hanchuanchuan.github.io/goInception/zh/options.html
 参数 `support_collation`

**Comment by gaoqiang-0327** [comment]
support_collation这个参数的意思是指定的排序规则可以为哪些。但是建表语句如果是DEFAULT CHARSET = utf8mb4  COMMENT = '用户表',  而不是这种“DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '用户表'” ,mysql8.0如果不指定字符集的话  会默认为：CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表'

**Comment by gaoqiang-0327** [comment]
support_collation这个参数的意思是指定的排序规则可以为哪些。但是建表语句如果是DEFAULT CHARSET = utf8mb4  COMMENT = '用户表',  而不是这种“DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '用户表'” ,mysql8.0如果不指定字符集的话  会默认为：CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表'

**Comment by gaoqiang-0327** [comment]
> 文档：https://hanchuanchuan.github.io/goInception/zh/options.html 参数 `support_collation`

support_collation这个参数的意思是指定的排序规则可以为哪些。
但是建表语句如果是：DEFAULT CHARSET = utf8mb4 COMMENT = '用户表',
而不是这种“DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '用户表'” ,
mysql8.0如果不指定字符集的话 会默认为：CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表'
感觉可以有一个建表语句强制指定字符集排序的规则，如果建表语句不带排序规则 则报错，
