### ISSUE TITLE
查询语句中对于别名.* masking无法解析，query_tree为空

### ISSUE THREAD

**Issue by unknowissue** [hanchuanchuan/goInception#417]
您好
辛苦帮忙看下，是不支持么？以及后排期计划么？
还是我的使用方法有问题？
**描述**
查询语句中对于别名.* masking无法解析，query_tree为空,比如
select a.* from t1 a limit 100 
结果为
+----+--------------------------------+----------+------------+--------+
| id |           statement            | errlevel | query_tree | errmsg |
+----+--------------------------------+----------+------------+--------+
| 1  | select a.* from t1 a limit 100 |    0     |     []     |  None  |
+----+--------------------------------+----------+------------+--------+
**重现**
`python
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
import pymysql
import prettytable as pt
tb = pt.PrettyTable()
sql = '''/*--user=xx;--password=xx==;--host=xxxxx--port=3308;--masking=1;*/
                          inception_magic_start;
                          use `db1`;
                          select a.* from t1 a limit 100;
                          inception_magic_commit;'''
conn = pymysql.connect(host='127.0.0.1', user='', passwd='',
                       db='', port=4000, charset="utf8mb4")
cur = conn.cursor()
ret = cur.execute(sql)
result = cur.fetchall()
print(result)
cur.close()
conn.close()
tb.field_names = [i[0] for i in cur.description]
for row in result:
    tb.add_row(row)
print(tb)
`
**环境**
 - 数据库: mysql8
 - 版本: v1.2.5
 - 部署方式:手动部署

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
测试了没有问题，请升级到最新版本后重试。
```json
[
    {
        "index":0,
        "field":"id",
        "type":"",
        "table":"t1",
        "schema":"",
        "alias":"col1"
    },
    {
        "index":1,
        "field":"c1",
        "type":"",
        "table":"t1",
        "schema":"",
        "alias":"IFNULL(c1,id)"
    },
    {
        "index":1,
        "field":"id",
        "type":"",
        "table":"t1",
        "schema":"",
        "alias":"IFNULL(c1,id)"
    }
]
```

![image](https://user-images.githubusercontent.com/18544383/147933539-b07bf128-97d1-4e9c-849a-985d2d925b36.png)

**Comment by hanchuanchuan** [comment]
已修复。请升级到[v1.2.5-10](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.5)版本后重试。

**Comment by unknowissue** [comment]
谢谢，测试可以了。
