### ISSUE TITLE
针对docker和进程两种方式的部署，更改配置文件后，如何优雅的重启不影响业务？

### ISSUE THREAD

**Issue by mygitnote** [hanchuanchuan/goInception#419]

**Comment by hanchuanchuan** [comment]
文档: https://hanchuanchuan.github.io/goInception/zh/options.html
动态修改配置即可. 例如 `inception set check_dml_limit = true;`

**Comment by mygitnote** [comment]
> 文档: https://hanchuanchuan.github.io/goInception/zh/options.html 动态修改配置即可. 例如 `inception set check_dml_limit = true;`

这个我知道，不过这样改了重启后就失效了吧？最终还是通过配置文件比较好，如果有类似Nginx那种改配置平滑重启（-s reload）就好了

**Comment by hanchuanchuan** [comment]
暂无计划考虑reload方式重载配置文件, 通过以下几种方式已能灵活配置:

- 修改配置文件
- inception set(全局)
- inception set(会话级)
