### ISSUE TITLE
建议增加$$inception_backup_information$$ 表的 host 列长度问题

### ISSUE THREAD

**Issue by chaigang0** [hanchuanchuan/goInception#421]
**描述您想要的功能：**

![image](https://user-images.githubusercontent.com/46520672/150900063-39d2f964-2016-42e9-9b42-762cccbc3ae1.png)

在执行工单时，我们有时会遇到这个抱错，
【Data too long for column 'host' at row 1.】

排查发现是备份库下的 $$inception_backup_information$$ 表的 host 列长度问题，
host 字段的长度是varchar(64) ,我们使用的AWS数据库，有时候连接地址会超过64个字符，

当然，解决这个问题，也很简单，只修改alter table $$inception_backup_information$$ modify host varchar(128) ,加大长度就可以了，

但这并不能从解本上解决，后面添加的新实例，再次执行工单，还是可能会遇到报错问题，虽然这个报错并不影响工单正常执行。

**描述您考虑过的解决/替代方案：**

我建议修改 $$inception_backup_information$$ 建表语句，将 host varchar(64) 修改为 varchar(128)

在 inception 项目 /sql/sql_parse.cc 文件中
链接：https://github.com/hhyo/inception/blob/master/sql/sql_parse.cc
第7994行。

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
该BUG在几年前已在`goincetion`项目中修复. 
inception项目其作者已不在维护(已闭源).

**Comment by unknowissue** [comment]
> 该BUG在几年前已在`goincetion`项目中修复. inception项目其作者已不在维护(已闭源).

嗷嗷，他的意思是想把
https://github.com/hanchuanchuan/goInception/blob/e2604a3c2a4b81a701a8bde59060234988e8444c/session/session_backup.go#L255-L280
这里的buf.WriteString("host VARCHAR(64),") 该大了

**Comment by mygitnote** [comment]
> 该BUG在几年前已在`goincetion`项目中修复. inception项目其作者已不在维护(已闭源).

修复了吗？为啥我最近也遇到了
![image](https://user-images.githubusercontent.com/24616188/163546678-85ccdbe0-77da-4956-9b18-7d2bf0531363.png)

**Comment by hanchuanchuan** [comment]
我理解错了，之前修复的是生成备份库名称逻辑。
该问题已修复。现在会在连接到备份库时会获取数据库表结构来自动截取host长度。新建备份表的host列长度已调整为`varchar(128)`。已存在的备份库可自行统一修改原始列长度(新版本会根据字段长度自动截取)。
请升级到`v1.2.5-36`版本后重试。

**Comment by cslingjun** [comment]
> 我理解错了，之前修复的是生成备份库名称逻辑。 该问题已修复。现在会在连接到备份库时会获取数据库表结构来自动截取host长度。新建备份表的host列长度已调整为`varchar(128)`。已存在的备份库可自行统一修改原始列长度(新版本会根据字段长度自动截取)。 请升级到`v1.2.5-36`版本后重试。

[goInception-linux-v1.2.5-48-ga9d54fc.tar.gz](https://github.com/hanchuanchuan/goInception/releases/download/v1.2.5/goInception-linux-v1.2.5-48-ga9d54fc.tar.gz)
使用的这个版本 ，仍然有这个问题。
![image](https://user-images.githubusercontent.com/24772668/172975761-7908ad5d-c1d7-4fdf-a4b6-e7b1ddbf9d31.png)

**Comment by Urnotprepared** [comment]
`CREATE TABLE `$_$Inception_backup_information$_$` (
  `opid_time` varchar(50) NOT NULL,
  `start_binlog_file` varchar(512) DEFAULT NULL,
  `start_binlog_pos` int(11) DEFAULT NULL,
  `end_binlog_file` varchar(512) DEFAULT NULL,
  `end_binlog_pos` int(11) DEFAULT NULL,
  `sql_statement` mediumtext,
  `host` varchar(64) DEFAULT NULL,
  `dbname` varchar(64) DEFAULT NULL,
  `tablename` varchar(64) DEFAULT NULL,
  `port` int(11) DEFAULT NULL,
  `time` timestamp NULL DEFAULT NULL,
  `type` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`opid_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 `

  `host` varchar(64) DEFAULT NULL,   这个字段需要扩大

**Comment by hanchuanchuan** [comment]
是的, 很报歉我之前的修复丢失了, 可能本地误回滚导致的, 所以又重新改了一次.

**Comment by hanchuanchuan** [comment]
请升级到`v1.3.0-1`版本后重试.
