### ISSUE TITLE
rename column audit failed for tidb 5.0

### ISSUE THREAD

**Issue by realcp1018** [hanchuanchuan/goInception#422]
**描述**
"alter table sbtest1 rename column `c` to `d`;" statement audit failed with error: line 1 column 37 near "column `c` to `d`;inception_magic_commit"

**重现**
CREATE TABLE `sbtest1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `k` int(11) NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `k_1` (`k`)
);

**环境**
 - 数据库: [tidb]
 - 版本: [例如 5.0.1/5.0.2]

**参数**

**Comment by realcp1018** [comment]
暂未在其他版本测试过，其他sql类似alter table add column等可以跑通

**Comment by hanchuanchuan** [comment]
已更新 [v1.2.5-23](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.5). 请升级后重试.
