### ISSUE TITLE
[ bug ]回滚数据与原始数据相差8h

### ISSUE THREAD

**Issue by BLUES-CY** [hanchuanchuan/goInception#423]
重现步骤
1.目标为utc时区的数据库，提交一条 删除带有timestamp字段的数据
2.回滚该语句，检查timestamp字段
3.前后数据对比发现timestamp相差8h

期待结果和实际结果
期待结果：
和原始日期一致

实际结果:
比原始日期多了8h

错误日志
只是数据库记录异常，无错误日志

目前看是utc数据库的binlog日志，解析到东八区的archery上，转换成相应时区的回滚SQL
存储到mediumtext字段的对应表中，提交回滚SQL时，archery默认使用的是原始数据库对应的时区，
结果以utc时区执行了该SQL

是否可以通过下面两种方法避免：
1.提交SQL时允许执行set time_zone（
2.提交SQL时是否可以选择设置成自己所在的时区，不用对面库的时区

目前公司有UTC和东八区的两种库，没法统一

版本信息
应用版本/分支：archery Release v1.8.2  goinception v1.2.4-85-g995d131-dirty

部署方式：Docker(部署在utc时区的ubuntu18)，mysql 使用apt方式单独安装，配置文件设置了+8:00

**Comment by hanchuanchuan** [comment]
`timestamp`类型会根据client时区自动转换, 在生成回滚语句时是以archery(goinception)所在机器的时区进行的, 所以当执行回滚语句时应同样以其时区来执行.
**生成的回滚语句变成了`INSERT INTO `test_inc`.`t1`(`id`,`c1`) VALUES(1,'2022-02-20 21:10:39');`形式, 所以必须以同样的时区执行才能回滚正确.**

**Comment by BLUES-CY** [comment]
您好：
        根据您的解答，问题的原因已经了解了，我这里archery所在的容器里的时区是北京时区，目标数据库的时区为UTC。
