### ISSUE TITLE
能否通过调用选项动态设置"must_have_columns"的列

### ISSUE THREAD

**Issue by ldcsaa** [hanchuanchuan/goInception#424]
**描述您想要的功能：**

数据库中有公共表和业务表，公共表中需要包含id,create_time,update_time等列，而业务表除此以外还要包含"租户ID"：tenant_id。

**描述您考虑过的解决/替代方案：**

能否通过调用选项动态设置"must_have_columns"的列？

**Comment by hanchuanchuan** [comment]
当然. 
你可以像设置MySQL会话级变量一样动态的修改`must_have_columns`参数值.
例如:
```sql
inception set must_have_columns = 'create_time,update_time';
create table table1(id int primary key, c1 int);
```
