### ISSUE TITLE
DELETE 语句不支持别名

### ISSUE THREAD

**Issue by xiyangxixian** [hanchuanchuan/goInception#428]
**描述**
对问题简单清晰的描述
SQL: DELETE FROM `tb` t WHERE t.id = 0
语法错误：line 1 column 18 near "t WHERE t.id = 0"

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
可以在MySQL中试一下该SQL，
我测试的结果也是会报语法错误的，正常的带别名写法应该如下：
```sql
DELETE t FROM tb t WHERE t.id = 0;
```

**Comment by xiyangxixian** [comment]
嗯嗯，MySQL 这边确实是一个不合法的 SQL，不过之前测了一下 TiDB 那边是支持 DELETE FROM tb t  这种形式的。

**Comment by hanchuanchuan** [comment]
好的，这样的话应该是TiDB更新升级了解析器，稍后会同步该部分语法解析。
