### ISSUE TITLE
accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files

### ISSUE THREAD

**Issue by leonlee81** [hanchuanchuan/goInception#430]
**描述**
SQL: ALTER TABLE `t_shop_xxxx_detail`\nMODIFY COLUMN `create_by` bigint COMMENT '数据密级S2,创建人',\nMODIFY COLUMN `update_by` bigint COMMENT '数据密级S2,更新人';

表数据量：110W

time="2022/02/24 23:13:37.072" level=info msg="con:8439 new connection 10.66.28.88:57272" file=server.go func=onConn line=319
time="2022/02/24 23:13:37.073" level=debug msg="con:0 ActivePendingTxn select HIGH_PRIORITY * from mysql.global_variables where variable_name in ('autocommit', 'sql_mode', 'max_allowed_packet', 'time_zone', 'block_encryption_mode', 'tidb_skip_utf8_check', 'tidb_index_join_batch_size', 'tidb_index_lookup_size', 'tidb_index_lookup_concurrency', 'tidb_index_lookup_join_concurrency', 'tidb_index_serial_scan_concurrency', 'tidb_hash_join_concurrency', 'tidb_projection_concurrency', 'tidb_hashagg_partial_concurrency', 'tidb_hashagg_final_concurrency', 'tidb_backoff_lock_fast', 'tidb_constraint_check_in_place', 'tidb_ddl_reorg_worker_cnt', 'tidb_opt_insubquery_unfold', 'tidb_distsql_scan_concurrency', 'tidb_max_chunk_size', 'tidb_enable_cascades_planner', 'tidb_retry_limit', 'tidb_disable_txn_auto_retry')" file=adapter.go func=buildExecutor line=278
time="2022/02/24 23:13:37.075" level=debug msg="con:8439 ActivePendingTxn SET AUTOCOMMIT = 0" file=adapter.go func=buildExecutor line=278
time="2022/02/24 23:13:37.075" level=debug msg="con:8439 autocommit=0" file=set.go func=setSysVariable line=180
time="2022/02/24 23:13:37.126" level=debug msg=mysqlServerVersion file=session_inception.go func=mysqlServerVersion line=1654
time="2022/02/24 23:13:37.135" level=debug msg="db version: 50730" file=session_inception.go func=mysqlServerVersion line=1705
time="2022/02/24 23:13:37.135" level=debug msg=setSqlSafeUpdates file=session_inception.go func=setSqlSafeUpdates line=1874
time="2022/02/24 23:13:37.135" level=debug msg=setLockWaitTimeout file=session_inception.go func=setLockWaitTimeout line=1896
time="2022/02/24 23:13:37.135" level=debug msg=processCommand file=session_inception.go func=processCommand line=551
time="2022/02/24 23:13:37.135" level=debug msg=checkAlterTable file=session_inception.go func=checkAlterTable line=3038
time="2022/02/24 23:13:37.172" level=debug msg=checkModifyColumn file=session_inception.go func=checkModifyColumn line=3456
time="2022/02/24 23:13:37.173" level=debug msg=mysqlCheckField file=session_inception.go func=mysqlCheckField line=3826
time="2022/02/24 23:13:37.173" level=debug msg=checkModifyColumn file=session_inception.go func=checkModifyColumn line=3456
time="2022/02/24 23:13:37.173" level=debug msg=mysqlCheckField file=session_inception.go func=mysqlCheckField line=3826
time="2022/02/24 23:13:37.173" level=debug msg=checkIsReadOnly file=session_inception.go func=checkIsReadOnly line=1943
time="2022/02/24 23:13:37.181" level=debug msg=executeRemoteStatement file=session_inception.go func=executeRemoteStatement line=1415
time="2022/02/24 23:13:37.181" level=info msg="con:8439 use gh-ost: ALTER TABLE `t_shop_xxxx_detail`\nMODIFY COLUMN `create_by` bigint COMMENT '数据密级S2,创建人',\nMODIFY COLUMN `update_by` bigint COMMENT '数据密级S2,更新人'" file=session_inception.go func=executeRemoteStatement line=1423
time="2022/02/24 23:13:37.181" level=debug msg="assume_master_host: xxxx-yyy-master.mysql.rds.aliyuncs.com:3300" file=osc.go func=mysqlExecuteAlterTableGhost line=221
time="2022/02/24 23:13:37.181" level=info msg="Migrating `xxxx_bos`.`t_shop_xxxx_detail`" file=migrator.go func=Migrate line=330
time="2022/02/24 23:13:37.231" level=info msg="connection validated on xxxx-yyy-master.mysql.rds.aliyuncs.com:3300" file=utils.go func=ValidateConnection line=89
time="2022/02/24 23:13:37.237" level=info msg="User has REPLICATION CLIENT, REPLICATION SLAVE privileges, and has ALL privileges on `xxxx_bos`.*" file=inspect.go func=validateGrants line=261
time="2022/02/24 23:13:37.249" level=info msg="binary logs validated on xxxx-yyy-master.mysql.rds.aliyuncs.com:3300" file=inspect.go func=validateBinlogs line=364
time="2022/02/24 23:13:37.249" level=info msg="Inspector initiated on xxxx-yyy-master.mysql.rds.aliyuncs.com:3300, version 5.7.30-log" file=inspect.go func=InitDBConnections line=72
time="2022/02/24 23:13:37.256" level=info msg="Table found. Engine=InnoDB" file=inspect.go func=validateTable line=422
time="2022/02/24 23:13:37.256" level=debug msg="Estimated number of rows via STATUS: 1152495" file=inspect.go func=validateTable line=423
time="2022/02/24 23:13:37.256" level=warning msg="--skip-foreign-key-checks provided: will not check for foreign keys" file=inspect.go func=validateTableForeignKeys line=430
time="2022/02/24 23:13:37.258" level=info msg="con:8440 new connection 10.66.26.241:28410" file=server.go func=onConn line=319
time="2022/02/24 23:13:37.258" level=debug msg="con:8440 ActivePendingTxn SET AUTOCOMMIT = 0" file=adapter.go func=buildExecutor line=278
time="2022/02/24 23:13:37.258" level=debug msg="con:8440 autocommit=0" file=set.go func=setSysVariable line=180
time="2022/02/24 23:13:37.262" level=debug msg="Validated no triggers exist on table" file=inspect.go func=validateTableTriggers line=507
time="2022/02/24 23:13:37.269" level=info msg="Estimated number of rows via EXPLAIN: 1152495" file=inspect.go func=estimateTableRowsViaExplain line=531
time="2022/02/24 23:13:37.276" level=debug msg="Potential unique keys in t_shop_xxxx_detail: [PRIMARY: [id]; has nullable: false]" file=inspect.go func=getCandidateUniqueKeys line=678
time="2022/02/24 23:13:37.282" level=info msg="Master forced to be xxxx-yyy-master.mysql.rds.aliyuncs.com:3300" file=migrator.go func=initiateInspector line=786
time="2022/02/24 23:13:37.288" level=info msg="log_slave_updates validated on xxxx-yyy-master.mysql.rds.aliyuncs.com:3300" file=inspect.go func=validateLogSlaveUpdates line=377
time="2022/02/24 23:13:37.300" level=debug msg=mysqlServerVersion file=session_inception.go func=mysqlServerVersion line=1654
time="2022/02/24 23:13:37.300" level=info msg="connection validated on xxxx-yyy-master.mysql.rds.aliyuncs.com:3300" file=utils.go func=ValidateConnection line=89
time="2022/02/24 23:13:37.307" level=debug msg="Streamer binlog coordinates: mysql-bin.001829:36478984" file=streamer.go func=readCurrentBinlogCoordinates line=163
time="2022/02/24 23:13:37.307" level=info msg="create BinlogSyncer with config {2000108439 mysql xxxx-yyy-master.mysql.rds.aliyuncs.com 3300 ddl_user    false false <nil> false UTC true 0 0s 0s 0 false false 0}" file=binlogsyncer.go func=NewBinlogSyncer line=144
time="2022/02/24 23:13:37.307" level=info msg="Connecting binlog streamer at mysql-bin.001829:36478984" file=gomysql_reader.go func=ConnectBinlogStreamer line=65
time="2022/02/24 23:13:37.307" level=info msg="begin to sync binlog from position (mysql-bin.001829, 36478984)" file=binlogsyncer.go func=StartSync line=359
time="2022/02/24 23:13:37.307" level=debug msg="db version: 50730" file=session_inception.go func=mysqlServerVersion line=1705
time="2022/02/24 23:13:37.307" level=debug msg=setSqlSafeUpdates file=session_inception.go func=setSqlSafeUpdates line=1874
time="2022/02/24 23:13:37.307" level=debug msg=setLockWaitTimeout file=session_inception.go func=setLockWaitTimeout line=1896
time="2022/02/24 23:13:37.308" level=debug msg=processCommand file=session_inception.go func=processCommand line=551
time="2022/02/24 23:13:37.308" level=debug msg=checkAlterTable file=session_inception.go func=checkAlterTable line=3038
time="2022/02/24 23:13:37.338" level=debug msg=checkModifyColumn file=session_inception.go func=checkModifyColumn line=3456
time="2022/02/24 23:13:37.338" level=debug msg=mysqlCheckField file=session_inception.go func=mysqlCheckField line=3826
time="2022/02/24 23:13:37.338" level=debug msg=checkModifyColumn file=session_inception.go func=checkModifyColumn line=3456
time="2022/02/24 23:13:37.338" level=debug msg=mysqlCheckField file=session_inception.go func=mysqlCheckField line=3826
time="2022/02/24 23:13:37.338" level=debug msg=checkIsReadOnly file=session_inception.go func=checkIsReadOnly line=1943
time="2022/02/24 23:13:37.345" level=debug msg=executeRemoteStatement file=session_inception.go func=executeRemoteStatement line=1415
time="2022/02/24 23:13:37.348" level=debug msg="Beginning streaming" file=migrator.go func=func2 line=1035
time="2022/02/24 23:13:37.354" level=info msg="rotate to (mysql-bin.001829, 36478984)" file=binlogsyncer.go func=parseEvent line=776
time="2022/02/24 23:13:37.354" level=info msg="rotate to next log from mysql-bin.001829:0 to mysql-bin.001829" file=gomysql_reader.go func=StreamEvents line=152
time="2022/02/24 23:13:37.360" level=info msg="connection validated on xxxx-yyy-master.mysql.rds.aliyuncs.com:3300" file=utils.go func=ValidateConnection line=89
time="2022/02/24 23:13:37.403" level=info msg="connection validated on xxxx-yyy-master.mysql.rds.aliyuncs.com:3300" file=utils.go func=ValidateConnection line=89
time="2022/02/24 23:13:37.409" level=info msg="will use time_zone='+08:00' on applier" file=applier.go func=validateAndReadTimeZone line=113
time="2022/02/24 23:13:37.409" level=info msg="Examining table structure on applier" file=applier.go func=readTableColumns line=119
time="2022/02/24 23:13:37.416" level=info msg="Applier initiated on xxxx-yyy-master.mysql.rds.aliyuncs.com:3300, version 5.7.30-log" file=applier.go func=InitDBConnections line=102
time="2022/02/24 23:13:37.428" level=info msg="Dropping table `xxxx_bos`.`_t_shop_xxxx_detail_ghc`" file=applier.go func=dropTable line=242
time="2022/02/24 23:13:37.439" level=info msg="Table dropped" file=applier.go func=dropTable line=249
time="2022/02/24 23:13:37.439" level=info msg="Creating changelog table `xxxx_bos`.`_t_shop_xxxx_detail_ghc`" file=applier.go func=CreateChangelogTable line=225
time="2022/02/24 23:13:37.448" level=info msg="Changelog table created" file=applier.go func=CreateChangelogTable line=232
time="2022/02/24 23:13:37.448" level=info msg="Creating ghost table `xxxx_bos`.`_t_shop_xxxx_detail_gho`" file=applier.go func=CreateGhostTable line=178
time="2022/02/24 23:13:37.458" level=info msg="Ghost table created" file=applier.go func=CreateGhostTable line=185
time="2022/02/24 23:13:37.458" level=info msg="Altering ghost table `xxxx_bos`.`_t_shop_xxxx_detail_gho`" file=applier.go func=AlterGhost line=196
time="2022/02/24 23:13:37.458" level=debug msg="ALTER statement: alter /* gh-ost */ table `xxxx_bos`.`_t_shop_xxxx_detail_gho` MODIFY COLUMN `create_by` BIGINT COMMENT '数据密级S2,创建人', MODIFY COLUMN `update_by` BIGINT COMMENT '数据密级S2,更新人'" file=applier.go func=AlterGhost line=200
time="2022/02/24 23:13:37.471" level=info msg="Ghost table altered" file=applier.go func=AlterGhost line=204
time="2022/02/24 23:13:37.478" level=info msg="Intercepted changelog state GhostTableMigrated" file=migrator.go func=onChangelogStateEvent line=229
time="2022/02/24 23:13:37.524" level=info msg="Waiting for ghost table to be migrated. Current lag is 0s" file=migrator.go func=FinalizeMigration line=377
time="2022/02/24 23:13:37.524" level=debug msg="ghost table migrated" file=migrator.go func=FinalizeMigration line=379
time="2022/02/24 23:13:37.524" level=info msg="Handled changelog state GhostTableMigrated" file=migrator.go func=onChangelogStateEvent line=255
time="2022/02/24 23:13:37.531" level=debug msg="Potential unique keys in _t_shop_xxxx_detail_gho: [PRIMARY: [id]; has nullable: false]" file=inspect.go func=getCandidateUniqueKeys line=678
time="2022/02/24 23:13:37.544" level=info msg="Chosen shared unique key is PRIMARY" file=inspect.go func=inspectOriginalAndGhostTables line=160
time="2022/02/24 23:13:37.544" level=info msg="Shared columns are id,shop_purchase_order_id,sku_id,product_id,purchase_price,num,receive_num,stock_type,stock,daily_stock,remark,create_by,update_by,create_time,update_time,is_delete,performance_type,send_num" file=inspect.go func=inspectOriginalAndGhostTables line=170
time="2022/02/24 23:13:37.558" level=info msg="Listening on unix socket file: /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock" file=server.go func=BindSocketFile line=52
time="2022/02/24 23:13:37.558" level=debug msg="Reading migration range according to key: PRIMARY" file=applier.go func=ReadMigrationMinValues line=360
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79
time="2022/02/24 23:13:37.558" level=error msg="accept unix /tmp/gh-ost.37ace3dbe2b8f53ebab6184b60ba0a.3300.xxxx_bos.t_shop_xxxx_detail.sock: accept4: too many open files" file=server.go func=func1 line=79

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql]阿里云RDS
 - 版本: 5.7

**参数**
可能与问题相关的设置参数

**Comment by leonlee81** [comment]
麻烦帮忙看看有没有遇到过这个问题

**Comment by hanchuanchuan** [comment]
`too many open files`是Linux报错，一般通过`ulimit`设置，或者修改`/etc/security/limits.conf` 或 `/proc/sys/fs/file-max`
