### ISSUE TITLE
ghost功能不显示cut-over，也不能通过命令切换

### ISSUE THREAD

**Issue by lprincewz** [hanchuanchuan/goInception#433]
**描述您想要的功能：**
一、原生gh-ost在指定postpone-cut-over-flag-file时,copy data结束后，会显示cut-over，目前测试goInception不会显示，只能通过百分比判断，但是这个不准。
二、当goInception指定ghost_postpone_cut_over_flag_file时，删除需要手动到对应服务器删除，如果部署在源端，不太方便，建议可以添加功能，像暂定类操作，可以直接通过goInception命令执行

**Comment by hanchuanchuan** [comment]
已有该功能。
暂停指定osc进程:
```sql
inception pause osc '*E53542EFF4E179BE267210114EC5EDBEF9DC5D8F';
-- 或同义词
inception pause alter '*E53542EFF4E179BE267210114EC5EDBEF9DC5D8F';
```

恢复/终止等详见文档：https://hanchuanchuan.github.io/goInception/zh/ghost.html

**Comment by lprincewz** [comment]
不是暂停，是指定ghost_postpone_cut_over_flag_file不会自动cut-over，需要删除对应文件才能完成cut-over，如果goInception部署在其他服务器,操作比较麻烦
