### ISSUE TITLE
对一张非分区表重建为分区表 会报错 请问可以支持这个语法吗

### ISSUE THREAD

**Issue by ht2324** [hanchuanchuan/goInception#434]
**描述您想要的功能：**
可以对普通表修改为分区表
AlTER TABLE  PARTITION BY 

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
分区表语法已添加支持 #281, #282 ， 请确认版本。如升级后仍不支持，请提供具体SQL。

**Comment by nick2wang** [comment]
> 分区表语法已添加支持 #281, #282 ， 请确认版本。如升级后仍不支持，请提供具体SQL。

1.2.5版本仍然不支持分区表与非分区表转换语法，SQL样例：
(1) 非分区表修改为分区表：
alter table tb_test partition by range (to_days(bill_date)) (
    partition p202201 values less than (to_days('2022-02-01')) ENGINE = InnoDB,
    partition p202202 values less than (to_days('2022-03-01')) ENGINE = InnoDB
);
(2) 分区表取消分区：
alter table tb_test remove partitioning;
