### ISSUE TITLE
enable_nullable能否扩展, 支持特定类型列允许null, 而其余类型列不允许

### ISSUE THREAD

**Issue by Fanduzi** [hanchuanchuan/goInception#435]
**描述您想要的功能：**
类似添加一个参数 nullable_col_type_list: [datetime]

为什么需要这个功能呢. 
有一些业务场景, 如用户订单表, 需要一个订单完成时间, 或者付款时间列. 这个列往往是datetime类型.  在用户下单后, 订单完成时间或付款时间就应该是null, 无论从业务逻辑还是从语义上null都是合理的.
如果enable_nullable=false. 则所有列都不允许null. 需要not null default. 对于datetime类型列. 只能设置一个"magic number", 如1970-01-01. 写过代码的人都知道, magic number不是一个好的设计.
但是如果enable_nullable=true, 则其他类型的列, 如varchar, 也可以null了.

我们目前的情况是, 只有datetime类型列希望可以允许null, 而其他类型列都不允许null. 目前goinception貌似无法实现吧. 作者能否支持一下, 不胜感激

**描述您考虑过的解决/替代方案：**
无

**可参考文档,资料,引用等：**
无

**Comment by hanchuanchuan** [comment]
可参考 PR #319 或 #418 来实现，欢迎提交PR。
