### ISSUE TITLE
[求解决]调用PT工具异常

### ISSUE THREAD

**Issue by mygitnote** [hanchuanchuan/goInception#439]
**描述**
goinception调用pt工具异常，手动执行没有问题。
docker部署方式最新版本。PT工具是3.0.8

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7]

**参数**
![image](https://user-images.githubusercontent.com/24616188/160103562-5056e67d-706b-4682-9dfd-4325b55b7a0d.png)
![image](https://user-images.githubusercontent.com/24616188/160103740-8906e032-07a1-405c-baa3-dc913fa13580.png)

**Comment by mygitnote** [comment]
补充：我的PT是装在goinception容器里的

**Comment by mygitnote** [comment]
大佬，能提供下建议吗？目前找不到原因。通过拷贝日志里的命令直接手动命令行执行是可以的。通过goinception就会报错。

**Comment by hanchuanchuan** [comment]
建议多测试一下，尚未遇到同样的问题。(pt-osc产生的触发器通常由其自身或二次开发的审核平台来清理)

**Comment by hanchuanchuan** [comment]
`--preserve-triggers`的功能是保留现有触发器来实现onlineddl，但如果触发器名称和pt-osc创建的触发器同名时，该参数是无效的。

**Comment by mygitnote** [comment]
> 建议多测试一下，尚未遇到同样的问题。(pt-osc产生的触发器通常由其自身或二次开发的审核平台来清理)

只要执行过程中触发PT调用就报这个错，看日志是goinception异常退出了，但是提示是触发器问题。虽然goinception报告异常返回但是pt仍在执行，而且会执行成功。这就很尴尬
