### ISSUE TITLE
mgr+proxysql架构 执行dml备份失败，ddl可以执行成功

### ISSUE THREAD

**Issue by hcb1987** [hanchuanchuan/goInception#441]
**描述**
mgr+proxysql架构 执行dml执行成功，但是备份失败，ddl可以执行成功,其他环境也可以正常备份

报错信息如下：
Backup: io.ReadFull(header) failed. err EOF: connection was bad.

**环境**
 - 数据库:mysql
 - 版本: 5.7.37-log
 - proxysql  版本2.3.2

**Comment by hanchuanchuan** [comment]
使用proxy情况下，不支持DML备份功能，原因是其不支持MySQL复制协议。

**Comment by hcb1987** [comment]
> 使用proxy情况下，不支持DML备份功能，原因是其不支持MySQL复制协议。

感谢回复，这个我已经解决了，修改proxysql中mysql_user表里面的参数fast_forward参数就行了。
