### ISSUE TITLE
语法检测执行超时，提示invalid connection

### ISSUE THREAD

**Issue by liuywgamebar1** [hanchuanchuan/goInception#442]
**描述**
对问题简单清晰的描述

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
请提供以下信息：
  具体执行了多久，什么SQL，是否能提供简单重现的例子，goinception日志有吗，版本是多少(是最新吗)
