### ISSUE TITLE
mysql表列数限制规则

### ISSUE THREAD

**Issue by xmabul** [hanchuanchuan/goInception#443]
**描述您想要的功能：**
表列数限制规则，比如超过30列就返回error，提示超过限制列数

**描述您考虑过的解决/替代方案：**
新增表时直接统计SQL语法树，但如果只是新增字段需要再获取已有字段数

**可参考文档,资料,引用等：**
mysql开发规范是30个字段

**Comment by hanchuanchuan** [comment]
已添加表列数限制参数`max_column_count`，请升级到`v1.2.5-46`版本。

**Comment by xmabul** [comment]
> 已添加表列数限制参数`max_column_count`，请升级到`v1.2.5-46`版本。

赞！
