### ISSUE TITLE
insert 空间类型语句解析失败

### ISSUE THREAD

**Issue by kongzeng** [hanchuanchuan/goInception#444]
**描述**
goinception:1.2.5下执行一下insert语句，审核失败

sql：insert into test (a) VALUES(Point(118.11598575705503,24.467496941935355))

error_message -> line 1 column 51 near "Point(118.11598575705503,24.467496941935355))" 

**重现**
insert into test (a) VALUES(Point(118.11598575705503,24.467496941935355))

**环境**
 - 数据库: [mysql]
 - 版本: [5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by kongzeng** [comment]
POINT（X，Y）和GeomFromText（ 'POINT（X,Y)'）这两种方式，mysql原生都是支持的，但是goinception不支持POINT（X，Y）

**Comment by hanchuanchuan** [comment]
请先使用`GeomFromText`的方式，TiDB解析器暂不支持`POINT(X,Y)`函数，等其支持后goinception会做相应升级。
