### ISSUE TITLE
DDL预估影响行数不准确

### ISSUE THREAD

**Issue by sona-yuan** [hanchuanchuan/goInception#445]
**描述**
通过CREATE INDEX 添加索引的sql，影响行数显示为1，与实际不符

**重现**
CREATE INDEX

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.25]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
CREATE INDEX稍后会更新为和ALTER TABLE ADD INDEX逻辑一致。
在审核时会通过`SHOW TABLE STATUS`获取预计表行数，在执行时获取实际执行返回的受影响行数(对于CREATE INDEX通常会返回0)。

**Comment by hanchuanchuan** [comment]
请升级到`v1.2.5-35`版本后重试。

**Comment by OWLbeiming** [comment]
1.8.5了，好像还是没修复
