### ISSUE TITLE
语法检测目前不支持mysql8.0,请求支持。

### ISSUE THREAD

**Issue by liuywgamebar1** [hanchuanchuan/goInception#446]
**描述您想要的功能：**
请求支持mysql8.0,建表语句使用 COLLATE = utf8mb4_0900_ai_ci  ，报错Error 1273: Unknown collation: 'utf8mb4_0900_ai_ci'
谢谢。
**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
请升级到最新版本后重试，该问题在1年前已修复。
