### ISSUE TITLE
建议加大连接参数max_allowed_packet的值

### ISSUE THREAD

**Issue by hhyo** [hanchuanchuan/goInception#45]
**描述您想要的功能：**
insert语句使用多values后，可能会导致语句体积过大，超出max_allowed_packet时会执行失败

**描述您考虑过的解决/替代方案：**
增大max_allowed_packet值或者去除该参数，使用实例默认设置

**可参考文档,资料,引用等：**
https://github.com/hanchuanchuan/goInception/blob/master/session/conn.go#L41

**Comment by hhyo** [comment]
同时备份表的字段类型需要调整为longtext，否则会出现
```
Backup: 数据过长!(列 'sql_statement',行 '1')
```

**Comment by hanchuanchuan** [comment]
已添加新参数 `max_allowed_packet`，默认值为 `4194304`，即4MB，可根据实际需要设置该参数，单位 `Byte`。
数据过长问题的原因是单个SQL过长，已经优化为 `mediumtext`类型。

**说明： 备份时提示`数据过长`不会影响实际的备份解析，回滚语句仍会正常生成。（仅影响备份记录表对原始语句的保存）**
