### ISSUE TITLE
[建议] 移除这个error：索引长度不能超过767或3072,由实际mysql的innodb_large_prefix决定

### ISSUE THREAD

**Issue by peng19832** [hanchuanchuan/goInception#450]
**描述您想要的功能：**
移除这个error：索引长度不能超过767或3072,由实际mysql的innodb_large_prefix决定

**描述您考虑过的解决/替代方案：**
增加转换表的行格式为DYNAMIC的提示

**可参考文档,资料,引用等：**
8.0版本，已经没有innodb_large_prefix配置项

**Comment by hanchuanchuan** [comment]
在mysql v8.0不再限制索引大小了吗? 现在的实现是v8.0自动按3072上限处理的。
表的行格式转为DYNAMIC格式的提示建议另提一个issue以方便其他相同需求的用户。

**Comment by sona-yuan** [comment]
tidb也不支持这个参数，要不然把这个改为参数控制吧
