### ISSUE TITLE
支持使用环境变量, 命令行参数等覆盖配置文件中的选项

### ISSUE THREAD

**Issue by LeoQuote** [hanchuanchuan/goInception#452]
**描述您想要的功能：**
k8s 环境下, 环境变量可以引用一些secret, 保密性会更好, 更新配置时就会自动重启, 更加方便.

如果是配置文件的形式, 只能存 cm 或者整个的 secret, 更新起来还是比较麻烦

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
现在配置的更新支持三种方式：
- 修改配置文件并重启
- 直接修改全局的配置参数(内存) `inception set global osc_check_interval = 10;`
- 在审核/执行前动态修改会话级参数 `inception set session osc_check_interval = 10;`

上述方式的组合应该能够支持你的需求了。
