### ISSUE TITLE
如何kill正在运行的进程

### ISSUE THREAD

**Issue by louiswang132** [hanchuanchuan/goInception#455]
https://hanchuanchuan.github.io/goInception/zh/kill_stmt.html

官网看到以上说明，能支持kill功能，使用inception show processlist获取到当前运行的sql id后，使用inception KILL {id}杀sql，提示((1, 'RERUN', 2, 'Audit Completed', 'line 1 column 18 near "155" ', 'inception kill 155', 0, '0_0_00000000', None, '0', None, '0'),)，这个怎么处理

**Comment by hanchuanchuan** [comment]
中止进程功能使用说明：
https://hanchuanchuan.github.io/goInception/zh/demo.html#%E8%BF%9B%E7%A8%8B%E5%88%97%E8%A1%A8

**Comment by louiswang132** [comment]
还有一个问题，是发布ddl用osc功能提交后没有及时返回信息，我获取不到sha1信息，后面无法对正在执行的sql进行终止功能，能知道这是什么原因吗？
提交sql：sql_execute = f"""/*--user='{user}';--password='{password}';--host='{host}';--port={port};--execute=1;--ignore-warnings=1;{str_backup};--sleep=200;--sleep_rows=100*/
                            inception_magic_start;
                            use `{db_name}`;
                            {sql_content.rstrip(';')};
                            inception_magic_commit;"""
goinception日志：time="2022/06/05 15:48:46.397" level=info msg="con:859 use pt-osc: alter table t_ali_rds1 modify f_db_instance_description varchar(128) null comment '55533355'" file=session_inception.go func=executeRemoteStatement line=1450
进程：
![image](https://user-images.githubusercontent.com/106665502/172040951-26fc5225-0722-4913-9032-d34d8a76e7cb.png)
