### ISSUE TITLE
count(*) 语法树解析有问题

### ISSUE THREAD

**Issue by Alex-wwei** [hanchuanchuan/goInception#457]
**描述**
对select count(*) from xxx;的查询，当通过--masking=1方式获取语法树的时候返回空；
![image](https://user-images.githubusercontent.com/24616188/172358920-3d2d2712-1059-4988-a736-13b472445eb7.png)
如果换成select count(field) from xxx; 则返回正常

**环境**
 - 数据库: [mysql5.7]
 - 版本: 最新版本

**Comment by hanchuanchuan** [comment]
是的，确实有这个问题，暂时还没想好对于`COUNT`操作应该返回什么信息，请问你有什么建议吗？
