### ISSUE TITLE
er_cant_set_collation无法对create table语句中的collation字符集进行审核，缺失er_table_collation_not_support参数

### ISSUE THREAD

**Issue by Ben2277** [hanchuanchuan/goInception#459]
**描述**
er_cant_set_collation无法对create table语句中的collation字符集进行审核，只能对create database生效。

从代码看，审核表级别collation的ast.TableOptionCollate对应了ErrTableCollationNotSupport错误，但ErrTableCollationNotSupport对应的er_table_collation_not_support参数缺失，感觉应该是漏了，没在config.go中没找到，望解答，多谢。

session_inception.go:
```go
    case ast.TableOptionCollate:
			if s.inc.EnableSetCollation {
				s.checkCollation(opt.StrValue)
			} else {
				s.appendErrorNo(ErrTableCollationNotSupport, table)
			}
```

**环境**
- mysql 5.7.25
- goinception 1.2.4

**参数**
ErrTableCollationNotSupport
er_table_collation_not_support

**Comment by hanchuanchuan** [comment]
错误级别的开关是另外加的，由于报错类型比较多所有有遗漏，稍后会更新相关功能。

**Comment by Ben2277** [comment]
> 错误级别的开关是另外加的，由于报错类型比较多所有有遗漏，稍后会更新相关功能。

已测试v1.3.0，问题解决，感谢
