### ISSUE TITLE
gh-ost版本升级

### ISSUE THREAD

**Issue by skymoou** [hanchuanchuan/goInception#462]
**描述您想要的功能：**

gh-ost  能够升级到最新版嘛，因为老版本的gh-ost会有数据丢失的情况

**Comment by LeoQuote** [comment]
自己升呗, 下载下来覆盖就行了, 这玩意儿不是goinception 提供的

**Comment by hanchuanchuan** [comment]
`gh-ost`同时支持内置和外部调用的方式, 请自行下载并配置` ghost_bin_dir `参数 (#334)
