### ISSUE TITLE
同一台服务器不能同时起两个goinception服务吗？

### ISSUE THREAD

**Issue by Alex-wwei** [hanchuanchuan/goInception#463]
两份配置文件，不通之处在于端口和日志文件。启动一个另一个启动不了。日志如下：
![image](https://user-images.githubusercontent.com/24616188/173738894-a1f6af15-16dd-4f2a-b263-ef1b88118482.png)

**Comment by hanchuanchuan** [comment]
如果你执意如此的话, 请参考文档对config.toml参数的说明
[config.toml参数](https://hanchuanchuan.github.io/goInception/zh/config.html#config-toml%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E) 
并配置不同的`path`目录.
