### ISSUE TITLE
执行不成功，go build -o goInception tidb-server/main.go

### ISSUE THREAD

**Issue by warlock-lv** [hanchuanchuan/goInception#464]
go build -o goInception tidb-server/main.go    
如下
[lvjl@emr-header-1 goInception]$ go build -o goInception tidb-server/main.go
go: github.com/BurntSushi/toml@v0.3.1: Get "https://goproxy.baidu.com/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod": x509: certificate has expired or is not yet valid: current time 2022-06-20T16:36:21+08:00 is after 2021-12-09T23:59:59Z
[lvjl@emr-header-1 goInception]$ 
怎么办？

**Comment by hanchuanchuan** [comment]
移除或更改goproxy后重试, 有部分包如果因网络问题可自行在go.mod使用replace功能替换为github其他镜像包
