### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by wanghuigithub** [hanchuanchuan/goInception#467]
**描述**
启动报错：
2022/06/29 12:33:33.284 tidb.go:262: [info] new store
2022/06/29 12:33:33.304 tidb.go:63: [info] store cdece2cf-9e4a-433e-82a6-bffac14aa38b new domain, ddl lease 0s, stats lease 0
2022/06/29 12:33:33.304 ddl.go:354: [info] [ddl] start DDL:a9af3528-0dd4-4b9d-a19b-fd46a2be971c, run worker true
2022/06/29 12:33:33.305 ddl_worker.go:81: [info] [ddl] start delRangeManager OK, with emulator: true
2022/06/29 12:33:33.305 ddl_worker.go:81: [info] [ddl] start delRangeManager OK, with emulator: true
2022/06/29 12:33:33.305 domain.go:124: [info] [ddl] full load InfoSchema from version 0 to 0, in 135.275µs
2022/06/29 12:33:33.305 domain.go:318: [info] [ddl] full load and reset schema validator.
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/hanchuanchuan/goInception/util/timeutil.inferTZNameFromFileName(0xc00af87580, 0x13, 0xc00af87580, 0x13, 0x0, 0x0)
	/go/goInception/util/timeutil/time.go:106 +0x212
github.com/hanchuanchuan/goInception/util/timeutil.InferSystemTZ(0x0, 0x4a80)
	/go/goInception/util/timeutil/time.go:74 +0x22e
github.com/hanchuanchuan/goInception/session.writeSystemTZ(0x1be9920, 0xc00012e000)
	/go/goInception/session/bootstrap.go:664 +0x34
github.com/hanchuanchuan/goInception/session.doDMLWorks(0x1be9920, 0xc00012e000)
	/go/goInception/session/bootstrap.go:756 +0x674
github.com/hanchuanchuan/goInception/session.bootstrap(0x1be9920, 0xc00012e000)
	/go/goInception/session/bootstrap.go:225 +0xfb
github.com/hanchuanchuan/goInception/session.runInBootstrapSession(0x1bbcd80, 0xc00026be00, 0x197b1f8)
	/go/goInception/session/session.go:1302 +0x1c8
github.com/hanchuanchuan/goInception/session.BootstrapSession(0x1bbcd80, 0xc00026be00, 0x0, 0x0, 0x0)
	/go/goInception/session/session.go:1236 +0x3ed
main.createStoreAndDomain()
	/go/goInception/tidb-server/main.go:161 +0x158
main.main()
	/go/goInception/tidb-server/main.go:132 +0xee

**重现**
使用docker pull hhyo/goinception:latest镜像，部署在k8s中

**环境**
 - 数据库: [mysql]

**Comment by hanchuanchuan** [comment]
指定系统时区试试看
