### ISSUE TITLE
无法通过text类型审核

### ISSUE THREAD

**Issue by amato1oveing** [hanchuanchuan/goInception#472]
**描述**
需要对text类型通过审核，设置disable_types="",enable_blob_type=false仍然无法通过审核

**版本**
1.3.0

**参数**
disable_types="",enable_blob_type=false

**Comment by 786951355** [comment]
您好，你这个text类型怎么解决的，我也有这个问题，不知道哪里没设置对。

> **描述** 需要对text类型通过审核，设置disable_types="",enable_blob_type=false仍然无法通过审核
> 
> **版本** 1.3.0
> 
> **参数** disable_types="",enable_blob_type=false

这个怎么设置的，可否告诉一下，3q

**Comment by amato1oveing** [comment]
> 

抱歉才看到你的问题，无法通过审核的是因为为默认错误等级为2，修改为0或1即可
下面是我修改后的的配置

#禁用数据库类型
disable_types                           ="text"

[inc_level]
er_invalid_data_type = 0

**Comment by 786951355** [comment]
这个禁用了无效的数据类型，会不会引起其他错误的数据类型导致也通过了。

**Comment by 786951355** [comment]
试了确实支持了，谢谢。先这样用吧。

**Comment by shengminjie** [comment]
> 这个禁用了无效的数据类型，会不会引起其他错误的数据类型导致也通过了。

是的，会引起……关键没有禁用text，text也被禁用了，er_invalid_data_type = 0或1 又影响了禁用其他项。已提https://github.com/hanchuanchuan/goInception/issues/529望修复。

**Comment by kobyt2** [comment]
我也遇到这个问题 希望有时间修复一下

**Comment by hanchuanchuan** [comment]
请开启enable_blob_type参数, 然后仅通过disable_types参数来控制不允许的数据类型.
该逻辑将在后续版本优化.
