### ISSUE TITLE
执行 go build -o goInception tidb-server/main.go   不成功

### ISSUE THREAD

**Issue by 0vally1** [hanchuanchuan/goInception#474]
PS D:\go_workspace\goInception> go build -o goInception tidb-server/main.go

# github.com/hanchuanchuan/goInception/session
session\session.go:341:11: s.getAlterTablePostPart undefined (type *session has no field or method getAlterTablePostPart, but does have GetAlterTablePostPart)
session\session_inception.go:684:4: s.mysqlComputeSqlSha1 undefined (type *session has no field or method mysqlComputeSqlSha1)
session\session_inception.go:1443:7: s.mysqlExecuteWithGhost undefined (type *session has no field or method mysqlExecuteWithGhost)
session\session_inception.go:1447:7: s.mysqlExecuteAlterTableGhost undefined (type *session has no field or method mysqlExecuteAlterTableGhost)
session\session_inception.go:1452:6: s.mysqlExecuteAlterTableOsc undefined (type *session has no field or method mysqlExecuteAlterTableOsc)
session\session_inception.go:3192:4: s.checkAlterUseOsc undefined (type *session has no field or method checkAlterUseOsc)
session\session_inception.go:3426:19: s.getSocketFile undefined (type *session has no field or method getSocketFile)

**Comment by 0vally1** [comment]
![image](https://user-images.githubusercontent.com/30279431/179183367-06ad811f-4560-49a2-91b3-02cfc72b6227.png)

**Comment by hanchuanchuan** [comment]
部分接口失败在`session/osc.go`文件中, 请检查并重试.
