### ISSUE TITLE
goInception调用pt执行DDL很慢

### ISSUE THREAD

**Issue by zmalyxy** [hanchuanchuan/goInception#484]
goInception版本：1.2.4
pt工具手工执行时很快，几百万的表分钟级别完成，同样的表通过archery用goInception调用pt执行时，不知道为啥会一直去连接不存在的IP地址（11.113.169.84），每次执行不同的DDL，IP地址还不相同，然后执行时间可能要好几个小时
![image](https://user-images.githubusercontent.com/25155190/181703546-45ce3c22-c991-4c79-9d7d-dc178cc8d2ac.png)

**Comment by hanchuanchuan** [comment]
请检查pt工具的执行参数设置(在goinception机器通过`ps -aux`查找pt进程).
对于连接其他IP的问题, 参数`--recursion-method`用以设置寻找slave的方式,在找到slave列表后,会逐个连接来获取主从延迟.
