### ISSUE TITLE
添加索引时未使用gh-ost

### ISSUE THREAD

**Issue by sona-yuan** [hanchuanchuan/goInception#485]
**描述**
使用create index  的方式添加索引时，表大小超过osc_min_table_size设置，ghost_on设置未true，但是实际执行未使用

**重现**
create index 添加索引

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
create/drop index若使用onlineddl时需要使用alter table语法, 稍后更新版本添加该warning.

**Comment by zyclove2008** [comment]
同样关注这个问题，create index 不走 OST，会导到 主从延迟，而工具又不能限制 create index 这种语法，所以这个问 题造成的后果可能很严重，忘修复

**Comment by DBAAJ** [comment]
当前有参数控制:ignore_osc_alter_stmt
