### ISSUE TITLE
allter table ... rename to ... 校验不符合预期

### ISSUE THREAD

**Issue by dbadylan** [hanchuanchuan/goInception#486]
使用 `alter table ... rename to ...` 对表进行重命名，该 sql 校验失败，提示表不存在，如下图：
![1](https://user-images.githubusercontent.com/46683377/182293770-658e4b55-0f6a-4fd7-9b65-d55a2c4d6bed.png)

如果换成 `rename table ... to ...` 则校验能正常通过：
![2](https://user-images.githubusercontent.com/46683377/182293781-99ecd1f9-dd89-424e-b57b-2422bb8170d8.png)

MySQL：5.7.29, 8.0.22
goInception：1.2.5

**Comment by hanchuanchuan** [comment]
请升级到最新版本后重试.
另外,建议在`inception_magic_start;`语法后使用`use db_name;`来设置数据库.

**Comment by dbadylan** [comment]
已解决，谢谢！

**Comment by dbadylan** [comment]
按建议，升级了最新的 goInception，同时也使用了 use 语法，但问题还是存在，入下图：

![企业微信截图_16613320165544](https://user-images.githubusercontent.com/46683377/186378732-1d0eb0da-a31e-4982-bfa5-2a5ac5ef7bdc.png)

![企业微信截图_20220824170744](https://user-images.githubusercontent.com/46683377/186378763-86756d79-b95c-4062-ab51-b0e3d1e25902.png)

**Comment by engliah12** [comment]
遇到同样的问题，使用的Archery 1.12.0版本，goinception是1.3.0

<img width="2454" height="542" alt="Image" src="https://github.com/user-attachments/assets/abfa9bce-3082-4af6-9b74-e068bb8e1773" />
