### ISSUE TITLE
执行工单时如果遇到失败, 如果失败是因为  Lock wait timeout exceeded 造成的, 将关联表全部杀掉再操作

### ISSUE THREAD

**Issue by LeoQuote** [hanchuanchuan/goInception#488]
**描述您想要的功能：**
有时候应用会对mysql 建立长连接, 执行一个sleep 操作锁表, 导致无法改表, 这时候如果改表, 可能会造成改表失败, 无论是原生执行还是 pt-osc 都可能失败.

如果可以在失败后, 自动去尝试 kill 所有的 process, 然后重新尝试改表, 就可以省去手工 kill prcocess 的麻烦

**描述您考虑过的解决/替代方案：**
手工在执行工单前 kill process

**可参考文档,资料,引用等：**
暂无

**Comment by hhyo** [comment]
percona 可以开启 innodb_kill_idle_transaction，否则就给业务同步风险后自己挂pt kill吧，kill sleep连接很多时候对业务是有损的

**Comment by hanchuanchuan** [comment]
高危操作~
