### ISSUE TITLE
调用gh-ost执行ddl，报错 exit status 1

### ISSUE THREAD

**Issue by nishizhuaheihei** [hanchuanchuan/goInception#489]
报错信息：
time="2022/08/03 01:04:02.653" level=error msg="sh [-c gh-ost --alter "ENGINE = innodb" --assume-master-host= --exact-rowcount=false --concurrent-rowcount=true --allow-on-master=true --allow-master-master=false --allow-nullable-unique-key=false --approve-renamed-columns=true --tungsten=false --discard-foreign-keys=false --skip-foreign-key-checks=true --aliyun-rds=false --gcp=false --ok-to-drop-table=false --initially-drop-old-table=true --initially-drop-ghost-table=true --cut-over=atomic --force-named-cut-over=false --assume-rbr=true --cut-over-exponential-backoff=false --exponential-backoff-max-interval=64 --chunk-size=1000 --dml-batch-size=10 --default-retries=60 --cut-over-lock-timeout-seconds=3 --nice-ratio=0.000000 --max-lag-millis=1500 --replication-lag-query= --heartbeat-interval-millis=500 --throttle-flag-file= --throttle-additional-flag-file= --postpone-cut-over-flag-file= --initially-drop-socket-file=false --serve-socket-file=/tmp/gh-ost....sock --panic-flag-file=/tmp/gh-ost....panic --replica-server-id=*** --critical-load-interval-millis=0 --critical-load-hibernate-seconds=0 --critical-load='Threads_running=80,threads_connected=1000' --max-load='Threads_running=80,threads_connected=1000' --execute --user="" --password='' --host=* --port=* --database='' --table='']" file=osc.go func=execCommand line=902
time="2022/08/03 01:04:02.654" level=error msg="exit status 1" file=osc.go func=execCommand line=903

**Comment by hanchuanchuan** [comment]
请尝试将命令复制到命令行手动执行.
如果仍旧报错请提供详细错误信息及日志.
