### ISSUE TITLE
备份库名过长导致回滚语句生成失败

### ISSUE THREAD

**Issue by shenjianxin** [hanchuanchuan/goInception#49]
**描述**
通过archery提交上线工单时无法生产回滚语句，提示如下：
Backup: 备份库名 'rm-hp3oyau9st72lxxxxxx.mysql.huhehaote.rds.aliyuncs.com-3306-xxxxxxx' 过长. Incorrect database name ''. Incorrect database name ''.

**Comment by hanchuanchuan** [comment]
出现该问题的原因是创建备份库时，名称过长导致。
现已添加自动截断，
`docker`版本已更新(可通过  `docker pull hanchuanchuan/goinception` 获取)，
二进制版本稍后发布release。
