### ISSUE TITLE
检查sql语句影响行数的结果和实际执行的结果不一致

### ISSUE THREAD

**Issue by fgp1990** [hanchuanchuan/goInception#490]
**描述**
/*-user=user;--password=pwd;--host=10.18.111.111;--port=4000;--check=1*/
inception_magic_start;
update aaa set bbb = '1' where qqq like '%jpeg';
inception_magic_commit;

这个的结果，和实际执行返回的结果不一致。
check=1的情况下，返回affected_row是1000。
我切换到sql工具里面，同样的语句，select的结果是20。

**重现**
非必现。有的时候，实际影响行数是1，都会出错。有的时候，不出错

**环境**
 - 数据库: mysql
 - 版本: 5.7.17

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
参考 #492
