### ISSUE TITLE
执行sql语句提示Not supported statement type

### ISSUE THREAD

**Issue by chaimingtao** [hanchuanchuan/goInception#495]
**描述**
审核sql提示Not supported statement type

**重现**
执行/*!40101 SET SQL_MODE=''*/语句，提示Not supported statement type.

**环境**
 - 数据库: [mysql]
 - 版本: [8.0]

**Comment by hanchuanchuan** [comment]
默认仅支持SET NAMES语法.
若要开启所有语法支持可设置参数`enable_any_statement`.

**Comment by chaimingtao** [comment]
添加了enable_any_statement的确可以了，目前执行以下语句有报错：

/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


/* Procedure structure for procedure `P_WG_GetListServerInfo` */;

/*!50003 DROP PROCEDURE IF EXISTS `P_WG_GetListServerInfo` */;

-------------------------------------------------------------------------------------------------------------------------------


|        7 | CHECKED |           0 | Audit Completed |                                                                          | /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */                            |             0 | 0_0_00000006 |               |            0 |         |           0 |
|        8 | RERUN   |           2 | Audit Completed | line 2 column 24 near "PROCEDURE IF EXISTS `P_WG_GetListServerInfo` */"  | /*!50003 DROP PROCEDURE IF EXISTS `P_WG_GetListServerInfo` */                      |             0 | 0_0_00000007 |               |            0 |         |           0 |

**Comment by chaimingtao** [comment]
> 默认仅支持SET NAMES语法. 若要开启所有语法支持可设置参数`enable_any_statement`.

添加了enable_any_statement的确可以了，目前执行以下语句有报错：

/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/* Procedure structure for procedure P_WG_GetListServerInfo */;

/*!50003 DROP PROCEDURE IF EXISTS P_WG_GetListServerInfo */;

| 7 | CHECKED | 0 | Audit Completed | | /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */ | 0 | 0_0_00000006 | | 0 | | 0 |
| 8 | RERUN | 2 | Audit Completed | line 2 column 24 near "PROCEDURE IF EXISTS P_WG_GetListServerInfo /" | /!50003 DROP PROCEDURE IF EXISTS P_WG_GetListServerInfo */ | 0 | 0_0_00000007 | | 0 | | 0 |

**Comment by hanchuanchuan** [comment]
暂不支持PROCEDURE.
建议移除/**/这类命令.
