### ISSUE TITLE
[Bug] 视图语法检测失败

### ISSUE THREAD

**Issue by peng19832** [hanchuanchuan/goInception#496]
**描述**
对问题简单清晰的描述
在试图里存在，跨库调用自定义函数的时候，检测会失败
![image](https://user-images.githubusercontent.com/9590209/185531138-724c58e3-e217-46c4-ae4b-2bab134053a2.png)

**重现**
模拟重现的步骤
视图里，跨库调用自定义函数

**环境**
 - 数据库: mysql/
 - 版本: 8.0

**Comment by hanchuanchuan** [comment]
语法暂未支持自定义函数, 我试试优化一下.

**Comment by peng19832** [comment]
> 语法暂未支持自定义函数, 我试试优化一下.

新库大佬☺
