### ISSUE TITLE
update和inster语句无法生成回滚语句

### ISSUE THREAD

**Issue by wutong6177** [hanchuanchuan/goInception#497]
**描述**
我开启了备份设置后--backup=1，可以对执行的sql语句生成相应的回滚语句。但是现在他只对改表结构和删表操作可以生成，但是对数据的update和inster无法生成回滚语句。请问这个如何排查或解决
邮箱623651361@qq.com

**Comment by hanchuanchuan** [comment]
请提供数据库具体版本.
另外, 确认参数`binlog_row_image`是否为FULL.

**Comment by wutong6177** [comment]
数据库版本是 5.7.24
检查确认过binlog_row_image是FULL

**Comment by wutong6177** [comment]
> 请提供数据库具体版本. 另外, 确认参数`binlog_row_image`是否为FULL.
数据库版本是 5.7.24
检查确认过binlog_row_image是FULL

**Comment by wutong6177** [comment]
> 请提供数据库具体版本. 另外, 确认参数`binlog_row_image`是否为FULL.

问题已经解决，是因为我测试的那个数据库binlog被屏蔽了，多谢您了
