### ISSUE TITLE
gh-ost 改表操作，希望在cut over环节，增加对MDL锁的监控

### ISSUE THREAD

**Issue by jiangnanora** [hanchuanchuan/goInception#499]
**描述您想要的功能：**
gh-ost 改表操作，希望在cut over环节，增加对MDL锁的监控

**描述您考虑过的解决/替代方案：**
在gh-ost该表的时候，由于各种问题，可能会导致MDL锁，引起故障，希望在cut over环节启一个协程实时监控MDL锁，如有问题则canal本次该表操作

**可参考文档,资料,引用等：**

**Comment by MDL13412** [comment]
这个会考虑加入吗? `MDL` 锁很容易导致故障
