### ISSUE TITLE
关于Mysql8 collation的支持

### ISSUE THREAD

**Issue by chinahuhq** [hanchuanchuan/goInception#500]
**描述您想要的功能：**
由于项目需求中存在大小写敏感的字段，参考设置排序集为utf8mb4_0900_as_cs，但是拉取了最新镜像发现仍未支持到
![image](https://user-images.githubusercontent.com/94677443/187640277-20f82158-7a3b-4fd3-9994-d3501c015448.png)
查看到其他issue，例如#446 ，实测发现已经支持了utf8mb4_0900_ai_ci。

**描述您考虑过的解决/替代方案：**
希望可以增加对排序集utf8mb4_0900_as_cs的支持，以及其他更多关于Mysql8的支持。

**可参考文档,资料,引用等：**
https://dev.mysql.com/doc/refman/8.0/en/charset-mysql.html

**Comment by hanchuanchuan** [comment]
该问题已修复. 请升级到 [v1.3.0-15](https://github.com/hanchuanchuan/goInception/releases/tag/v1.3.0) 版本后重试.
