### ISSUE TITLE
uniq_index_prefix 设置为大写，无法正常匹配

### ISSUE THREAD

**Issue by miaoyongbin** [hanchuanchuan/goInception#501]
**描述**
当设置uniq_index_prefix为"UNIQ_"时，SQL审核不通过
**重现**
唯一索引 'UNIQ_ADDRESS_NUMBER' 需要指定'UNIQ_'前缀

**环境**
 - 数据库: [mysql]
 - 版本: 5.6.25

**参数**
可能与问题相关的设置参数

**Comment by DC-ET** [comment]
1.3.0版本一下存在如下bug，可以看下是否跟你是同一个问题

**Comment by DC-ET** [comment]
https://github.com/hanchuanchuan/goInception/issues/469

**Comment by hanchuanchuan** [comment]
配置`uniq_index_prefix`设置为小写即可.

**Comment by DC-ET** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DC-ET** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
