### ISSUE TITLE
delete语句使用别名导致审核报错

### ISSUE THREAD

**Issue by dbadylan** [hanchuanchuan/goInception#505]
delete语句如果使用了别名，审核会报错：
![1](https://user-images.githubusercontent.com/46683377/190337489-14b4e379-443a-40ee-a5cf-0fd72df59a23.png)

如果去掉别名，则审核正常：
![2](https://user-images.githubusercontent.com/46683377/190337633-4d8dfd58-b15e-496b-8713-3ced8b69175d.png)

goInception版本：
![3](https://user-images.githubusercontent.com/46683377/190337804-633032ab-5f10-466e-9566-863ca98b28bf.png)

**Comment by hanchuanchuan** [comment]
MySQL能执行通过吗?
可以试试
```sql
DELETE t FROM t1 as t WHERE t.id=1;
```

**Comment by dbadylan** [comment]
@hanchuanchuan mysql是可以正常执行的：
![1](https://user-images.githubusercontent.com/46683377/190888641-963a87e6-1c27-45a4-9b5b-adb30d1dd06f.png)

**Comment by hanchuanchuan** [comment]
关键在于`DELETE`后面是否跟了表别名`t`. 注意检查语法.
