### ISSUE TITLE
TiDB 建表 PRE_SPLIT_REGIONS 解析异常

### ISSUE THREAD

**Issue by NoskyOrg** [hanchuanchuan/goInception#508]
**描述**
在建表语句中，添加 tidb的 PRE_SPLIT_REGIONS = 2 会异常

**重现**
```sql
CREATE TABLE `dd`(
    `date` varchar(20) NOT NULL DEFAULT '' COMMENT '日期'
) ENGINE = InnoDB SHARD_ROW_ID_BITS=4 PRE_SPLIT_REGIONS=2
```

SQL解析失败 line 1 column 251 near "PRE_SPLIT_REGIONS=2;inception_magic_commit"

**环境**
 - 数据库: [tidb v4.0]

**Comment by hanchuanchuan** [comment]
已优化. 请升级至 [v1.3.0-25](https://github.com/hanchuanchuan/goInception/releases/tag/v1.3.0) 版本.

**Comment by NoskyOrg** [comment]
hao
