### ISSUE TITLE
delete 语句不支持别名

### ISSUE THREAD

**Issue by hctech** [hanchuanchuan/goInception#51]
**描述**
delete 语句不支持别名

**重现**
```
use test;
delete t1 from abc as t1 where t1.id = 1;
```
审核时会出现 ` Table 'test.t1' doesn't exist.`

原来的 inception 中就有这个 issue: https://github.com/mysql-inception/inception/issues/72

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.21]

**Comment by hanchuanchuan** [comment]
谢谢反馈，该问题已经优化，
二进制版本 https://github.com/hanchuanchuan/goInception/releases/tag/v1.0-rc4
`docker` 通过 `docker pull hanchuanchuan/goinception` 获取最新版。

**Comment by hctech** [comment]
delete inner join 的时候还是会出现这个问题
```
use `pharmacy`;

DELETE s1
FROM supplier_drug_mapping AS s1
INNER JOIN supplier_drug_mapping AS s2 ON s1.sku_id = s2.sku_id
AND s1.channel_id = s2.channel_id
WHERE s1.id > s2.id;
```
审核时会出现
```
Table 'pharmacy.s1' doesn't exist.
Column 's1.sku_id' not existed.
Column 's1.channel_id' not existed.
```

**Comment by hanchuanchuan** [comment]
是最新版本吗，我这边测试可以通过的。欢迎进入主页中的QQ群讨论。
![image](https://user-images.githubusercontent.com/18544383/60937180-0e7f5a00-a302-11e9-9d4e-8b948ae87795.png)

**Comment by hanchuanchuan** [comment]
该问题已经修复。版本 https://github.com/hanchuanchuan/goInception/releases/tag/v1.0
