### ISSUE TITLE
执行sql的时候启用--backup=1时，会出现SSL的报错

### ISSUE THREAD

**Issue by qimeinajie** [hanchuanchuan/goInception#514]
**描述**
执行sql的时候启用--backup=1时，会出现SSL的报错
#342 参考了这个
        sql_execute = f"""/*--user='{user}';--password='{password}';--host='{host}';--port={port};--execute=1;--ignore-warnings=1;--ssl=required;--backup=1;--sleep=200;--sleep_rows=100*/
                            inception_magic_start;
                            {set_session_sql}
                            use `{workflow.db_name}`;
                            {workflow.sqlworkflowcontent.sql_content.rstrip(';')};
                            inception_magic_commit;"""
[如上，已经是按照文档](https://hanchuanchuan.github.io/goInception/params.html)加上了ssl的参数
但其中如果--backup=1则会报”con:7046 Error 9002: SSL connection is required. Please specify SSL options and retry..“
但其中如果--backup=0则正常

**环境**
 - 数据库: [azure mysql]
 - Goinception docker镜像 goinception:v1.3.0

**Comment by qimeinajie** [comment]
经过几天的研究，现已根本解决Backup数据库mysql在执行备份时的SSL报错问题。
修改几个文件，session/core.go,session/session_inception.go,session/conn.go
找到对应的数据库连接串:'addr := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?charset=%s&p........'
在末端加上 ‘tls=skip-verify’，加完的结果例子如下

        addr := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?charset=%s&parseTime=True&loc=Local&autocommit=1&maxAllowedPacket=%d_&tls=skip-verify_"

即可解决备份时的时候，SSL链接报错的问题。

由于本人对Go语言不熟悉，不敢提PR，目前只是粗暴地直接加tls在所有需要连接数据库的位置，建议哪位大神可以将改配置添加到与backup-host/backup-port/username/password..那个配置一起，作为一个可配参数。
期待这个问题，早日得到支持，感恩

**Comment by hanchuanchuan** [comment]
感谢你的详细反馈!
请升级到 `v1.3.0-42`版本后配置`backup-tls`参数并重试.
