### ISSUE TITLE
MySQL8.0表字段默认值审核问题

### ISSUE THREAD

**Issue by seiang** [hanchuanchuan/goInception#518]
**描述**
针对MySQL5.7和MySQL8.0版本默认值设置审核报错

建表语句：
CREATE TABLE `test` ( 
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `start_time` datetime NOT NULL DEFAULT ((curtime() - interval 1 day)) COMMENT '开始时间',
  `end_time` datetime NOT NULL DEFAULT ((curtime() - interval 1 day)) COMMENT '结束时间',
  `words` json NOT NULL DEFAULT (json_object()) COMMENT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  CHARSET=utf8mb4;

**重现**
DEFAULT ((curtime() - interval 1 day)) 
DEFAULT (json_object())

上述建表语句在MySQL5.7版本报错语法问题，但是在MySQL8.0可以创建成功

审核报错：
line 2 column 43 near "((curtime() - interval 1 day))

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: mysql5.7.19 和mysql8.0.19

**Comment by jarod** [comment]
我也遇到json默认值的问题，`DEFAULT (JSON_OBJECT())`/ `DEFAULT '{}'` 是MySQL `8.0.13`开始支持的，希望goinception能支持
