### ISSUE TITLE
分区表不能直接修改分区定义

### ISSUE THREAD

**Issue by lprincewz** [hanchuanchuan/goInception#520]
**描述**
不支持直接修改分区定义，原先秒级时间戳分区，要修改为毫秒级时间戳分区
原先表结构：
CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
   ...
  `create_time` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间，时间戳，到秒',
  `update_time` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '最后更新时间，时间戳，到秒',
  PRIMARY KEY (`id`,`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=19771133 DEFAULT CHARSET=utf8mb4 COMMENT='xxx'
/*!50100 PARTITION BY RANGE (`create_time`)
(PARTITION p_202206 VALUES LESS THAN (1656604800) ENGINE = InnoDB,
 PARTITION p_202207 VALUES LESS THAN (1659283200) ENGINE = InnoDB,
 PARTITION p_202208 VALUES LESS THAN (1661961600) ENGINE = InnoDB,
 PARTITION p_202209 VALUES LESS THAN (1664553600) ENGINE = InnoDB,
 PARTITION p_202210 VALUES LESS THAN (1667232000) ENGINE = InnoDB,
 PARTITION p_202211 VALUES LESS THAN (1669824000) ENGINE = InnoDB,
 PARTITION p_202212 VALUES LESS THAN (1672502400) ENGINE = InnoDB,
 PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */
alter语句：
ALTER TABLE `test` partition by RANGE (`create_time`)  (
     PARTITION p_202206 VALUES LESS THAN (1656604800000),
         PARTITION p_202207 VALUES LESS THAN (1659283200000),
         PARTITION p_202208 VALUES LESS THAN (1661961600000),
         PARTITION p_202209 VALUES LESS THAN (1664553600000),
         PARTITION p_202210 VALUES LESS THAN (1667232000000),
         PARTITION p_202211 VALUES LESS THAN (1669824000000),
         PARTITION p_202212 VALUES LESS THAN (1672502400000),
         PARTITION p_max VALUES LESS THAN MAXVALUE
        ) ;
审核报错：
Table 'test' is already a partitioned table. Duplicate partition name p_202206 Duplicate partition name p_202207 Duplicate partition name p_202208 Duplicate partition name p_202209 Duplicate partition name...

**Comment by lprincewz** [comment]
Duplicate partition可以通过设置er_same_name_partition参数跳过，但是Table 'test' is already a partitioned table报错跳不过

**Comment by hanchuanchuan** [comment]
请升级到 `v1.3.0-42`版本后重试.
