### ISSUE TITLE
提个问题，goInception能否部署多个，共用同一个backup服务？

### ISSUE THREAD

**Issue by Z-July** [hanchuanchuan/goInception#524]
**描述您想要的功能：**
想知道几个问题，目前没找到相关文档：
1、单台机器部署的情况下，处理DML是否有execute和backup的瓶颈？
2、多台机器部署的情况下，是否可以共用同一个backup服务，针对同库同表不同DML的不同goInception的处理，在录入同一个backup相关数据时是否会有冲突数据？

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
1. 可以进行压力测试来验证, 生产环境的并发没那么高, 可能会出现一个update/delete影响行数特别大的情况,由于binlog是指定start/end position的,而读取binlog和入库是不同线程,所以总体上问题不大.
2. 可以共用backup服务,生成的opid也就是备份的唯一标识是不同的,所以录入时不影响.
