### ISSUE TITLE
表存在字段varbinary字段时，备份语句会失败

### ISSUE THREAD

**Issue by Sharelengh** [hanchuanchuan/goInception#526]
**描述**
在执行dml语句进行备份时，若表结构存在varbinary类型的字段，字备份结果为 失败，相关日志如下：

time="2022/11/09 09:45:41.331" level=info msg="rotate to (mysql-bin.000361, 473191672)" file=binlogsyncer.go func=parseEvent line=776
time="2022/11/09 09:45:41.332" level=info msg="syncer is closing..." file=binlogsyncer.go func=close line=175
time="2022/11/09 09:45:41.334" level=info msg="kill last connection id 157079362" file=binlogsyncer.go func=killConnection line=849
time="2022/11/09 09:45:41.335" level=info msg="syncer is closed" file=binlogsyncer.go func=close line=202
time="2022/11/09 09:45:41.337" level=error msg="con:4 Error 1366: Incorrect string value: '\\xEE\\xD8\\xF6\\x0CN$...' for column 'rollback_statement' at row 1 sql:insert into `192_168_1_190_3306_tcc`.`text_trx`(rollback_statement,opid_time) values(?,?) params:[INSERT INTO `tcc`.`text_trx`(`ID`,`name`,`trx_id`,`batch_data`,`content`,`status`,`trx_type`,`retry_cnt`,`CREATE_TIME`,`LAST_UPDATE_TIME`,`VERSION`) VALUES(1,'xxxx','M_\xee\xd8\xf6\fN$\x8b\xe6\\n\xf0\xc1\x91i<','E\xcb\x11\xd8\x014A(\xb5\xd9\a\x9aM\xa2\x82\xec',......

**重现**
模拟重现的步骤
使用下面表结构及数据，可复现问题
CREATE TABLE `text_trx` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `trx_id` varbinary(32) NOT NULL,
  `batch_data` varbinary(32) NOT NULL,
  `content` longblob,
  `status` int(11) DEFAULT NULL,
  `trx_type` int(11) DEFAULT NULL,
  `retry_cnt` int(11) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL,
  `VERSION` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `UX_TX_BQ` (`trx_id`,`batch_data`) USING BTREE,
  KEY `idx_domain` (`name`,`LAST_UPDATE_TIME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

INSERT INTO `tcc`.`text_trx` (`ID`, `name`, `trx_id`, `batch_data`, `content`, `status`, `trx_type`, `retry_cnt`, `CREATE_TIME`, `LAST_UPDATE_TIME`, `VERSION`) VALUES (2, 'xxxx2', 0x4D5FEED8F60C4E248BE60AF0C191693C, 0x45CB11D801344128B5D9079A4DA282EC, b'101110010101101', 2, 1, 31, now(), now(), 1);

**环境**
 - 数据库: [Percona Server (GPL), Release 38, Revision 3692a61]
 - 版本: [5.7.35-38-log]

**参数**
字符集参数直接设置init_connect值为'set names utf8mb4;'同样出错

**Comment by hanchuanchuan** [comment]
试试设置参数`hex_blob=true`.

**Comment by systemcia** [comment]
> hex_blob=true

我这边也是同样的问题，试着设置了，还是不可以，同样的报错：
