### ISSUE TITLE
不可以设置表字段为longtext

### ISSUE THREAD

**Issue by kerilcng** [hanchuanchuan/goInception#528]
你好，我试着通过goinception审核将表字段modify为longtext的时候失败，调整了多个text和nuallable参数都无法成功。是完全禁止使用longtext类型吗？

Not supported data type on field: 'label_ids'(longtext).
Type conversion warning for column 'material.label_ids' varchar(255) -> longtext.

**Comment by shengminjie** [comment]
> 你好，我试着通过goinception审核将表字段modify为longtext的时候失败，调整了多个text和nuallable参数都无法成功。是完全禁止使用longtext类型吗？
> 
> Not supported data type on field: 'label_ids'(longtext). Type conversion warning for column 'material.label_ids' varchar(255) -> longtext.

可能和这个问题有关，有先临时解决的方法。
https://github.com/hanchuanchuan/goInception/issues/528#issue-1447572474

**Comment by hanchuanchuan** [comment]
相关问题 #529
