### ISSUE TITLE
disable_types未禁用text字段，text字段无法通过审核

### ISSUE THREAD

**Issue by shengminjie** [hanchuanchuan/goInception#529]
**描述**
disable_types参数没有写text，建表无法建text字段。
设置er_invalid_data_type = 0或1后可以建含text字段的表了，但是提示warning，同时blob这些也可以建了……
是不是程序默认对text有些地方因上次变动disable_types还没改过来，望修复一下。

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.29]

**参数**
disable_types ="blob"
er_invalid_data_type = 2

**Comment by hanchuanchuan** [comment]
按以下步骤配置:
1. 打开参数`enable_blob_type`开允许text/blob类型
2. 使用新参数`disable_types`来灵活控制要禁用的类型,如blob.

之所以这么麻烦是因为参数`enable_blob_type`等属于历史遗留. 集中通过`disable_types`统一配置更方便一些.

**Comment by shengminjie** [comment]
感谢回复，总结如下：
# 设置禁止的所有类型
disable_types = "blob,enum,set,bit"
# 允许text类型，实际此参数会允许text和blob
enable_blob_type=true
在以上参数下，下列参数可以设置为2，不需要再使用临时提到的er_invalid_data_type=1或0。
er_invalid_data_type = 2
er_use_text_or_blob = 2
就不会出现禁止的字段出现警告而可以通过。

**Comment by pengkang1991** [comment]
你好，我在config.toml添加了
disable_types = "blob,enum,set,bit"
er_invalid_data_type = 2
er_use_text_or_blob = 2
后容器无法启动，报以下错误。


time="2022-11-25T09:45:39+08:00" level=fatal msg="Near line 94 (last key parsed 'inc'): bare keys cannot contain '在'\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12\ngithub.com/hanchuanchuan/goInception/config.(*Config).Load\n\t/go/src/github.com/hanchuanchuan/goInception/config/config.go:805\nmain.loadConfig\n\t/go/src/github.com/hanchuanchuan/goInception/tidb-server/main.go:227\nmain.main\n\t/go/src/github.com/hanchuanchuan/goInception/tidb-server/main.go:121\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"
