### ISSUE TITLE
DML 预估受影响行数不准确

### ISSUE THREAD

**Issue by Afeir** [hanchuanchuan/goInception#53]
**描述**
对问题简单清晰的描述
配置了 max_update_rows 参数, 实际操作DML语句受影响行数预估不准确,
导致在正常受限update 行数的sql执行报错.

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数
max_update_rows 参数

**Comment by hanchuanchuan** [comment]
[v1.0.3](https://github.com/hanchuanchuan/goInception/releases/tag/v1.0.3) 版本更新：
添加调用选项 `real_row_count` 用以设置是否通过count(*)获取真正受影响行数，默认为`false`。
