### ISSUE TITLE
增加表字符集的check

### ISSUE THREAD

**Issue by beebol** [hanchuanchuan/goInception#535]
**描述您想要的功能：**
如果表未带字符集，审核失败。

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
不支持该设置. 可以通过以下方式实现该目的:
1. 设置MySQL实例本身的`character_set_server`和database的默认字符集.
2. 配置`support_charset`来设置允许的字符集.
通过上述方式来控制未指定时和指定字符集时的行为一致.
