### ISSUE TITLE
 执行的时候结果集的affected_rows行数，不准确

### ISSUE THREAD

**Issue by guohaohub** [hanchuanchuan/goInception#537]
**描述**
对问题简单清晰的描述
![image](https://user-images.githubusercontent.com/22384638/206120548-c7775be4-ff65-428a-8d09-7182e46e2568.png)

 执行的时候结果集的affected_rows行数与实际相差太大，特别是数据多的时候

**重现**
执行的语句为
delete from `th_sku` where id > 5006002 and id < 5006372;

**环境**
  数据库: mysql
  版本: 5.7.21]
 

**参数**
可能与问题相关的设置参数
这个是config.toml的配置
#当建表时自增列的类型不为int或者bigint时报错
check_autoincrement_datatype = true
#当建表时自增列的值指定的不为1，则报错
check_autoincrement_init_value = false
#建表时，如果指定的自增列的名字不为ID，则报错，说明是有意义的，给提示
check_autoincrement_name = false
#建表时，列没有注释时报错
check_column_comment = true
#检查在建表、修改列、新增列时，新的列属性是不是要有默认值
check_column_default_value = false
#检查列位置/顺序变更
check_column_position_change = false
#检查字段类型变更
check_column_type_change = true
#在DML语句中使用了LIMIT时，是不是要报错
check_dml_limit = false
#在DML语句中使用了Order By时，是不是要报错
check_dml_orderby = false
#在DML语句中没有WHERE条件时，是不是要报错
check_dml_where = true
#开启时,当使用 float/double 类型时提示转成 decimal 类型
check_float_double = true
#检查标识符是否正确,规则是[a-z,A-Z,0-9,_]
check_identifier = true
#要求标识符即表名、列名、索引名等必须为小写,默认为false
check_identifier_lower = false
#要求标识符即表名、列名、索引名等必须为大写,默认为false
check_identifier_upper = false
#检查where条件中是否存在隐式类型转换,默认值false
check_implicit_type_conversion = true
#是否检查索引前缀,索引前缀通过参数index_prefix和uniq_index_prefix配置
check_index_prefix = true
#是不是要检查插入语句中的列链表的存在性
check_insert_field = true
#建表时，如果没有主键，则报错
check_primary_key = true
#建表时，表没有注释时报错
check_table_comment = true
#配置是否检查current_timestamp数量
check_timestamp_count = false
#建表时，如果没有为timestamp类型指定默认值，则报错
check_timestamp_default = false
#指定的列必须添加索引。多个列时以逗号分隔(格式: 列名 [列类型,可选]),指定列类型时对类型也会限制.
columns_must_have_index = ""
#设置连接数据库的默认字符集,默认值为utf8mb4 (解决低版本不支持utf8mb4的问题)
default_charset = "utf8mb4"
#禁用数据库类型,多个时以逗号分隔(合并参数 enable_blob_type,enable_json_type,enable_enum_set_bit,enable_timestamp_type)
disable_types = ""
#是否允许列的类型是BLOB/TEXT
enable_blob_type = true
##是否允许列的类型JSON
enable_json_type = true
##是否允许列的类型使用集合、枚举、位图类型
enable_enum_set_bit = true
##是否允许timestamp类型
enable_timestamp_type = true
#自增列是不是要为无符号型
enable_autoincrement_unsigned = false
#是否允许所有语法(仍受其他开关影响,如删表等).
enable_any_statement = false
#是否允许blob/text/json类型置为not null,默认为false,即不允许
enable_blob_not_null = false
#设置是否支持change column语法,默认值true
enable_change_column = true
#允许列自己设置字符集
enable_column_charset = false
#是否允许删除数据库
enable_drop_database = false
#是否允许删除表
enable_drop_table = true
#sql指纹功能。dml语句相似时，可以根据相同的指纹ID复用explain结果，以减少远端数据库explain操作，并提高审核速度
enable_fingerprint = false
#explain判断受影响行数时使用的规则("first", "max")。 "first": 使用第一行的explain结果作为受影响行数, "max": 使用explain结果中的最大值作为受影响行数
explain_rule = "first"
#是不是支持外键
enable_foreign_key = false
#检查在SQL语句中，是不是有标识符被写成MySQL的关键字，默认值为报警。
enable_identifer_keyword = true
#设置是否启用最小化回滚SQL，当开启时，update的回滚语句仅记录最小化变更(未变更列不再记录), 默认为false
enable_minimal_rollback = false
#创建或者新增列时是否允许列为NULL
enable_nullable = true
#创建索引时是否允许空索引名
enable_null_index_name = false
#order by rand时是不是报错
enable_orderby_rand = false
#是不是支持分区表
enable_partition_table = false
#是否强制主键列必须是int
enable_pk_columns_only_int = false
#Select*时是不是要报错
enable_select_star = true
#是否允许指定表和数据库的字符集
enable_set_charset = true
#是否允许指定表和数据库的排序规则
enable_set_collation = false
#是否允许指定存储引擎,默认为true
enable_set_engine = true
#开启统计功能.
enable_sql_statistic = true
#支持创建和使用视图
enable_use_view = true
#设置是否支持时间为0值，关闭时强制报错。默认值为 true，即开启，此时会基于数据库sql_mode的NO_ZERO_DATE判断是否支持
enable_zero_date = true
#是否记录全量日志
general_log = false
#在解析binlog时,二进制类型如果无法以字符串形式保存,则以十六进制字符串转储(影响类型:binary,varbinary,blob),默认关闭
hex_blob = false
#配置要强制忽略osc的alter子句. 格式为drop index,add column等,多个时以逗号分隔
ignore_osc_alter_stmt = ""
#返回的信息使用语言,可选值en-US,zh-CN
lang = "zh-CN"
#会话在执行SQL时的元数据锁等待超时,单位:秒
lock_wait_timeout = -1
#允许的最大数据包大小.默认为 4194304,单位字节,即4MB
max_allowed_packet = 4194304
#最大char长度,当超出时警告转换为varchar类型
max_char_length = 20
#当DDL预估受影响行数超出设置值时警告,为0时不限制
max_ddl_affect_rows = 0
#配置远端数据库的max_execution_time,为0时不限制
max_execution_time = 0
#设置insert values允许的最大行数.0为不限制
max_insert_rows = 1000
#一个索引最多可指定的列数
max_key_parts = 3
#单表允许的最大索引数
max_keys = 3
#主键最多可指定的列数
max_primary_key_parts = 3
#当update/delete预估受影响行数超出设置值时警告
max_update_rows = 5000
#在多个改同一个表的语句出现是，报错，提示合成一个
merge_alter_table = true
#用以指定建表时必须创建的列。多个列时以逗号分隔(格式: 列名 [列类型,可选])
must_have_columns = ""
#指定不再审核的SQL.该参数指定要跳过的客户端/框架默认SQL,以实现客户端兼容
skip_sqls = ""
#连接远程数据库的默认sql_mode设置
sql_mode = ""
#安全更新.-1表示不做操作,基于远端数据库,0表示关闭安全更新,1表示开启安全更新
sql_safe_updates = -1
#支持的字符集,多个时以逗号分隔
support_charset = "utf8,utf8mb4"
#支持的排序规则,多个时以逗号分隔
support_collation = ""
#支持的存储引擎类型.默认为innodb,此处可以设置多个,以逗号分隔,或者修改默认的存在引擎类型
support_engine = "innodb"
#普通索引前缀，默认为 idx_, 受审核参数 check_index_prefix 影响。为空时不限制
index_prefix = "idx_"
#唯一索引前缀，默认为 uniq_, 受审核参数 check_index_prefix 影响。为空时不限制
uniq_index_prefix = "uniq_"
#表名前缀,默认为空,即不限制
table_prefix = ""
# 是否跳过goinception用户权限校验, 默认跳过
skip_grant_table = true

[inc_level]
#insert语句需要指定字段列表.
er_with_insert_field = 2 
#请指定where条件
er_no_where_condition = 1
#update/delete语句不允许Limit.
er_with_limit_condition = 2
#update/delete语句不允许Order by.
er_with_orderby_condition = 2
#不允许'select *'语法.
er_select_only_star = 1
#不允许'Order by rand'语法.
er_ordery_by_rand = 1
#列 '%s' 数据类型(%s)不支持.
er_invalid_data_type = 2
#不允许使用外键(表 '%s'). 
er_not_allowed_nullable = 2                                                                      
#索引 '%s'指定了太多的字段(表 '%s'), 最多允许 %d 个字段.
er_too_many_key_parts = 1
#预计一次更新(%d行)超过 %d 行.
er_udpate_too_much_rows = 2
#一次新增(%d行)超过 %d 行.
er_insert_too_much_rows = 2
#预计影响行数(%d行)超过 %d 行.
er_change_too_much_rows = 1
#表 '%s' 指定了太多索引, 最多允许 %d 个.
er_too_many_keys = 2                                        
# 表名需要指定'%s'前缀
er_table_prefix = 1
#允许的字符集为: '%s'(表'%s').
er_table_charset_must_utf8 = 1                                                                 
#表 '%s' 禁止设置字符集!                                                        
er_table_charset_must_null = 1
#表 '%s' 需要设置注释.
er_table_must_have_comment = 2                                                                  
#列 '%s' 需要设置注释(表'%s').
er_column_have_no_comment = 2
#表 '%s' 需要设置主键. 
er_table_must_have_pk = 2                                                                       
#不允许创建分区表.
er_partition_not_allowed = 1                                                                          
#不允许使用enum类型.
er_use_enum = 1                                                                          
#不允许使用 blob/text 类型(列'%s'). 
er_use_text_or_blob = 0
#索引 '%s' 需要指定'%s'前缀(表'%s'). 
er_index_name_idx_prefix = 2
#唯一索引 '%s' 需要指定'%s'前缀(表'%s').
er_index_name_uniq_prefix = 2
# 自增列建议设置无符号标志unsigned(表'%s').                                                                          
er_autoinc_unsigned = 1
#列 '%s' 建议设置为varchar类型.
er_char_to_varchar_len = 2                                                             
#建议自增列初始值置为 1.                                                         
er_inc_init_err = 1                                                 
#自增列需要设置为int或bigint类型. 
er_set_data_type_int_bigint = 2                                                                
#请设置timestamp列 '%s' 的默认值.                                                                      
er_timestamp_default = 1
#表 '%s' 列 '%s' 禁止设置字符集或排序规则
er_charset_on_column = 2                                                             
#自增列('%s')建议命名为'ID'.
er_auto_incr_id_warning = 1                                                              
#表 '%s' 的多个alter操作请合并成一个.
er_alter_table_once = 2                                                     
#BLOB,TEXT,GEOMETRY或JSON列 '%s' 禁止设置默认值.                                                                    
er_blob_cant_have_default = 2                                                          
#列 '%s' 请设置默认值(表'%s')
er_with_default_add_column = 1  
#TEXT/BLOB 列 '%s' 禁止设置为not null(表'%s').
er_text_not_nullable_error = 1
#表定义不正确,只能有一个TIMESTAMP字段在DEFAULT或ON UPDATE指定CURRENT_TIMESTAMP.
er_too_much_auto_timestamp_cols = 2
#标识符 '%s' 是MySQL关键字.
er_ident_use_keyword = 1                                                
#标识符 '%s' 无效, 允许字符为 [a-z|A-Z|0-9|_]. 
er_invalid_ident = 2                                                                   
#主键列 '%s' 建议使用int或bigint类型(表'%s'.'%s').
er_pk_cols_not_int = 0                                                 
#表 '%s'.'%s' 主键指定了太多的字段, 最多允许 %d 个字段 
er_pk_too_many_parts = 2
#类型转换警告: 列 '%s' %s -> %s.
er_change_column_type = 1                                                                 
#禁止指定字符集: '%s'
er_cant_set_charset = 1                                            
#禁止指定排序规则: '%s'
er_cant_set_collation = 2
#禁止指定存储引擎:'%s'
er_cant_set_engine = 0
#表必须包含以下列: '%s'. 
er_must_have_columns = 0
#列: '%s' 必须建索引.
er_columns_must_have_index = 0
#列: '%s' 类型必须为 '%s',当前为 '%s'
er_columns_must_have_index_type_err = 1
#MariaDB v%d 对回滚支持不完美,请注意确认回滚语句是否正确 
er_mariadb_rollback_warn = 1
#不允许使用json类型(列'%s'). 
er_json_type_support  = 1
#不允许改变列顺序(列'%s'). 
er_cant_change_column_position = 1
#不允许change column语法(列'%s').                                                                 
er_cant_change_column = 0                                                                          
#列 '%s' 建议设置为 decimal 类型. 
er_float_double_to_decimal = 2                                                                         
#可能是错误语法!更新多个字段时请使用逗号分隔.                                                         
er_wrong_and_expr = 2
#join语句请指定on子句.
er_join_no_on_condition = 1
#不允许隐式类型转换(列'%s.%s',类型'%s').
er_implicit_type_conversion = 1
#请确认是否要在where条件中使用值表达式.
er_use_value_expr = 1
#不允许创建或使用视图 '%s'.
er_view_support = 2
#不正确的时间:'%v'(列 '%s')
er_incorrect_datetime_value = 2
#列'%s'指定长度过长(自定义上限为%d) 
er_max_varchar_length = 2

[osc]

# 用来设置在arkit返回结果集中，对于原来OSC在执行过程的标准输出信息是不是要打印到结果集对应的错误信息列中，
# 如果设置为1，就不打印，如果设置为0，就打印。而如果出现了错误，则都会打印。默认值：OFF
osc_print_none = true

# 对应参数pt-online-schema-change中的参数--print。默认值：OFF
osc_print_sql =true

# 全局的OSC开关。默认值：OFF
osc_on = true

# 这个参数实际上是一个OSC开关，如果设置为0，则全部ALTER语句都使用OSC方式，
# 如果设置为非0，则当这个表占用空间大小大于这个值时才使用OSC方式。
# 单位为M，这个表大小的计算方式是通过语句
# select (DATA_LENGTH + INDEX_LENGTH)/1024/1024 from information_schema.tables
# where table_schema = 'dbname' and table_name = 'tablename' 来实现的。默认值：16
# [0-1048576]
osc_min_table_size = 16

# 对应参数pt-online-schema-change中的参数alter-foreign-keys-method，具体意义可以参考OSC官方手册。默认值：none
# [auto | none | rebuild_constraints | drop_swap]
osc_alter_foreign_keys_method = "none"

# 对应参数pt-online-schema-change中的参数recursion_method，具体意义可以参考OSC官方手册。默认值：processlist
# [processlist | hosts | none]
osc_recursion_method = "processlist"

# 对应参数pt-online-schema-change中的参数--max-lag。默认值：3
osc_max_lag = 3

# 类似--max-lag，检查集群暂停流量控制所花费的平均时间（仅适用于PXC 5.6及以上版本,会自动检测)
osc_max_flow_ctl = -1

# 对应参数pt-online-schema-change中的参数 --sleep 默认值：0.0
osc_sleep = 0.0

# 对应参数pt-online-schema-change中的参数 --set-vars lock_wait_timeout=?
osc_lock_wait_timeout = 60

# 对应参数pt-online-schema-change中的参数--[no]check-alter。默认值：ON
osc_check_alter = true

# 对应参数pt-online-schema-change中的参数--[no]check-replication-filters。默认值：ON
osc_check_replication_filters = true

# 检查是否为添加唯一索引,如果是,则禁止
osc_check_unique_key_change = true

# 对应参数pt-online-schema-change中的参数--[no]drop-old-table。默认值：ON
osc_drop_old_table = true

# 对应参数pt-online-schema-change中的参数--[no]drop-new-table。默认值：ON
osc_drop_new_table = true

# 对应参数pt-online-schema-change中的参数--max-load中的thread_running部分。默认值：80
osc_max_thread_running = 80

# 对应参数pt-online-schema-change中的参数--max-load中的thread_connected部分。默认值：1000
osc_max_thread_connected = 1000

# 对应参数pt-online-schema-change中的参数--critical-load中的thread_running部分。默认值：80
osc_critical_thread_running = 80

# 对应参数pt-online-schema-change中的参数--critical-load中的thread_connected部分。默认值：1000
osc_critical_thread_connected = 1000

# 对应参数pt-online-schema-change中的参数--chunk-time。默认值：1
osc_chunk_time = 1.0

# 对应参数pt-online-schema-change中的参数--chunk-size-limit。默认值：4
osc_chunk_size_limit = 4

# 对应参数pt-online-schema-change中的参数--chunk-size。默认值：1000
osc_chunk_size = 1000

# 对应参数pt-online-schema-change中的参数--check-interval，意义是Sleep time between checks for --max-lag。默认值：5
osc_check_interval = 5

osc_bin_dir = "/usr/local/bin"

[ghost]

ghost_on = false
ghost_allow_on_master = true
ghost_assume_rbr = true
ghost_chunk_size = 1000
ghost_concurrent_rowcount = true
ghost_cut_over = "atomic"
ghost_cut_over_lock_timeout_seconds = 3
ghost_default_retries = 60
ghost_heartbeat_interval_millis = 500
ghost_max_lag_millis = 1500
ghost_approve_renamed_columns = true
ghost_exponential_backoff_max_interval = 64
ghost_dml_batch_size = 10
ghost_ok_to_drop_table = true
ghost_skip_foreign_key_checks = true

**Comment by hanchuanchuan** [comment]
请了解MySQL的执行计划. 受影响行数是预估的. 如果想在审核阶段获取真实行数, 请查阅文档 `real_row_count` https://hanchuanchuan.github.io/goInception/params.html
