### ISSUE TITLE
update语句提示语法错误

### ISSUE THREAD

**Issue by st1266** [hanchuanchuan/goInception#54]
**描述**
使用Archery审核平台，操作sql上线时，SQL检测报错，提示语法错误，但是语法正确，
在另一个测试库里，建相同表，插入相同数据，检测同样的update语句没有问题。
线上数据库是percona mysql 5.5.61，测试环境是percona mysql 5.7.26。
怀疑是goinception对版本mysql的语法解析问题？

**重现**
![image](https://user-images.githubusercontent.com/52566924/61345513-100fcb80-a888-11e9-803b-50de327dab83.png)
![image](https://user-images.githubusercontent.com/52566924/61345516-14d47f80-a888-11e9-9c69-a562032d85de.png)

**环境**
 - 数据库: mysql
 - 版本: 5.5.61有问题，5.7.26没问题

**Comment by hanchuanchuan** [comment]
MySQL 5.5 版本不支持explain update操作。

**Comment by hanchuanchuan** [comment]
已添加对MySQL 5.5版本的支持。
注意：现阶段对5.5版本 timestamp的审核暂不完整，有什么问题欢迎及时反馈。
