### ISSUE TITLE
对 algorithm=instant 语法支持

### ISSUE THREAD

**Issue by lisonlin22** [hanchuanchuan/goInception#540]
mysql 8.0 支持 algorithm=instant 语法。 goInception 不支持。 在 parser/parser.y  1368行 增加 INSTANT 重新 go build 一下即可
For example：

AlterAlgorithm:
	"DEFAULT"
|	"INPLACE"
|	"COPY"
|	"INSTANT"

**Comment by hanchuanchuan** [comment]
Fixed 35fde7da3e560999bea2069336f4d68274b9cee4
请升级到版本后`v1.3.0-46`重试.
