### ISSUE TITLE
goinception 不支持select 语句么

### ISSUE THREAD

**Issue by bruceyanghui** [hanchuanchuan/goInception#543]
**描述**
无法对select 的语句进行返回， 'error_message': 'Not supported statement type.'

**重现**

inception_magic_start;
use testdb; 
select c1,m1 from t1;
inception_magic_commit;'''

报错：  'Not supported statement type.'

**环境**
mysql 5.7

**参数**
可能与问题相关的设置参数

**Comment by wangjiqing** [comment]
SQL上线功能为什么要执行 DQL 语句？

**Comment by hanchuanchuan** [comment]
select语句可以审核, 审核的目的是检查语法是否有误. 但不支持执行.
