### ISSUE TITLE
create unique index时提示索引不是idx_开头

### ISSUE THREAD

**Issue by lprincewz** [hanchuanchuan/goInception#544]
**描述**
create unique index uniq_col1 on tab1 (col1);
index 'uniq_col1' in table 'tab1' need 'idx_' prefix.
goInception把唯一索引识别成了创建普通索引了

**Comment by hanchuanchuan** [comment]
请升级到最新版后重试, 这个问题已修复, 只是忘记具体修复的版本号了.
