### ISSUE TITLE
生成的备份库中的备份信息表名不一致

### ISSUE THREAD

**Issue by FangPengbo** [hanchuanchuan/goInception#545]
**描述**
生成备份库的表名称为何有大写有小写？

**重现**
配置备份库，执行sql开启备份功能
切换备份库，执行sql开启备份功能

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.21]

第一次生成的备份库中的备份信息表叫  $_$inception_backup_information$_$
第二次生成的备份库中的备份信息表叫  $_$Inception_backup_information$_$

为什么会出现这种情况呢

**Comment by hanchuanchuan** [comment]
是否更改了参数`lower_case_table_names`.
代码中写的是`$_$Inception_backup_information$_$`,而如果不区分大小写的话, 则会自动转为全小写.

**Comment by FangPengbo** [comment]
> 是否更改了参数`lower_case_table_names`. 代码中写的是`$_$Inception_backup_information$_$`,而如果不区分大小写的话, 则会自动转为全小写.

确实是这个问题，两个备份库设置的 lower_case_table_names 参数是不同的。🤦‍♂️
谢谢👍
