### ISSUE TITLE
Failed to register slave; too long 'report-password'

### ISSUE THREAD

**Issue by FangPengbo** [hanchuanchuan/goInception#546]
**描述**
在审核通过执行阶段
goinception返回的状态为 Execute Successfully Backup failed
错误信息为：Backup：ERROR 1105(HY000):Failed to register slave; too long 'report-password'

**重现**
开启备份功能之后，执行sql。

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.21]

**参数**
[ghost]

ghost_on = true
ghost_initially_drop_socket_file = true
ghost_initially_drop_ghost_table = true
ghost_initially_drop_old_table = true
osc_max_thread_connected = 10000
osc_critical_thread_connected = 10000

**Comment by hanchuanchuan** [comment]
解析binlog需要模拟从库来拉取binlog，但无法注册slave，是否使用了proxy?

**Comment by FangPengbo** [comment]
> 解析binlog需要模拟从库来拉取binlog，但无法注册slave，是否使用了proxy?

没有使用proxy，这个错误是偶发的。

**Comment by FangPengbo** [comment]
> 解析binlog需要模拟从库来拉取binlog，但无法注册slave，是否使用了proxy?

确实是使用代理了，这个有办法可以解决吗

**Comment by FangPengbo** [comment]
https://github.com/github/gh-ost/issues/484
和gh-ost遇到的这个问题一样吗，模拟从库来拉取binlog的时候密码超过32 个字符的长度吗

**Comment by FangPengbo** [comment]
更改从库的密码长度不超过32位
