### ISSUE TITLE
执行SQL时因为备份失败导致异常

### ISSUE THREAD

**Issue by tanglu86** [hanchuanchuan/goInception#547]
**环境**
 - 数据库: mysql5.7
 - Archery:1.8..4
 - Goinception:1.3.0-42

goInception配置文件在INC模块下定义了backup相关信息，通过Archery连接备份库测试正常，执行SQL语句报错Invalid remote backup information.
![1](https://user-images.githubusercontent.com/38269740/210942519-c7ed5d71-9487-4ef0-9acb-bd6511faa44a.jpg)
![2](https://user-images.githubusercontent.com/38269740/210942526-8aeb1ef1-bff0-4643-8641-075ca931b3b7.png)

**Comment by tanglu86** [comment]
配置文件问题

**Comment by jeromeji** [comment]
> 配置文件问题

同遇到了，请问是哪里的配置问题。。。

**Comment by cqvienet** [comment]
我也遇到这个问题，goInception版本号v1.3.0-84-gb0cbfd0737，archery版本号v1.10.0，archery界面上也可以正常连接数据库，请问是哪里出了问题？
