### ISSUE TITLE
optimize table xxxx; 解析失败

### ISSUE THREAD

**Issue by FangPengbo** [hanchuanchuan/goInception#548]
**描述**
对 optimize table xxxx;  语句执行检测；goinception报解析失败的错误。

**重现**

对 optimize table xxxx;  语句执行检测；

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.21]

查看goinception日志如下
`level=error msg="con:73 解析失败! line 1 column 929 near \"optimize table yearning_test.testaaa;inception_magic_commit\" " file=session_inception.go func=executeInc line=219`

**Comment by hanchuanchuan** [comment]
运维命令暂不支持。

**Comment by FangPengbo** [comment]
> 运维命令暂不支持。

好的
