### ISSUE TITLE
Skip backup because there is no table structure information.

### ISSUE THREAD

**Issue by FangPengbo** [hanchuanchuan/goInception#550]
**描述**
开启备份功能，执行 `DROP TABLE xxxx; ` 执行成功并备份成功，备份语句生产了CREATE TABLE XXX；
但是在执行 `TRUNCATE TABLE xxxx;` 语句时执行成功却跳过了备份。
errMsg为：`Skip backup because there is no table structure information`

**重现**

开启备份功能执行 `TRUNCATE TABLE xxxx;` 语句

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.21]

**Comment by hanchuanchuan** [comment]
`TRUNCATE TABLE`语法不会生成binlog记录，也不会影响表结构，所以无法备份，也不会生成备份信息。

**Comment by FangPengbo** [comment]
> `TRUNCATE TABLE`语法不会生成binlog记录，也不会影响表结构，所以无法备份，也不会生成备份信息。

对。
