### ISSUE TITLE
check_dml_where=true 配置无效

### ISSUE THREAD

**Issue by pengkang1991** [hanchuanchuan/goInception#553]
**描述您想要的功能：**
执行update 语句的时候 如果没有where函数就会报错的功能

**描述您考虑过的解决/替代方案：**
我在config.toml里面配置了 check_dml_where=true，但是无效。

**可参考文档,资料,引用等：**

config.toml

[inc]
#设置禁止的数据类型
disable_types = "blob,enum,set,bit"
enable_blob_type = true
check_dml_where = false

版本：goinception:v1.3.0
部署方式：docker

**Comment by hanchuanchuan** [comment]
请连接到goinception执行管理命令来检查内存中的配置以验证修改是否已生效:
```inc show variables like 'check_dml_where';```
