### ISSUE TITLE
goInception设置 sql_safe_updates=1有些mysql实例update语句where没有走索引检测通过

### ISSUE THREAD

**Issue by liebao520** [hanchuanchuan/goInception#557]
**描述**
对问题简单清晰的描述
goInception设置 sql_safe_updates=1  ，两个相同版本，不同ip的mysql，update语句where条件都没有走索引，SQL检测时一个提示:You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column.  一个提示pass
**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.36]

**参数**
可能与问题相关的设置参数
goInception sql_safe_updates=1

**Comment by hanchuanchuan** [comment]
这个提示是后端MySQL本身返回的. 
请检查同样的SQL在两个MySQL上执行explain查看执行计划的差异.
