### ISSUE TITLE
[事务相关] 多条DML语句, 其中一条发生错误时，其他语句正常执行

### ISSUE THREAD

**Issue by xiaoshenwei** [hanchuanchuan/goInception#567]
**描述**
多条DML语句, 当某一条SQL 执行失败， 以后SQL不在执行， 之前SQL执行正常

期望:
SQL1 成功
SQL2 失败
SQL3 成功
SQL4 成功

现象:
SQL1 成功
SQL2 失败
SQL3 不执行
SQL4 不执行

**参数**
--trans=0;

**Comment by hanchuanchuan** [comment]
现在是这个逻辑没错, 没有忽略错误强制继续的参数. 建议由调用端自行实现.
