### ISSUE TITLE
MySQL存储过程的支持

### ISSUE THREAD

**Issue by waitspring** [hanchuanchuan/goInception#568]
https://github.com/hanchuanchuan/goInception/issues/256
@hanchuanchuan @LeoQuote
Inception 如果没有计划支持存储过程的话，能否基于配置文件设计一个参数，用于控制是否放行不支持审核的语句：由用户决定是否在冒风险的条件下，把未经审核的语句直接放行掉。
这样做的原因在于，本身Archery项目里面也有审核引擎，可以基于其内置的审核引擎来做二次开发，允许上线使用存储过程。
两位作者联合考虑一下呢？

**Comment by yangjule126** [comment]
同上

**Comment by hanchuanchuan** [comment]
> 

参考 https://cn.pingcap.com/blog/tidb-source-code-reading-5
