### ISSUE TITLE
goInception 支持 my2sql 咨询

### ISSUE THREAD

**Issue by Jacklli** [hanchuanchuan/goInception#576]
**描述您想要的功能：**
希望 goInception 支持 my2sql， binlog2sql 的性能比较差。

**描述您考虑过的解决/替代方案：**
希望 goInception 支持 my2sql，binlog2sql 的性能比较差。

**可参考文档,资料,引用等：**
希望 goInception 支持 my2sql

goInception 是否有支持 my2sql 的计划呢？

**Comment by hanchuanchuan** [comment]
goInception使用的解析库和my2sql一致, 均为[go-mysql](https://github.com/go-mysql-org/go-mysql), 应该不存在你担心的问题.
