### ISSUE TITLE
怎么让goinception不检查after列的存在性

### ISSUE THREAD

**Issue by czxin788** [hanchuanchuan/goInception#578]
**描述**
怎么让goinception不检查after列的存在性

**重现**
ALTER TABLE t1 ADD COLUMN convert_num decimal(8, 2) UNSIGNED DEFAULT NULL COMMENT 'test';
审核成功

ALTER TABLE t1 ADD COLUMN convert_num_unit varchar(38) DEFAULT '' COMMENT 'test' AFTER convert_num;
审核报： t1.convert_num 不存在

其实是因为第一个sql的convert_num列还没加上呢，所以第二个sql报错了。怎么让goinception不检查after列的存在性

**环境**
 - 数据库: mysql
 - 版本: 5.7.21
- goinception版本：v1.3.0-72

**参数**

**Comment by hanchuanchuan** [comment]
建议合并到同一个`alter table`语句中, 如果是大表的话, 拆分为多条DDL对数据库的影响会比较大. 
另外如果是已存在的列, After校验逻辑是没问题的.
