### ISSUE TITLE
[bug] 不支持json类型

### ISSUE THREAD

**Issue by benevolence-doctor** [hanchuanchuan/goInception#58]
**描述**
alter table wb_today_baby add column self_like_s3 json DEFAULT null COMMENT '自定义点赞场景3';
添加json类型字段的时候goinception报错：
不允许使用json类型(列'self_like_s3').

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 8.01]

**Comment by hanchuanchuan** [comment]
查看 审核选项 https://hanchuanchuan.github.io/goInception/options/
设置参数 ` enable_json_type `

**Comment by benevolence-doctor** [comment]
已解决 谢谢
