### ISSUE TITLE
JSON字符串属性不支持

### ISSUE THREAD

**Issue by yuexiaofengqing** [hanchuanchuan/goInception#582]
**描述**
当我使用JSON的字段属性时，检查报错TEXT/BLOB Column 'messageBody' in table 'retry_message' can't  been not null.
**重现**
建表语句如下：
CREATE TABLE `retry_message` (
  `id` bigint(20) unsigned NOT NULL,
  `messageBody` json NOT NULL ,
  `messageType` varchar(30) NOT NULL ,
  `messageStatus` varchar(30) NOT NULL 
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_messageStatus` (`messageStatus`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT;

**环境**
 - 数据库: [mysql/mariadb]
 MySQL 
 - 版本: [例如 5.7.21]
5.7.38
**参数**
可能与问题相关的设置参数
已经设置enable_json_type = true

**Comment by 18805407688** [comment]
兄弟，你messageStatus 字段少一个逗号

**Comment by hanchuanchuan** [comment]
请设置 `er_text_not_nullable_error` ERROR LEVEL先忽略, 
```inc set level er_text_not_nullable_error=0;``` (支持会话级别设置)
后续将优化JSON类型审核逻辑.
