### ISSUE TITLE
must_have_columns 设置不符合预期

### ISSUE THREAD

**Issue by qinzhi1209** [hanchuanchuan/goInception#583]
**描述**
设置了参数must_have_columns = "create_time,modify_time,rec_status" ，但是当建表语句中没有create_time或者其他两个字段时，审核状态只是warning不是error

**重现**
<img width="1120" alt="image" src="https://github.com/hanchuanchuan/goInception/assets/49607830/c3933e9a-9714-482d-b068-6e0172ef50ed">

**环境**
 - 数据库: [mysql]
 - 版本: [例如 8.0]

**参数**
must_have_columns

**Comment by miaoyongbin** [comment]
设置er_must_have_columns级别为2即可

**Comment by qinzhi1209** [comment]
好的，谢谢，但是我设置了如下：
disable_types = "timestamp"
er_disable_types = 2
当建表字段类型是timestamp报错只是warning而不是error
<img width="1133" alt="image" src="https://github.com/hanchuanchuan/goInception/assets/49607830/2e10895e-deae-4d0f-a595-fd4d1ae202c9">

**Comment by hanchuanchuan** [comment]
设置ERROR LEVEL参数`er_invalid_data_type`.
请查阅文档和内置函数`inc show levels`来设置告警级别.
