### ISSUE TITLE
能否支持表的truncate操作

### ISSUE THREAD

**Issue by songtao12** [hanchuanchuan/goInception#584]
**描述您想要的功能：**
目前系统审核truncate语句报错如下：Drop/truncate 't' is not allowed, please replace with alter rename statement.
线上SQL操作有trucate表操作的需求，需要平台支持truncate语句的审核

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by includeMaple** [comment]
修改配置文件enable_drop_table为true，然后重启服务
