### ISSUE TITLE
delete b.* 报语法错误

### ISSUE THREAD

**Issue by czxin788** [hanchuanchuan/goInception#585]
**描述**
mysql可以正常执行：delete b.* from aaa a left join bbb b on a.numericalorder = b.numericalorder where enterpriseid in (116765594498537) and a.datadate between '2023-01-01' and '2023-05-31' and b.accochecktype in (201708010104402109, 201708010104402114)

但是goinception审核报错： 
line 1 column 18 near "* from aaa a left join bbb b on a.numericalorder = b.numericalorder where enterpriseid in (116765594498537) and a.datadate between '2023-01-01' and '2023-05-31' and b.accochecktype in (201708010104402109, 201708010104402114)"

**重现**
模拟重现的步骤

**环境**
 - 数据库: mysql 5.7.34
 - goinception版本：
 /goInception -V
Release Version: v1.3.0-68-g2f47aef-dirty
Git Commit Hash: 2f47aef6f7ab0428f413e4064148b94cee50a775
Git Branch: master
UTC Build Time: 2023-03-20 15:04:09
GoVersion: go version go1.14.15 linux/amd64

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
请改为 `delete b from aaa a left join bbb b ...`
属于TiDB语法兼容性问题, 有些特殊写法不支持.
参考 #505
