### ISSUE TITLE
DDL语句中出现特殊字符, 审核通过, 执行失败

### ISSUE THREAD

**Issue by xiaoshenwei** [hanchuanchuan/goInception#598]
**描述**
SQL语句中出现某些特殊字符

**重现**
```sql
CREATE TABLE `commodity_sku_sell_channel_sales` (
  `id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'id',
  `createTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifyTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `skuId` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'skuId',
  `sellChannel` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '销售渠道',
  `salesNum` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '销量',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_skuId_sellChannel` (`skuId`,`sellChannel`)
) DEFAULT CHARSET=utf8mb4 COMMENT='sku渠道销售信息'
```
<img width="545" alt="image" src="https://github.com/hanchuanchuan/goInception/assets/104475958/a1a045cb-fa1e-41ef-a793-8573d61fe503">

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

goInception 审核通过 但MySQL执行失败
![image](https://github.com/hanchuanchuan/goInception/assets/104475958/bdfbcd84-59fd-41d0-989c-e3959d30253e)

**Comment by hanchuanchuan** [comment]
goinception未复现该问题, 请检查goinception日志来验证提交的SQL是否正确.

**Comment by xiaoshenwei** [comment]
![image](https://github.com/hanchuanchuan/goInception/assets/104475958/c1d84a5a-befe-468a-ae1b-70f1c6456a52)
