### ISSUE TITLE
SQL检测 扫描/影响行数 有问题与实际不符

### ISSUE THREAD

**Issue by a8159236** [hanchuanchuan/goInception#605]
**描述**
使用的是archery管理平台，SQL检测 扫描/影响行数 有问题，实际上只有两行数据修改，但是检测结果却显示影响行数有1111行？影响行数完全是 goinception 的返回，是不是goinception检测有问题？

**重现**
![企业微信截图_16945765839281](https://github.com/hanchuanchuan/goInception/assets/32159630/bae2456b-7b6f-40b6-822b-0e316f5bc4c0)
![企业微信截图_16945765383278](https://github.com/hanchuanchuan/goInception/assets/32159630/bb49ad4a-0096-41fe-b51b-5d7c34564f2a)

**环境**
 - 数据库: [mysql]
 - 版本: [5.6]

**Comment by a8159236** [comment]
![image](https://github.com/hanchuanchuan/goInception/assets/32159630/f79ccb12-bceb-470e-9236-e59fc364d5a6)
wokan我看有人遇到同样问题是要修改real_row_count参数，这个参数怎么修改，我是用docker启动的goinception

**Comment by a8159236** [comment]
是直接在执行语句上面添加这一个参数吗？
![image](https://github.com/hanchuanchuan/goInception/assets/32159630/7db94bfe-5637-4e1d-9a86-49c5beb393c0)

**Comment by a8159236** [comment]
![image](https://github.com/hanchuanchuan/goInception/assets/32159630/0de69841-896f-405d-8464-d044e87fe114)
是通过修改这个参数为true吗？等同于real_row_count ？

**Comment by hanchuanchuan** [comment]
请查看使用文档：https://hanchuanchuan.github.io/goInception/params.html

**Comment by syz951127** [comment]
> 请查看使用文档：https://hanchuanchuan.github.io/goInception/params.html

我这边加上了这个--real_row_count=true 
同样的where条件 查询和 update预估的值还是不一样

**Comment by syz951127** [comment]
> > 请查看使用文档：https://hanchuanchuan.github.io/goInception/params.html
> 
> 我这边加上了这个--real_row_count=true 同样的where条件 查询和 update预估的值还是不一样

抓包看了下。 发现是goinception根据dml还原select语句时 条件变化了
```sql
# 更新语句
update tb_1 set column_a=1 where column_b like '%\_123';
# 还原的查询语句
select count(*) from tb_1 where column_b like '%_123';
```
