### ISSUE TITLE
SQL检测 扫描/影响行数 SQL存在转义符时与实际不符

### ISSUE THREAD

**Issue by BearGuardian** [hanchuanchuan/goInception#638]
**描述**
我这边配置有加上--real_row_count=true
同样的where条件 查询和 update预估的值还是不一样。
通过抓包发现当语句存在转义符时被忽略了

**重现**
```sql
# 更新语句
update tb_1 set column_a=1 where column_b like '%\_123';
# 还原的查询语句
select count(*) from tb_1 where column_b like '%_123';
```

**环境**
 - 数据库: mysql
 - 版本: 8.0.30

**Comment by zmix999** [comment]
应该是sqlparser问题，可以使用ESCAPE指定转义符号处理

**Comment by zmix999** [comment]
可以看下我fork的分支https://gitee.com/zhoujin826/goInception，升级了相关依赖包，解决了这个问题

**Comment by BearGuardian** [comment]
> fork

get👍   我试下

**Comment by BearGuardian** [comment]
> 可以看下我fork的分支[https://gitee.com/zhoujin826/goInception，升级了相关依赖包，解决了这个问题](https://gitee.com/zhoujin826/goInception%EF%BC%8C%E5%8D%87%E7%BA%A7%E4%BA%86%E7%9B%B8%E5%85%B3%E4%BE%9D%E8%B5%96%E5%8C%85%EF%BC%8C%E8%A7%A3%E5%86%B3%E4%BA%86%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98)

get 👍 我试一下

**Comment by hanchuanchuan** [comment]
@zmix999 👍👍 感谢贡献! 稍后我将合并到goinception.
