### ISSUE TITLE
Identifier 'user' is keyword in MySQL

### ISSUE THREAD

**Issue by yyukai** [hanchuanchuan/goInception#64]
**描述**
语法树无法解析包含 mysql关键字的sql语句。

**重现**
select * from `user`;

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by hanchuanchuan** [comment]
检查一下参数 `enable_identifer_keyword` 设置
