### ISSUE TITLE
8.0版本在add和modify都包含的DDL中，会禁用osc

### ISSUE THREAD

**Issue by BigChaoChao** [hanchuanchuan/goInception#668]
**描述**
8.0版本在add和modify都包含的DDL中，会禁用osc，变成直连OnlineDDL

**Comment by hanchuanchuan** [comment]
在MySQL v8.0如果有add column时会自动禁用osc, MySQL v8.0支持 ALGORITHM=INSTANT方式添加立即添加列.
该判断在同一alter table语句时会有问题, 将在下个版本升级. #673

**Comment by hanchuanchuan** [comment]
请升级到v1.3.0-94版本后重试. (添加了新的控制参数`enable_ddl_instant`, 默认为`true`, 设为false即可主动关闭该功能)
