### ISSUE TITLE
tidb实例中执行ddl显示Execute: Unexpected database port reported: 10171.

### ISSUE THREAD

**Issue by nieen** [hanchuanchuan/goInception#677]
**描述**
在对tidb实例中执行ddl时，审核通过的ddl语句，执行信息显示Execute: Unexpected database port reported: 10171.
不是所有tidb实例，是部分tidb实例会出现这个问题，但是不知道从哪里入手排查。
请问大家有遇到过类似问题吗？有没有排查思路什么的。

**重现**

**环境**
 - 数据库: [tidb]
 - 版本: [5.7.25-TiDB-v6.5.1]

**参数**
可能与问题相关的设置参数

**Comment by nieen** [comment]
10171 端口不是访问tidb实例的端口

**Comment by zmix999** [comment]
看下错误日志呢

**Comment by nieen** [comment]
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/d16ecd7f-a5da-47c2-b60f-b3a89dac7fc9">
这个是tidb执行ddl时的日志，发现一个规律，在大数据量的情况下，tidb 执行 ddl就会出现这个问题。 @zmix999 大哥，有啥思路嘛

**Comment by nieen** [comment]
测试表有523565行数据，
测试表结构：
CREATE TABLE `t_fxr_test` (
  `key_id` varchar(10) NOT NULL,
  `gw` varchar(8) NOT NULL,
  `ips` varchar(50) NOT NULL,
  `tunnel_type` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`key_id`)
  /*T![clustered_index] CLUSTERED */
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COLLATE = utf8_bin

测试执行语句：alter table t_fxr_test modify key_id varchar(20) default '' not null

**Comment by nieen** [comment]
> <img alt="image" width="1130" src="https://private-user-images.githubusercontent.com/77630269/375694711-d16ecd7f-a5da-47c2-b60f-b3a89dac7fc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjUzNzksIm5iZiI6MTcyODcyNTA3OSwicGF0aCI6Ii83NzYzMDI2OS8zNzU2OTQ3MTEtZDE2ZWNkN2YtYTVkYS00N2MyLWI2MGYtYjNhODlkYWM3ZmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MjQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYWVmNjg4NTFkMGM0ZGNkODhiYThmYzVlYTVhMjQ1NzYwNDRjMDc2ZTljMzI0NjIwZTUxOTI2ODIwZDliNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8tjdhpD38ri1_g2knp7sz0BF0j_vRHnP9VPxBS6D40I"> 这个是tidb执行ddl时的日志，发现一个规律，在大数据量的情况下，tidb 执行 ddl就会出现这个问题。 @zmix999 大哥，有啥思路嘛

**Comment by nieen** [comment]
进过测试好像与数据量没有必然的关系，在重复执行测试中，又成功了

**Comment by nieen** [comment]
@zmix999 大哥，实在抱歉打扰你，不知道可不可以帮忙看看这个情况啊

**Comment by zmix999** [comment]
![image](https://github.com/user-attachments/assets/2ffe9cfe-34f4-4aa4-86da-677a3b8afdb5)
tidb不支持gh-ost这个工具吧， 这工具只支持mysql， goinception执行ddl调用gh-ost工具有一个表大小的判断，

**Comment by nieen** [comment]
@zmix999  大哥， 方便指出一下你这里讲的调用gh-ost工具时对表大小进行判断的代码在哪里吗？我看了下没有找到，下面图中看起来也没有对表大小有判断的点
![image](https://github.com/user-attachments/assets/42e1b86a-72e5-433f-a87f-71282a1ba2c5)

就是在调用gh-ost工具时，如果表超过预期的大小，报错显示Unexpected database port reported， 这个好像也不太合理

**Comment by nieen** [comment]
我这边的tidb实例架构是这样的，部署proxySQL, proxySQL下挂多个tidb服务，我这边用goInception连tidb时用的proxySQL的端口

**Comment by zmix999** [comment]
OscMinTableSize
这不是架构的问题，就是gh-ost这种工具就不支持TIDB数据库，这很清楚吧

**Comment by nieen** [comment]
明白的，主要是想捋清楚里面的逻辑。感谢大哥
