### ISSUE TITLE
添加删除外键都会报错Not supported statement type.

### ISSUE THREAD

**Issue by jy3792397** [hanchuanchuan/goInception#68]
**描述**
确认enable_foreign_key=true已打开
执行alter table xxx add constraint FK_xxx foreign key (xxx) references xxx(xxx); 或者 ALTER TABLE xxx DROP FOREIGN KEY xxx;都会报错Not supported statement type.

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
enable_foreign_key

**Comment by hanchuanchuan** [comment]
好的，该问题确实存在，预计近两天修复。

**Comment by hanchuanchuan** [comment]
[v1.0.4](https://github.com/hanchuanchuan/goInception/releases/tag/v1.0.4) 版本更新
