### ISSUE TITLE
set names charset不支持

### ISSUE THREAD

**Issue by lyx-dba** [hanchuanchuan/goInception#69]
**描述**
set names charset不支持

**重现**
![image](https://user-images.githubusercontent.com/49632514/62285015-633c6d80-b487-11e9-8b6a-cef94190c9e0.png)

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.21]

**参数**
enable_set_charset=true

**Comment by hanchuanchuan** [comment]
是的，不支持这个语法，字符集默认是utf8mb4。

**Comment by lyx-dba** [comment]
![image](https://user-images.githubusercontent.com/49632514/62338547-89a3ec80-b50b-11e9-8d42-8dcfb80b4e15.png)
不是说支持set names charset么

**Comment by hanchuanchuan** [comment]
已添加该语法支持，仅支持utf8和utf8mb4字符集。
docker版本已更新，release二进制版本稍后发布。

**Comment by hanchuanchuan** [comment]
[v1.0.4](https://github.com/hanchuanchuan/goInception/releases/tag/v1.0.4) 版本更新
