### ISSUE TITLE
make parser 报错

### ISSUE THREAD

**Issue by WatchLucky** [hanchuanchuan/goInception#71]
因为无法翻墙
 mv  go.mod  go.mod_bak  
 cp   go.mod_wall     go.mod 

make parser 
报错如下：
Parse table entries: 824515 of 2072063, x 16 bits == 1649030 bytes
bin/goyacc -o parser/parser.go parser/parser.y 2>&1 | egrep "(shift|reduce)/reduce" | awk '{print} END {if (NR > 0) {print "Find conflict in parser.y. Please check y.output for more information."; exit 1;}}'
rm -f y.output

**Comment by hanchuanchuan** [comment]
这个是正常的

**Comment by WatchLucky** [comment]
> 这个是正常的
ok，翻墙了。所有的包都能下载  
maker parser  成功

但是 build goInception 的时候报错
go build -o goInception tidb-server/main.go

  
# github.com/hanchuanchuan/goInception/parser
parser\lexer.go:148:26: undefined: yySymType
parser\misc.go:626:24: undefined: yySymType
parser\yy_parser.go:71:11: undefined: yySymType
parser\yy_parser.go:72:9: undefined: yySymType
parser\yy_parser.go:73:9: undefined: yySymType
