### ISSUE TITLE
我建分区表的时候审核报错

### ISSUE THREAD

**Issue by Myshiner** [hanchuanchuan/goInception#81]
**描述**
建分区表审核报错
![image](https://user-images.githubusercontent.com/48242833/64310714-bef09e00-cfd3-11e9-8126-5ce36c89fb0c.png)
**sql语句**
CREATE TABLE entity_cms_mirrordata (
  id int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  topic_id bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '知识点id',
  subject_id int(11) unsigned NOT NULL DEFAULT 0 COMMENT '学科id',
  system_id bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '学生id',
  sourcefrom tinyint(4) unsigned NOT NULL DEFAULT 1 COMMENT '来源: 1 cms后台;2 okay+ ;3 学生端;4 系统推荐',
  status tinyint(4) NOT NULL DEFAULT 1 COMMENT '当前状态1正常2删除',
  studied_status tinyint(4) NOT NULL DEFAULT 0 COMMENT '学习状态: 0 未学完; 1 学完了',
  operator_id int(10) unsigned NOT NULL DEFAULT 0 COMMENT '创建人id',
  create_time datetime NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '创建时间',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_firstscreen tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否是首屏 1是0否',
  topic_type tinyint(4) NOT NULL DEFAULT 1 COMMENT '知识点类型 1 知识点 2 章节',
  sourcefrom_type tinyint(4) NOT NULL DEFAULT 0 COMMENT '来源类型 0系统 1 手动',
  is_mirror tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否在魔镜 1是0否',
  first_create_time datetime NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '创建时间',
  mirror_update_time datetime NOT NULL DEFAULT '1900-01-01 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '魔镜修改时间',
  stage_id int(11) unsigned NOT NULL DEFAULT 1 COMMENT '学段',
  directory_id bigint(20) NOT NULL DEFAULT 0 COMMENT '教材版本体系id',
  kidtype bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'kid及类型',
  PRIMARY KEY (id, system_id) USING BTREE,
  UNIQUE KEY uniq_system_type_topic (system_id, topic_type, topic_id) USING BTREE COMMENT '知识点',
  KEY idx_system_subject (
    system_id,
    studied_status,
    status,
    subject_id,
    is_mirror
  ) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Cms魔镜数据表'
/*!50100 PARTITION BY HASH (system_id)
PARTITIONS 100 */;

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql]
 - 版本: [例如 5.7.24]

**参数**
可能与问题相关的设置参数
max_key_parts | 0 
max_keys      | 0
enable_identifer_keyword | true
enable_partition_table | true

**Comment by hanchuanchuan** [comment]
goInception支持分区表语法，该SQL没有问题，可以到使用的项目下发布该问题。
