### ISSUE TITLE
环境搭建错误

### ISSUE THREAD

**Issue by oyb001** [hanchuanchuan/goInception#82]
### 执行 make parser时报以下错误，网络是正常的，也可以翻墙。
go: google.golang.org/genproto@v0.0.0-20181004005441-af9cb2a35e7f: unrecognized import path "google.golang.org/genproto" (https fetch: Get https://google.golang.org/genproto?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: google.golang.org/genproto@v0.0.0-20180817151627-c66870c02cf8: unrecognized import path "google.golang.org/genproto" (https fetch: Get https://google.golang.org/genproto?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding gopkg.in/mgo.v2 v2.0.0-20180705113604-9856a29383ce
go: gopkg.in/mgo.v2@v2.0.0-20180705113604-9856a29383ce: git fetch -f https://gopkg.in/mgo.v2 refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/ouyangbin/Workspace/dev/golang/pkg/mod/cache/vcs/71c6fba555fd7b185c93dcad3ed507d63007e825cf56a4a329b0e102990a7036: exit status 128:
	error: RPC failed; curl 18 transfer closed with outstanding read data remaining
	fatal: the remote end hung up unexpectedly
	fatal: early EOF
	fatal: index-pack failed
go: error loading module requirements

**Comment by hanchuanchuan** [comment]
报错信息是下载包失败了，网络超时，可以检查一下网络。

**Comment by oyb001** [comment]
https://gopkg.in/mgo.v2,这个页面是可以打开的，google也可以打开，我还可以进行哪些网络检测？

**Comment by hanchuanchuan** [comment]
手动下载报错的依赖包即可，记得使用go mod依赖管理，代码不要放在go path目录下。

**Comment by oyb001** [comment]
手动下载命令: go get gopkg.in/mgo.v2
go mod的开关是打开的:_INTELLIJ_FORCE_SET_GO111MODULE=on
记得使用go mdo依赖管理，具体指什么操作？
代码不要放在go path目录下面-是指 gopkg.in下载放到goroot/src里面不？

**Comment by hanchuanchuan** [comment]
可以先了解一下go mod。使用该模式后依赖会自动下载到$GOPATH/pkg/mod文件夹。
开关是`GO111MODULE=on`，IDE变量不太清楚。
问题还没有解决吗，如果有些包因网络问题下载不了，可以搜一下github是否有镜像，
如果有的话修改`go.mod`文件，用replace替换。

**Comment by oyb001** [comment]
上网搜索了一下，在go.mod里面替换了地址，但是提示无效的模块版本，github里面明明有
replace gopkg.in/mgo.v2 => github.com/go-mgo/mgo vr2016.08.01
以下是报错 信息:
go: finding github.com/go-mgo/mgo vr2016.08.01
go: errors parsing go.mod:
/Users/ouyangbin/Documents/001_work/01_git/goInception/go.mod:11: invalid module version github.com/go-mgo/mgo: unknown revision vr2016.08.01

**Comment by oyb001** [comment]
网络问题，在网络好的时候，多试试。
