### ISSUE TITLE
返回的审核信息

### ISSUE THREAD

**Issue by gdsea** [hanchuanchuan/goInception#83]
**描述您想要的功能：**
我在部署archery时使用了goinception，但是审核信息反人类，与inception相比，差太多了，例如当新建表时，我使用了关键字，
会提示如下报错
line 3 column 9 near " varchar(20) not null,primary key(id) ) ENGINE=InnoDB" (total length 151)
--
另外好多报错类似于total length xxx

**Comment by hanchuanchuan** [comment]
嗯，好的，可以不用的哈~

**Comment by gdsea** [comment]
哈哈，作者很有礼貌，我错咯，对不起
