### ISSUE TITLE
mysql关键字参数设置后没有效果

### ISSUE THREAD

**Issue by securityBoB** [hanchuanchuan/goInception#85]
**描述**
对问题简单清晰的描述

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mysql/mariadb]
 - 版本: [例如 5.7.21]

**参数**
可能与问题相关的设置参数

**Comment by securityBoB** [comment]
+----------+---------+-------------+-----------------+---------------+---------------------------------------------------------------------------+---------------+--------------+---------------+--------------+---------+-------------+
| order_id |  stage  | error_level |   stage_status  | error_message |                                    sql                                    | affected_rows |   sequence   | backup_dbname | execute_time | sqlsha1 | backup_time |
+----------+---------+-------------+-----------------+---------------+---------------------------------------------------------------------------+---------------+--------------+---------------+--------------+---------+-------------+
|    1     | CHECKED |      0      | Audit Completed |      None     |                                  use test                                 |       0       | 0_0_00000000 |      None     |      0       |   None  |      0      |
|    2     | CHECKED |      0      | Audit Completed |      None     |                      CREATE TABLE `service_station` (                     |       0       | 0_0_00000001 |      None     |      0       |   None  |      0      |
|          |         |             |                 |               |        `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',      |               |              |               |              |         |             |
|          |         |             |                 |               |           `name` varchar(255) NOT NULL DEFAULT '' COMMENT '名称',         |               |              |               |              |         |             |
|          |         |             |                 |               |       `description` varchar(3000) NOT NULL DEFAULT '' COMMENT '详情',     |               |              |               |              |         |             |
|          |         |             |                 |               |     `img_url` varchar(4000) NOT NULL DEFAULT '' COMMENT '服务器站照片',   |               |              |               |              |         |             |
|          |         |             |                 |               |        `address` varchar(255) NOT NULL DEFAULT '' COMMENT '详细地址',     |               |              |               |              |         |             |
|          |         |             |                 |               |         `linkman` varchar(255) NOT NULL DEFAULT '' COMMENT '联系人',      |               |              |               |              |         |             |
|          |         |             |                 |               |           `phone` varchar(255) NOT NULL DEFAULT '' COMMENT '电话',        |               |              |               |              |         |             |
|          |         |             |                 |               |         `longitude` varchar(255) NOT NULL DEFAULT '' COMMENT '经度',      |               |              |               |              |         |             |
|          |         |             |                 |               |         `latitude` varchar(255) NOT NULL DEFAULT '' COMMENT '纬度',       |               |              |               |              |         |             |
|          |         |             |                 |               |                              PRIMARY KEY (`id`)                           |               |              |               |              |         |             |
|          |         |             |                 |               | ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='服务站' |               |              |               |              |         |             |
+----------+---------+-------------+-----------------+---------------+---------------------------------------------------------------------------+---------------+--------------+---------------+--------------+---------+-------------+
['order_id', 'stage', 'error_level', 'stage_status', 'error_message', 'sql', 'affected_rows', 'sequence', 'backup_dbname', 'execute_time', 'sqlsha1', 'backup_time']
0
None

**Comment by securityBoB** [comment]
![image](https://user-images.githubusercontent.com/20141355/65561171-1c915e00-df74-11e9-9a8c-e086c073cca6.png)

**Comment by hanchuanchuan** [comment]
参数 `enable_identifer_keyword` 设置为 `true` 时表示允许关键字，所以需要设置为 ` false` ：
`inception set enable_identifer_keyword = false`
另外，由于使用的是TiDB的关键字列表，所以`name`和`description`均未列为关键字。

**Comment by securityBoB** [comment]
谢谢,对的,我是试了 false 和true 都限制不住,才来提的issue,现在明白了  name 这里不是当做关键字.
