### ISSUE TITLE
TiDB数据库兼容问题

### ISSUE THREAD

**Issue by MonkeyFang** [hanchuanchuan/goInception#86]
在调用goInception解析tidb的update执行计划时出现报错，报错如下：

sql: Scan error on column index 0, name "id": converting driver.Value type []uint8 ("TableReader_6") to a uint: invalid syntax; sql: Scan error on column index 0, name "id": converting driver.Value type []uint8 ("└─Selection_5") to a uint: invalid syntax; sql: Scan error on column index 0, name "id": converting driver.Value type []uint8 ("  └─TableScan_4") to a uint: invalid syntax.

手工在tidb explain时，没有出现问题

**Comment by hanchuanchuan** [comment]
好的，感谢指出。

**Comment by MonkeyFang** [comment]
不用谢，delete也是同样的报错，但create，drop，alter ，select，insert是可以的。

**Comment by hanchuanchuan** [comment]
已修复该问题。docker版本已更新，release二进制版本稍后发布。

**Comment by MonkeyFang** [comment]
感谢
