### ISSUE TITLE
求支持连接安全加密。

### ISSUE THREAD

**Issue by suliuer** [hanchuanchuan/goInception#92]
**描述您想要的功能：**
启动时有显示：server.go:196: [info] Secure connection is NOT ENABLED
远程连接不加密，对业务业说十分危险。希望能添加连接安全加密的功能。

**描述您考虑过的解决/替代方案：**

**可参考文档,资料,引用等：**

**Comment by hanchuanchuan** [comment]
创建安全用户时做了哪种限制呢? `require SSL` 还是 `require X509` , 这会影响连接设置方式

**Comment by hanchuanchuan** [comment]
已添加安全连接设置选项  #98 

详细使用文档和示例请查看 [mysql加密连接设置](https://hanchuanchuan.github.io/goInception/params/#mysql)
