### ISSUE TITLE
MariaDB v100022 not supported yet,please confirm that the rollback sql is correct

### ISSUE THREAD

**Issue by liyangbing** [hanchuanchuan/goInception#93]
MariaDB数据库执行
执行结果提示：
MariaDB v100022 not supported yet,please confirm that the rollback sql is correct

**Comment by hanchuanchuan** [comment]
该问题原因是MariaDB在更高版本时, DML的binlog事件移除了QueryEvent, 导致无法正确获取执行线程号,
此时如果操作表有并发操作,回滚语句可能增多.添加该提示以提醒进行二次确认.
