### ISSUE TITLE
Backup: **Corrupted replication event was detected Got packets out of order

### ISSUE THREAD

**Issue by liyangbing** [hanchuanchuan/goInception#95]
**描述**

update table  set snapshot_id=id WHERE snapshot_id=0 | 失败 | 1746 | 
### Backup: **Corrupted replication event was detected.

update table  set snapshot_id=id WHERE snapshot_id=0 | 失败 | 247 | 
### Backup: Got packets out of order

**重现**
模拟重现的步骤

**环境**
 - 数据库: [mariadb]

**参数**
--enable-remote-backup  true

**Comment by alvinhmg** [comment]
同样遇到，请求解答

**Comment by hanchuanchuan** [comment]
麻烦发一下goinception的详细日志

**Comment by hanchuanchuan** [comment]
该问题没能复现，需要提供更详细的信息。

**Comment by alvinhmg** [comment]
谢谢解答，这个应该不是GoInception的问题，麻烦了
