### ISSUE TITLE
binlog日志未开启,无法备份!

### ISSUE THREAD

**Issue by yanlingsishao** [hanchuanchuan/goInception#99]
**描述**
使用备份参数，binlog日志未开启,无法备份!
![image](https://user-images.githubusercontent.com/28887713/67919979-758c8b80-fbdd-11e9-8460-892821ce9be0.png)

**重现**
mysql已经做了binlog，但是还是无法备份
![image](https://user-images.githubusercontent.com/28887713/67920033-aa98de00-fbdd-11e9-8d03-62cbcbfd71f7.png)
参数如下
--user=root;--password=;--host=10.1.1.38;--check=0;--port=3306;--execute=1;--backup=1;

**环境**
 - 数据库: [mariadb]
 - 版本: [例如 5.5.60]

**参数**
是不是还需要配置什么参数

**Comment by hanchuanchuan** [comment]
不需要其他参数，备份功能前置条件会验证 `log_bin` 是否开启，
可以打开 MariaDB的 `general_log` 看一下goinception服务发送的SQL
